import { useEffect, useRef, useState } from 'react';
import type { Chapter } from '../api';
import { Badge, Button, Panel, StatusMessage } from '../ui/primitives';
import { type ExperimentalClient, type Row, type Rows, segment } from './api';
import { Details, Field, Form, RecordStatus, Refresh, ResourceState, useAction, useResource } from './shared';
function SegmentEditor({ client, plan, item, profiles, refresh }: { client: ExperimentalClient; plan: Row; item: Row; profiles: Row[]; refresh: () => void }) {
  const [character, setCharacter] = useState(item.character_id || ''), [profile, setProfile] = useState(item.profile_id || ''), [emotion, setEmotion] = useState(item.emotion), [style, setStyle] = useState(item.speaking_style || ''), [reviewed, setReviewed] = useState(item.attribution_status === 'REVIEWED'), [asset, setAsset] = useState('');
  const action = useAction(refresh), path = `/audiobook/plans/${segment(plan.id)}/segments/${segment(item.id)}`;
  const busy = action.busy;
  return <article className="experimental-record" aria-label={`有声片段 ${item.kind}`}><div className="experimental-actions"><Badge>{item.kind}</Badge><Badge tone={item.attribution_status === 'NEEDS_REVIEW' ? 'warning' : 'neutral'}>{item.attribution_status}</Badge><Badge>{item.timing_status}</Badge></div><p>{item.text}</p><p>时间线：{item.start_ms == null || item.end_ms == null ? '未测量，完整边界未知' : `${item.start_ms}–${item.end_ms} ms`}</p><Details label="对白归属证据与原文 offset" value={{ evidence: item.attribution_evidence, start: item.source_start, end: item.source_end, digest: item.source_text_digest }} />{action.feedback}
    <Field label="片段人物 ID（旁白为 __narrator__）"><input disabled={item.kind === 'NARRATION'} value={character} onChange={event => setCharacter(event.target.value)} /></Field><Field label="片段声音 Profile"><select value={profile} onChange={event => setProfile(event.target.value)}><option value="">尚未分配</option>{profiles.map(row => <option key={row.id} value={row.id}>{row.display_name}</option>)}</select></Field><Field label="片段情绪标签"><input value={emotion} onChange={event => setEmotion(event.target.value)} /></Field><Field label="片段说话风格"><input value={style} onChange={event => setStyle(event.target.value)} /></Field>{item.kind === 'DIALOGUE' && <label className="experimental-check"><input type="checkbox" checked={reviewed} onChange={event => setReviewed(event.target.checked)} />已人工核对白归属</label>}
    <Button disabled={busy || plan.status !== 'PENDING_REVIEW'} onClick={() => action.run(() => client.put(path, { expected_version: plan.version, character_id: character || null, profile_id: profile || null, emotion, speaking_style: style, attribution_reviewed: reviewed }), '片段元数据已保存')}>保存片段归属与风格</Button>
    <Field label="实测片段音频资产 ID"><input value={asset} onChange={event => setAsset(event.target.value)} /></Field><Button disabled={busy || !asset || plan.status !== 'PENDING_REVIEW'} onClick={() => action.run(() => client.put(`${path}/audio`, { expected_version: plan.version, asset_id: asset }), '已绑定实测音频')}>绑定实测片段音频</Button>
  </article>;
}
export function AudiobookPanel(props: { client: ExperimentalClient; chapter?: Chapter; requestedPlanId?: string }) {
  const identity = useRef({ client: props.client, generation: 0 });
  if (identity.current.client !== props.client) identity.current = { client: props.client, generation: identity.current.generation + 1 };
  return <AudiobookContent key={identity.current.generation} {...props} />;
}
function AudiobookContent({ client, chapter, requestedPlanId }: { client: ExperimentalClient; chapter?: Chapter; requestedPlanId?: string }) {
  const resource = useResource(async signal => { const [capabilities, profiles, mappings, plans] = await Promise.all([client.get('/audiobook/capabilities', signal), client.get<Rows>('/audiobook/profiles', signal), client.get<Rows>('/audiobook/mappings', signal), client.get<Rows>('/audiobook/plans', signal)]); return { capabilities, profiles: profiles.items, mappings: mappings.items, plans: plans.items }; }, [client]);
  const action = useAction(resource.reload);
  const [name, setName] = useState(''), [provider, setProvider] = useState(''), [model, setModel] = useState(''), [voice, setVoice] = useState(''), [license, setLicense] = useState('');
  const [character, setCharacter] = useState('__narrator__'), [profile, setProfile] = useState(''), [chapterId, setChapterId] = useState(chapter?.id || ''), [title, setTitle] = useState(''), [planId, setPlanId] = useState(''), [manifest, setManifest] = useState<any>(), [subtitles, setSubtitles] = useState<any>();
  const [trackKind, setTrackKind] = useState('MUSIC'), [trackLabel, setTrackLabel] = useState(''), [trackAsset, setTrackAsset] = useState('');
  const plan = resource.data?.plans.find(row => row.id === planId);
  useEffect(() => { if (!planId && resource.data?.plans[0]) setPlanId(resource.data.plans[0].id); }, [planId, resource.data]);
  useEffect(() => { setManifest(undefined); setSubtitles(undefined); }, [planId, plan?.version]);
  const located = useRef<string>();
  useEffect(() => { if (requestedPlanId && !resource.loading && !resource.error && resource.data?.plans.some(row => row.id === requestedPlanId) && located.current !== requestedPlanId) { located.current = requestedPlanId; setPlanId(requestedPlanId); } }, [requestedPlanId, resource.loading, resource.error, resource.data]);
  const review = (operation: string) => plan && action.run(() => client.post(`/audiobook/plans/${segment(plan.id)}/${operation}`, { expected_version: plan.version }), '有声计划审核已更新');
  const busy = action.busy || resource.loading;
  return <Panel title="有声小说 V2 · 归属与混音准备" actions={<Refresh reload={resource.reload} busy={busy} />}>
    <StatusMessage>无法确定的对白为 NEEDS_REVIEW。时长只来自实测音频资产；无音素对齐或精准口型模型时保持 NOT_CONFIGURED。</StatusMessage>{action.feedback}<ResourceState loading={resource.loading} error={resource.error} /><Details label="TTS / Mixer / 字幕能力" value={resource.data?.capabilities} />
    <Form onSubmit={() => action.run(async () => { const row = await client.post<Row>('/audiobook/profiles', { display_name: name, provider_id: provider, model_id: model, voice_id: voice, license_note: license }); setProfile(row.id); }, '声音 Profile 已保存；音质尚未验证')}><h3>声音 Profile（仅身份与许可元数据）</h3><Field label="声音 Profile 名称"><input required value={name} onChange={event => setName(event.target.value)} /></Field><Field label="声音 Provider ID"><input required value={provider} onChange={event => setProvider(event.target.value)} /></Field><Field label="声音 Model ID"><input required value={model} onChange={event => setModel(event.target.value)} /></Field><Field label="Voice ID"><input required value={voice} onChange={event => setVoice(event.target.value)} /></Field><Field label="声音许可说明"><textarea required value={license} onChange={event => setLicense(event.target.value)} /></Field><Button type="submit" disabled={busy}>保存声音 Profile</Button></Form>
    <Form onSubmit={() => action.run(() => { const previous = resource.data?.mappings.find(row => row.character_id === character); return client.post('/audiobook/mappings', { character_id: character, profile_id: profile, ...(previous ? { expected_version: previous.version } : {}) }); }, '人物声音映射已保存')}><Field label="声音映射人物 ID"><input required value={character} onChange={event => setCharacter(event.target.value)} /></Field><Field label="映射声音 Profile"><select required value={profile} onChange={event => setProfile(event.target.value)}><option value="">选择声音</option>{resource.data?.profiles.map(row => <option key={row.id} value={row.id}>{row.display_name}</option>)}</select></Field><Button type="submit" disabled={busy || !profile || !character}>保存人物声音映射</Button></Form><Details label="现有声音映射" value={resource.data?.mappings} />
    <Form onSubmit={() => action.run(async () => { const row = await client.post<Row>('/audiobook/plans', { chapter_id: chapterId, title }); setPlanId(row.id); }, '对白序列已拆分，等待人工审核')}><Field label="有声计划来源章节 ID"><input required value={chapterId} onChange={event => setChapterId(event.target.value)} /></Field><Field label="有声计划标题"><input value={title} onChange={event => setTitle(event.target.value)} /></Field><Button type="submit" disabled={busy || !chapterId}>创建对白序列计划</Button></Form>
    {!!resource.data?.plans.length && <Field label="有声计划"><select disabled={busy} value={planId} onChange={event => { setPlanId(event.target.value); setManifest(undefined); setSubtitles(undefined); }}>{resource.data.plans.map(row => <option key={row.id} value={row.id}>{row.title} · {row.status}</option>)}</select></Field>}
    {requestedPlanId && !resource.loading && !resource.error && !resource.data?.plans.some(row => row.id === requestedPlanId) && <StatusMessage tone="warning">请求的有声计划在当前权限下不可用。</StatusMessage>}
    {plan && <section className="experimental-section" aria-label="有声计划详情"><RecordStatus row={plan} /><p>待核对白：{plan.needs_review_count} · 时长：{plan.duration_ms == null ? 'UNMEASURED' : `${plan.duration_ms} ms`}</p><Details value={plan.sources} label="有声计划来源版本" /><div className="experimental-list">{plan.segments.map((item: Row) => <SegmentEditor key={`${item.id}:${plan.version}`} client={client} plan={plan} item={item} profiles={resource.data?.profiles || []} refresh={resource.reload} />)}</div>
      <Form onSubmit={() => action.run(() => client.post(`/audiobook/plans/${segment(plan.id)}/tracks`, { expected_version: plan.version, kind: trackKind, label: trackLabel, asset_id: trackAsset || null }), '混音轨道槽位已添加')}><h3>混音轨道槽位</h3><Field label="轨道类型"><select value={trackKind} onChange={event => setTrackKind(event.target.value)}>{['MUSIC', 'AMBIENCE', 'SFX'].map(value => <option key={value}>{value}</option>)}</select></Field><Field label="轨道名称"><input required value={trackLabel} onChange={event => setTrackLabel(event.target.value)} /></Field><Field label="轨道音频资产 ID（可留空）"><input value={trackAsset} onChange={event => setTrackAsset(event.target.value)} /></Field><Button type="submit" disabled={busy || plan.status !== 'PENDING_REVIEW'}>添加混音轨道槽位</Button></Form><Details label="背景音乐 / 环境 / 音效轨道" value={plan.tracks} />
      <div className="experimental-actions"><Button disabled={busy} onClick={() => action.run(async () => setManifest(await client.get(`/audiobook/plans/${segment(plan.id)}/duration-manifest`)), '时长清单已读取')}>查看时长清单</Button><Button disabled={busy || plan.timing_status !== 'MEASURED'} onClick={() => action.run(async () => setSubtitles(await client.get(`/audiobook/plans/${segment(plan.id)}/subtitles`)), '片段字幕已读取')}>查看片段字幕</Button>{plan.status === 'PENDING_REVIEW' && <><Button disabled={busy || plan.stale || plan.needs_review_count > 0 || plan.segments.some((item: Row) => !item.profile_id)} onClick={() => review('approve')}>批准有声计划</Button><Button disabled={busy} onClick={() => review('reject')}>驳回有声计划</Button></>}{['APPROVED', 'REJECTED'].includes(plan.status || '') && <Button disabled={busy} onClick={() => review('reopen')}>重开有声审核</Button>}</div>
    </section>}{manifest && plan?.id === manifest.plan_id && plan?.version === manifest.plan_version && <Details label="实测时长清单" value={manifest} />}{subtitles && plan?.id === subtitles.plan_id && plan?.version === subtitles.plan_version && <Details label="片段级字幕（无音素对齐）" value={subtitles} />}
  </Panel>;
}
