import { useState } from 'react';
import { Badge, Button, Panel, StatusMessage } from '../ui/primitives';
import { type ExperimentalClient, type Row, type Rows, segment } from './api';
import { Details, Field, Form, RecordStatus, Refresh, ResourceState, useAction, useResource } from './shared';
export function EmbeddingPanel({ client }: { client: ExperimentalClient }) {
  const resource = useResource(async signal => { const [status, indexes] = await Promise.all([client.get('/embeddings/status', signal), client.get<Rows>('/embeddings/indexes', signal)]); return { status, indexes: indexes.items }; }, [client]);
  const action = useAction(resource.reload), [title, setTitle] = useState(''), [type, setType] = useState('ASSET'), [entity, setEntity] = useState(''), [screenplay, setScreenplay] = useState(''), [indexId, setIndexId] = useState(''), [query, setQuery] = useState(''), [result, setResult] = useState<any>();
  const configured = resource.data?.status.status === 'CONFIGURED' && !!resource.data.status.capability;
  const transition = (row: Row, operation: string) => action.run(() => client.post(`/embeddings/indexes/${segment(row.id)}/${operation}`, { expected_version: row.version }), '索引状态已更新');
  const busy = action.busy || resource.loading;
  return <Panel title="可选视觉 Embedding" actions={<Refresh reload={resource.reload} busy={busy} />}>
    {action.feedback}<ResourceState loading={resource.loading} error={resource.error} />{resource.data && <><Badge tone={configured ? 'info' : 'warning'}>{resource.data.status.status}</Badge><StatusMessage>{configured ? '请检查 provider capability、模型身份与验证级别。' : '未配置真实 Embedding Provider。查询与重建不可用；不会回退为假向量或词法匹配。'}</StatusMessage><Details value={resource.data.status} label="Provider capability 与模型身份" /></>}
    <Form onSubmit={() => action.run(async () => { const value = await client.post<Row>('/embeddings/indexes', { title, entities: [{ entity_type: type, entity_id: entity, ...(screenplay ? { screenplay_id: screenplay } : {}) }] }); setIndexId(value.id); }, '索引定义已创建，尚未生成向量')}><Field label="向量索引标题"><input required value={title} onChange={event => setTitle(event.target.value)} /></Field><Field label="索引实体类型"><select value={type} onChange={event => setType(event.target.value)}>{['ASSET', 'CHARACTER', 'SCENE'].map(value => <option key={value}>{value}</option>)}</select></Field><Field label="索引实体 ID"><input required value={entity} onChange={event => setEntity(event.target.value)} /></Field>{type === 'SCENE' && <Field label="索引场景所属剧本 ID"><input value={screenplay} onChange={event => setScreenplay(event.target.value)} /></Field>}<Button type="submit" disabled={busy || !title || !entity}>保存索引定义</Button></Form>
    <div className="experimental-list">{resource.data?.indexes.map(row => <article className="experimental-record" key={row.id}><h3>{row.title}</h3><RecordStatus row={row} /><Details value={row} label="索引版本 / 模型 / digest / lineage" /><div className="experimental-actions"><Button disabled={busy || !configured} onClick={() => transition(row, 'rebuild')}>重建向量索引</Button><Button disabled={busy || row.status === 'REMOVED'} onClick={() => transition(row, 'invalidate')}>标记索引失效</Button><Button disabled={busy || row.status === 'REMOVED'} onClick={() => transition(row, 'remove')}>移除索引记录</Button></div></article>)}</div>
    <Form onSubmit={() => action.run(async () => setResult(await client.post('/embeddings/query', { index_id: indexId, text: query, limit: 10 })), '向量查询已完成')}><Field label="查询向量索引"><select value={indexId} onChange={event => setIndexId(event.target.value)}><option value="">选择索引</option>{resource.data?.indexes.map(row => <option key={row.id} value={row.id}>{row.title}</option>)}</select></Field><Field label="视觉向量查询"><input value={query} onChange={event => setQuery(event.target.value)} /></Field><Button type="submit" disabled={busy || !configured || !indexId || !query}>查询向量</Button></Form>{result && <Details value={result} label="向量相似度与来源" />}
  </Panel>;
}
