import { useEffect, useState } from 'react';
import type { Chapter } from '../api';
import { Badge, Button, Panel, StatusMessage } from '../ui/primitives';
import { type ExperimentalClient, type Row, type Rows, segment } from './api';
import { Details, Field, Form, RecordStatus, Refresh, ResourceState, ids, useAction, useResource } from './shared';

export function RegistryPanel({ client }: { client: ExperimentalClient }) {
  const resource = useResource(signal => client.get('/media/adapters', signal), [client]);
  return <Panel title="Media Workflow Adapter Registry" actions={<Refresh reload={resource.reload} />}><StatusMessage>模型发现与可运行 Workflow 分离。ADAPTER_REQUIRED 不可运行；Mock 仅验证任务与审核契约。</StatusMessage><ResourceState loading={resource.loading} error={resource.error} /><Details label="IMAGE / VIDEO / AUDIO 操作契约" value={resource.data?.operations} /><div className="experimental-list">{resource.data?.items?.map((row: Row) => <article className="experimental-record" key={row.adapter_id}><h3>{row.family}</h3><div className="experimental-actions"><Badge>{row.modality}</Badge><Badge tone={row.runnable ? 'info' : 'warning'}>{row.state}</Badge><span>{row.runnable ? '具备可运行实现' : '尚无可运行实现'}</span></div><p>{row.operations.join(' · ')}</p><Details label="Adapter 身份与限制" value={row} /></article>)}</div></Panel>;
}
function ProposalImage({ client, row }: { client: ExperimentalClient; row: Row }) {
  const [url, setUrl] = useState(''), [failed, setFailed] = useState(false);
  useEffect(() => {
    const controller = new AbortController(); let objectUrl = '';
    client.blob(`/media/proposals/${segment(row.id)}/preview`, controller.signal).then(blob => { if (!controller.signal.aborted) { objectUrl = URL.createObjectURL(blob); setUrl(objectUrl); } }).catch(() => { if (!controller.signal.aborted) setFailed(true); });
    return () => { controller.abort(); if (objectUrl) URL.revokeObjectURL(objectUrl); };
  }, [client, row.id]);
  return url ? <img className="experimental-preview" src={url} alt={`${row.kind} MOCK_ONLY 候选 ${(row.candidate_index ?? 0) + 1}`} /> : failed ? <StatusMessage tone="error">预览暂不可读</StatusMessage> : <p>正在读取候选预览…</p>;
}
export function MediaPanel({ client, chapter }: { client: ExperimentalClient; chapter?: Chapter }) {
  const resource = useResource(async signal => { const [covers, storyboards, tasks, proposals] = await Promise.all([client.get<Rows>('/media/cover-briefs', signal), client.get<Rows>('/media/storyboard-briefs', signal), client.get<Rows>('/media/tasks', signal), client.get<Rows>('/media/proposals', signal)]); return { briefs: [...covers.items, ...storyboards.items], tasks: tasks.items, proposals: proposals.items }; }, [client]);
  const action = useAction(resource.reload);
  const [title, setTitle] = useState(''), [subtitle, setSubtitle] = useState(''), [genre, setGenre] = useState(''), [characters, setCharacters] = useState(''), [palette, setPalette] = useState(''), [composition, setComposition] = useState(''), [prompt, setPrompt] = useState(''), [safeArea, setSafeArea] = useState(.08);
  const [screenplay, setScreenplay] = useState(''), [shot, setShot] = useState(''), [screenplayVersion, setScreenplayVersion] = useState(1);
  const [briefId, setBriefId] = useState(''), [selected, setSelected] = useState<string[]>([]), [comparison, setComparison] = useState<any>();
  const brief = resource.data?.briefs.find(row => row.id === briefId);
  useEffect(() => { if (!briefId && resource.data?.briefs[0]) setBriefId(resource.data.briefs[0].id); }, [briefId, resource.data]);
  const transition = (row: Row, operation: string, collection = 'tasks') => action.run(() => client.post(`/media/${collection}/${segment(row.id)}/${operation}`, { expected_version: row.version }), '媒体状态已更新');
  const busy = action.busy || resource.loading;
  return <Panel title="封面与分镜生成工作流" actions={<Refresh reload={resource.reload} busy={busy} />}>
    <StatusMessage>本入口仅运行显式 MOCK_ONLY 图像。真实图像质量、GPU 和商业 Provider 尚未验证。批准才生成正式资产与 lineage。</StatusMessage>{action.feedback}<ResourceState loading={resource.loading} error={resource.error} />
    <Form onSubmit={() => action.run(async () => { const value = await client.post<Row>('/media/cover-briefs', { title, subtitle, genre, character_ids: ids(characters), palette: ids(palette), composition, prompt, safe_area: { left: safeArea, right: safeArea, top: safeArea, bottom: safeArea, units: 'FRACTION' }, chapter_ids: chapter ? [chapter.id] : [], privacy_level: 'LOCAL_ONLY' }); setBriefId(value.id); setTitle(''); }, '封面 Brief 已保存')}>
      <h3>Cover Brief</h3><Field label="封面标题"><input required value={title} onChange={event => setTitle(event.target.value)} /></Field><Field label="封面副标题"><input value={subtitle} onChange={event => setSubtitle(event.target.value)} /></Field><Field label="封面类型"><input value={genre} onChange={event => setGenre(event.target.value)} /></Field><Field label="封面关键人物 ID"><input value={characters} onChange={event => setCharacters(event.target.value)} /></Field><Field label="封面调色板（逗号分隔）"><input value={palette} onChange={event => setPalette(event.target.value)} /></Field><Field label="封面构图"><textarea value={composition} onChange={event => setComposition(event.target.value)} /></Field><Field label="安全边距比例"><input type="number" min={0} max={.49} step={.01} value={safeArea} onChange={event => setSafeArea(Number(event.target.value))} /></Field><Field label="媒体生成说明"><textarea value={prompt} onChange={event => setPrompt(event.target.value)} /></Field><Button type="submit" disabled={busy || !title.trim()}>保存封面 Brief</Button>
    </Form>
    <Form onSubmit={() => action.run(async () => { const value = await client.post<Row>('/media/storyboard-briefs', { screenplay_id: screenplay, shot_id: shot, expected_screenplay_version: screenplayVersion, prompt, privacy_level: 'LOCAL_ONLY' }); setBriefId(value.id); }, '分镜 Brief 已保存')}><h3>Shot → Storyboard Brief</h3><Field label="分镜剧本 ID"><input required value={screenplay} onChange={event => setScreenplay(event.target.value)} /></Field><Field label="分镜 Shot ID"><input required value={shot} onChange={event => setShot(event.target.value)} /></Field><Field label="剧本当前编辑版本"><input type="number" min={1} value={screenplayVersion} onChange={event => setScreenplayVersion(Number(event.target.value))} /></Field><Button type="submit" disabled={busy || !screenplay || !shot}>从 Shot 创建分镜 Brief</Button></Form>
    <section className="experimental-section"><Field label="待生成媒体 Brief"><select value={briefId} onChange={event => setBriefId(event.target.value)}><option value="">选择 Brief</option>{resource.data?.briefs.map(row => <option key={row.id} value={row.id}>{row.kind} · {row.title || row.shot_id} · v{row.version}</option>)}</select></Field>{brief && <Details value={brief} label="Brief 与来源版本" />}<Button disabled={busy || !brief} onClick={() => action.run(() => client.post('/media/tasks', { brief_id: brief!.id, expected_brief_version: brief!.version, adapter_id: 'mock-image-v1', candidate_count: 2 }), 'MOCK_ONLY 媒体任务已排队')}>创建 Mock 图像任务</Button></section>
    <div className="experimental-list">{resource.data?.tasks.map(row => <article className="experimental-record" key={row.id} aria-label="媒体任务"><h3>{row.operation}</h3><RecordStatus row={row} /><Badge>{row.adapter_definition?.state}</Badge><div className="experimental-actions">{row.status === 'QUEUED' && <Button disabled={busy} onClick={() => transition(row, 'execute')}>执行 Mock 图像任务</Button>}{['QUEUED', 'RUNNING'].includes(row.status || '') && <Button disabled={busy} onClick={() => transition(row, 'cancel')}>取消媒体任务</Button>}{(['FAILED', 'CANCELLED'].includes(row.status || '') || row.recoverable) && <Button disabled={busy} onClick={() => transition(row, 'retry')}>重试媒体任务</Button>}</div><Details value={row} label="任务契约与来源" /></article>)}</div>
    <Button disabled={busy || selected.length < 2} onClick={() => action.run(async () => setComparison(await client.post('/media/proposals/compare', { proposal_ids: selected })), '媒体比较已更新')}>比较已选媒体候选</Button>
    {comparison && <section className="experimental-record" aria-label="媒体候选比较"><h3>媒体候选比较 · 未执行质量评分</h3><div className="experimental-grid">{comparison.items.map((row: Row) => <div key={row.id}><ProposalImage client={client} row={row} /><Details value={row} label={`候选 ${row.candidate_index + 1} 的模型 / digest / lineage`} /></div>)}</div></section>}
    <div className="experimental-list">{resource.data?.proposals.map(row => <article className="experimental-record" key={row.id} aria-label={`媒体候选 ${row.candidate_index + 1}`}><label className="experimental-check"><input type="checkbox" checked={selected.includes(row.id)} onChange={event => setSelected(current => event.target.checked ? [...current, row.id] : current.filter(id => id !== row.id))} />{row.kind} 候选 {row.candidate_index + 1}</label><RecordStatus row={row} /><Badge>{row.verification}</Badge><ProposalImage client={client} row={row} /><Details value={{ source_digest: row.source_digest, sources: row.sources, asset_id: row.asset_id, lineage: row.lineage }} label="来源与正式资产血缘" /><div className="experimental-actions">{row.status === 'PENDING_REVIEW' && <><Button disabled={busy || row.stale} onClick={() => transition(row, 'approve', 'proposals')}>批准媒体为资产</Button><Button disabled={busy} onClick={() => transition(row, 'reject', 'proposals')}>驳回媒体候选</Button></>}{row.status === 'REJECTED' && <Button disabled={busy} onClick={() => transition(row, 'reopen', 'proposals')}>重开媒体审核</Button>}</div></article>)}</div>
  </Panel>;
}
