import { useEffect, useRef, useState } from 'react';
import { Badge, Button, EmptyState, Panel, StatusMessage } from '../ui/primitives';
import type { Row } from './api';
import type { BrokerApi, BrokerRoute } from './modelBrokerClient';
import { Details, Field, ResourceState, useAction, useResource } from './shared';

type TestCase = { title: string; kind: string; prompt: string; rule: string; expected: string[] };
const emptyCase = (): TestCase => ({ title: '中文续写样本', kind: 'CHINESE_CONTINUATION', prompt: '', rule: 'NONEMPTY', expected: [] });
const kinds = [['CHINESE_CONTINUATION', '中文续写'], ['STRUCTURED_EXTRACTION', '结构化提取'], ['SHORT_REVIEW', '短审稿'], ['TOOL_PROTOCOL', '工具协议（只核对文本，不执行工具）'], ['IMAGE_WORKFLOW', '本地图片流程（单图实测）'], ['VIDEO_WORKFLOW', '指定视频流程（结果导入）']];
const uuid = () => globalThis.crypto?.randomUUID?.() || `benchmark-${Date.now()}-${Math.random()}`;
export function ModelBenchmarkPanel({ api, routes }: { api: BrokerApi; routes: BrokerRoute[] }) {
  const resource = useResource(signal => api.benchmarks(signal), [api]);
  const profiles = useResource(async signal => { const value = await api.capabilityProfiles(signal); if (!Array.isArray(value.items)) throw new Error('能力档案响应无效'); return value; }, [api]);
  const [title, setTitle] = useState(''), [cases, setCases] = useState<TestCase[]>([emptyCase()]), [repetitions, setRepetitions] = useState(1), [output, setOutput] = useState(128), [seconds, setSeconds] = useState(30), [budget, setBudget] = useState(0);
  const [editing, setEditing] = useState<Row>(), [setId, setSetId] = useState(''), [routeId, setRouteId] = useState('');
  const [left, setLeft] = useState(''), [right, setRight] = useState(''), [comparison, setComparison] = useState<Row>();
  const [importText, setImportText] = useState(''), [importError, setImportError] = useState('');
  const alive = useRef(true), inputEpoch = useRef(0), importEpoch = useRef(0), requestId = useRef(uuid());
  useEffect(() => { alive.current = true; return () => { alive.current = false; inputEpoch.current++; importEpoch.current++; }; }, []);
  const action = useAction(resource.reload);
  const currentSet = resource.data?.sets.find(r => r.id === setId);
  const runKinds = new Set<string>(currentSet?.cases.map((row: TestCase) => row.kind) || []);
  const capability = runKinds.size === 1 && runKinds.has('IMAGE_WORKFLOW') ? 'IMAGE' : runKinds.has('IMAGE_WORKFLOW') || runKinds.has('VIDEO_WORKFLOW') ? null : 'TEXT';
  const validRoutes = routes.filter(r => r.available && !r.cloud && r.capability === capability);
  const validRoute = validRoutes.some(r => r.route_id === routeId);
  const changed = () => { inputEpoch.current++; requestId.current = uuid(); };
  const reset = () => { changed(); setEditing(undefined); setTitle(''); setCases([emptyCase()]); };
  const edit = (row: Row) => { changed(); setEditing(row); setTitle(row.title); setCases(row.cases); setRepetitions(row.repetitions); setOutput(row.max_output_tokens); setSeconds(row.timeout_seconds); setBudget(row.max_cost_microusd); };
  const patchCase = (index: number, patch: Partial<TestCase>) => { changed(); setCases(old => old.map((row, i) => i === index ? { ...row, ...patch } : row)); };
  return <div className="experimental-section">
    <Panel title="有界评测与能力证据">
      <p>由你主动开始，每次最多 6 个样本、逐步执行。只调用已启用本地或明确标记的合成 Adapter；安装、读取页面不会运行评测。图片每步通过已登记本地路线生成一张，保留原媒体任务与待审候选。视频仍仅导入证据，尚无对应本地调度授权。</p>
      <StatusMessage>接口成功只代表协议完成。文学质量、tokens/s、显存和冷/热启动没有测量时保持未知；小样本结果不形成模型排行榜。</StatusMessage>
      <ResourceState loading={resource.loading} error={resource.error} />
      {editing && <StatusMessage>编辑「{editing.title}」v{editing.version}；保存后旧版本评测结论会标为历史。</StatusMessage>}
      <Field label="评测任务集标题"><input maxLength={120} value={title} onChange={e => { changed(); setTitle(e.target.value); }} /></Field>
      {cases.map((row, index) => <fieldset className="experimental-record" key={index}><legend>样本 {index + 1}</legend><Field label={`样本 ${index + 1} 标题`}><input maxLength={120} value={row.title} onChange={e => patchCase(index, { title: e.target.value })} /></Field><Field label={`样本 ${index + 1} 类型`}><select value={row.kind} onChange={e => patchCase(index, { kind: e.target.value, ...(e.target.value === 'IMAGE_WORKFLOW' ? { rule: 'NONEMPTY', expected: [] } : {}) })}>{kinds.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field label={`样本 ${index + 1} 合成测试输入`}><textarea maxLength={3000} value={row.prompt} onChange={e => patchCase(index, { prompt: e.target.value })} /></Field><Field label={`样本 ${index + 1} 正确性规则`}><select disabled={row.kind === 'IMAGE_WORKFLOW'} value={row.rule} onChange={e => patchCase(index, { rule: e.target.value })}><option value="NONEMPTY">{row.kind === 'IMAGE_WORKFLOW' ? '图像可解码与尺寸记录（不代表美术质量）' : '非空文本（不代表质量）'}</option><option value="CONTAINS">包含指定文本</option><option value="JSON_KEYS">有效 JSON 对象包含指定键</option></select></Field>{row.rule !== 'NONEMPTY' && <Field label={`样本 ${index + 1} 规则目标（每行一项）`}><textarea value={row.expected.join('\n')} onChange={e => patchCase(index, { expected: e.target.value.split('\n').filter(Boolean) })} /></Field>}{cases.length > 1 && <Button disabled={action.busy} onClick={() => { changed(); setCases(old => old.filter((_, i) => i !== index)); }}>移除样本 {index + 1}</Button>}</fieldset>)}
      <Button disabled={cases.length >= 6 || action.busy} onClick={() => { changed(); setCases(old => [...old, emptyCase()]); }}>增加评测样本</Button>
      <div className="experimental-grid"><Field label="每个样本重复次数"><input type="number" min="1" max="3" value={repetitions} onChange={e => { changed(); setRepetitions(Number(e.target.value)); }} /></Field><Field label="每次最大输出 Token"><input type="number" min="1" max="512" value={output} onChange={e => { changed(); setOutput(Number(e.target.value)); }} /></Field><Field label="每样本取消时限（秒）"><input type="number" min="1" max="120" value={seconds} onChange={e => { changed(); setSeconds(Number(e.target.value)); }} /></Field><Field label="整组费用预占上限（µUSD）"><input type="number" min="0" value={budget} onChange={e => { changed(); setBudget(Number(e.target.value)); }} /></Field></div>
      <p>总样本数 {cases.length * repetitions} / 6。超时会请求取消；同步上游调用可能需要其传输超时才能结束，已经发出的内容和消耗无法撤回。</p>
      <div className="experimental-actions"><Button disabled={action.busy || !title.trim() || cases.some(r => !r.title.trim() || !r.prompt.trim() || (r.rule !== 'NONEMPTY' && !r.expected.length)) || cases.length * repetitions > 6} onClick={() => void action.run(async () => {
        const ticket = inputEpoch.current, value = { title, cases, repetitions, max_output_tokens: output, timeout_seconds: seconds, max_cost_microusd: budget };
        const saved = editing ? await api.updateSet(editing.id, { ...value, expected_version: editing.version }) : await api.createSet(value);
        if (alive.current && ticket === inputEpoch.current) { setSetId(saved.id); reset(); }
      }, '任务集已保存，尚未调用模型。')}>{editing ? '保存任务集新版本' : '保存评测任务集'}</Button>{editing && <Button onClick={reset}>放弃任务集编辑</Button>}<Button disabled={action.busy} onClick={resource.reload}>刷新评测记录（保留输入）</Button></div>{action.feedback}
      {!resource.loading && !resource.error && <div className="experimental-list">{resource.data?.sets.map(row => <article className="experimental-record" key={row.id}><strong>{row.title} · v{row.version}</strong><p>{row.cases.length * row.repetitions} 个有界样本</p><Button onClick={() => edit(row)}>编辑任务集 {row.title}</Button></article>)}</div>}
    </Panel>
    <Panel title="明确选择并运行评测"><Field label="待运行任务集"><select value={setId} onChange={e => { requestId.current = uuid(); setSetId(e.target.value); }}><option value="">请选择已保存任务集</option>{resource.data?.sets.map(r => <option key={r.id} value={r.id}>{r.title} · v{r.version}</option>)}</select></Field><Field label="本次评测的本地模型路线"><select value={routeId} onChange={e => { requestId.current = uuid(); setRouteId(e.target.value); }}><option value="">请选择明确路线</option>{validRoutes.map(r => <option key={r.route_id} value={r.route_id}>{r.display_name}{r.synthetic ? ' · 合成协议测试' : ''}</option>)}</select></Field>{!validRoutes.length && <EmptyState title="没有可执行本地 Adapter" detail="仍可管理任务集、导入外部证据。不会下载模型或改走收费云服务。" />}<Button disabled={!currentSet || !validRoute || action.busy || resource.loading || !!resource.error} onClick={() => void action.run(async () => { await api.startBenchmark(currentSet!, routeId, requestId.current); if (alive.current) requestId.current = uuid(); }, '评测已准备。请明确执行下一样本，不会自动连续运行。')}>建立有界评测运行</Button>
      {!resource.loading && !resource.error && resource.data?.runs.map(row => <BenchmarkRun key={row.id} api={api} run={row} onChange={resource.reload} />)}
    </Panel>
    <Panel title="隐藏模型标签的小样本偏好">
      <p>比较两组由你完成、输入与参数相符的当前结果。隐藏 A/B 模型标签，选择后揭示路线；偏好只记录本次阅读，不换算为质量分或排行榜。</p>
      <div className="experimental-grid">{[['left', '结果组一'], ['right', '结果组二']].map(([key, label]) => <Field key={key} label={label}><select value={key === 'left' ? left : right} onChange={e => { setComparison(undefined); if (key === 'left') setLeft(e.target.value); else setRight(e.target.value); }}><option value="">请选择执行证据</option>{resource.data?.evidence.filter(row => row.origin === 'EXECUTED' && row.evidence_state === 'CURRENT' && (!row.capability || row.capability === 'TEXT')).map(row => <option key={row.id} value={row.id}>{row.created_at} · {row.id.slice(0, 8)}</option>)}</select></Field>)}</div>
      <Button disabled={!left || !right || left === right || action.busy} onClick={() => void action.run(async () => { const value = await api.compareBlind(left, right); if (alive.current) setComparison(value); }, '模型标签已隐藏，请阅读两组原始输出。')}>开始 A/B 隐藏标签比较</Button>
      {resource.data?.comparisons?.map(row => <Button key={row.id} disabled={action.busy} onClick={() => setComparison(row)}>查看偏好记录 {row.created_at} · {row.choice || '待阅读'}</Button>)}
      {comparison && <section className="experimental-section" aria-label="小样本偏好比较"><p>样本数：{comparison.sample_count}；不代表全模型质量。</p><div className="experimental-grid">{comparison.samples.map((sample: { label: string; outputs: string[] }) => <Field key={sample.label} label={`隐藏模型 ${sample.label} 的输出`}><textarea readOnly value={sample.outputs.join('\n\n')} /></Field>)}</div>{comparison.status === 'REVIEW' ? <div className="experimental-actions">{[['A', '偏好 A'], ['B', '偏好 B'], ['TIE', '相当'], ['NEITHER', '都不满意']].map(([choice, label]) => <Button key={choice} disabled={action.busy} onClick={() => void action.run(async () => { const result = await api.voteBlind(comparison, choice); if (alive.current) setComparison(result); }, '本次小样本偏好已保存。')}>{label}</Button>)}</div> : <><StatusMessage>本次偏好：{comparison.choice}。没有写入全局质量分。</StatusMessage><Details value={comparison.reveal} label="揭示本次 A/B 路线" /></>}</section>}
    </Panel>
    <Panel title="模型能力档案与证据分层"><Button onClick={profiles.reload}>刷新能力档案</Button><ResourceState loading={profiles.loading} error={profiles.error} />{!profiles.loading && !profiles.error && profiles.data?.items.map(row => <article key={row.route_id} className="experimental-record"><strong>{row.provider_id} / {row.model_id}</strong><p>{row.evidence_tiers.join(' · ')}{row.synthetic ? ' · 合成协议测试' : ''}</p><p>目录声明、检测、协议测试、本地评测分别记录；用户验证：{row.user_verified ? '已记录' : '未记录'}。未知吞吐、显存、文学质量保持未知。</p><Details value={row} label="档案字段来源与已执行测量" /></article>)}</Panel>
    <Panel title="当前证据与结果导入"><p>导入文件仅作为用户提供的未验证证据保留，不自动授权路线、不执行工作流，也不进入速度或质量调度。模型、运行时、Adapter 或任务集变化会使旧结论失效。</p><Field label="读取评测结果 JSON 文件"><input type="file" accept="application/json,.json" onChange={async e => { const file = e.target.files?.[0], ticket = ++importEpoch.current; setImportError(''); setImportText(''); if (!file) return; if (file.size > 65536) { setImportError('结果文件不得超过 64 KiB。'); return; } try { const text = await file.text(); JSON.parse(text); if (alive.current && ticket === importEpoch.current) setImportText(text); } catch { if (alive.current && ticket === importEpoch.current) setImportError('结果文件不是有效 JSON。'); } }} /></Field><Field label="待导入结果 JSON（核对后提交）"><textarea value={importText} onChange={e => { importEpoch.current++; setImportText(e.target.value); }} /></Field><p>必填：set_id、expected_set_version、route_id、route_fingerprint、input_hash、workflow_hash、model_id、runtime_version、adapter_hash、latency_ms、sample_count、error_count、provenance。哈希使用 SHA-256；不得包含密钥、路径或原稿。</p>{importError && <StatusMessage tone="error">{importError}</StatusMessage>}<Button disabled={!importText.trim() || action.busy} onClick={() => void action.run(async () => { const ticket = importEpoch.current; await api.importEvidence(JSON.parse(importText)); if (alive.current && ticket === importEpoch.current) setImportText(''); }, '导入证据已保存，仍标记为未验证。')}>核对并导入评测证据</Button>
      {!resource.loading && !resource.error && resource.data?.evidence.map(row => <article className="experimental-record" key={row.id}><div className="experimental-actions"><strong>{row.verification}</strong><Badge tone={row.evidence_state === 'CURRENT' ? 'success' : 'warning'}>{row.evidence_state === 'CURRENT' ? '当前版本相符' : '历史 / 待复验'}</Badge></div><p>{row.origin === 'EXECUTED' ? '本机执行' : '导入未验证'} · {row.metrics?.sample_count} 个样本 · 延迟 {row.metrics?.latency_ms} ms · 规则通过 {row.metrics?.rule_pass_count ?? '未提供'}</p><p>文学质量、tokens/s、显存、冷/热启动：未评测。</p>{!!row.invalidation_reasons?.length && <p>{row.invalidation_reasons.join(' · ')}</p>}<Details value={row} label="查看精确指纹、参数与证据范围" /><Button disabled={action.busy || row.status === 'INVALIDATED'} onClick={() => void action.run(async () => { await api.invalidateEvidence(row); profiles.reload(); }, '证据已标记失效，调度器不再使用。')}>使此证据失效</Button>{row.origin === 'EXECUTED' && row.evidence_state === 'CURRENT' && <EvidenceReview api={api} row={row} onSaved={profiles.reload} />}</article>)}
    </Panel>
  </div>;
}
function BenchmarkRun({ api, run, onChange }: { api: BrokerApi; run: Row; onChange: () => void }) {
  const action = useAction(onChange), cancelAction = useAction(onChange);
  return <article className="experimental-record"><strong>运行 {run.id.slice(0, 12)} · {run.status}</strong><progress aria-label="评测完成进度" value={run.completed} max={run.total} /><p>{run.completed} / {run.total} 已完成；每次按钮只执行一个保存的样本。</p><div className="experimental-actions"><Button disabled={action.busy || run.status !== 'READY'} onClick={() => void action.run(() => api.benchmarkAction(run, 'step'), '此样本处理已返回，请核对状态与原始结果。')}>执行下一评测样本</Button><Button disabled={!['READY', 'RUNNING'].includes(run.status || '')} onClick={() => void cancelAction.run(async () => { const latest = await api.benchmarks(); const current = latest.runs.find(r => r.id === run.id); if (current) await api.benchmarkAction(current, 'cancel'); }, '评测已请求取消。')}>取消此评测运行</Button><Button onClick={onChange}>核对运行状态</Button></div>{action.busy && <StatusMessage>正在执行一个本地样本。可取消；不会自动运行下一样本。</StatusMessage>}{action.feedback}{cancelAction.feedback}{run.results?.map((result: Row, index: number) => <details key={index}><summary>{result.case_title} · {result.passed ? '规则通过' : '规则未通过'} · {result.latency_ms} ms</summary>{result.error_code && <p>{result.error_code}</p>}<Field label={`样本 ${index + 1} 输出（不代表文学质量）`}><textarea readOnly value={result.output || ''} /></Field><p>输入摘要：{result.input_hash}</p>{result.media_receipt && <><p>原媒体任务：{result.media_receipt.task_id} · {result.media_receipt.status}。请到封面与分镜生成工作流查看和审核候选。</p><Details value={result.media_receipt} label="图像输出摘要、解码尺寸与待审状态" /></>}</details>)}{run.status === 'RUNNING' && <StatusMessage tone="warning">如果执行器重启，此运行不会自动重发。请核对上游并取消旧运行；未知费用继续保留。</StatusMessage>}</article>;
}

function EvidenceReview({ api, row, onSaved }: { api: BrokerApi; row: Row; onSaved: () => void }) {
  const [note, setNote] = useState(''), [confirmed, setConfirmed] = useState(false);
  const action = useAction(onSaved);
  return <div className="experimental-form"><Field label={`证据 ${row.id.slice(0, 8)} 的核对说明`}><input maxLength={500} value={note} onChange={event => { setNote(event.target.value); setConfirmed(false); }} /></Field><label className="experimental-check"><input type="checkbox" checked={confirmed} onChange={event => setConfirmed(event.target.checked)} />我已检查本次模型身份和保存的原始输出，仅确认本组样本</label><Button disabled={action.busy || !confirmed || !note.trim()} onClick={() => void action.run(async () => { await api.reviewEvidence(row, note); setConfirmed(false); }, '人工核对已绑定这份证据。未生成全局质量评分。')}>记录本次人工验证</Button>{action.feedback}</div>;
}
