import { useEffect, useMemo, useRef, useState } from 'react';
import { Badge, Button, Panel, StatusMessage } from '../ui/primitives';
import type { ExperimentalClient } from './api';
import { Details, Field, ResourceState, useAction, useResource } from './shared';
import { offlineSyncClient, type SyncApi, type SyncCatalog, type SyncChannel, type SyncChoices, type SyncExport, type SyncPlan, type SyncRecovery, type SyncRow } from './offlineSyncClient';
let identity = 0;
const labels: Record<string, string> = { PENDING: '已持久保存，待交换', UNKNOWN: '结果未知，先核对', FAILED: '传输未完成，可手动重取同一消息', ACKNOWLEDGED: '接收回执已核对，尚不代表已应用', PENDING_REVIEW: '收件箱待审阅', APPLIED: '原章节写入已确认', RECONCILED: '人工核对已采用', CLAIMED: '已开始写入，先核对结果', SUPERSEDED: '已被较新完整候选替代', CLOSED_WITHOUT_REPLAY: '已人工关闭，候选和部分结果保留', ACTIVE: '仅手动本地交换', REVOKED: '已撤销后续交换' };
const json = (text: string) => { if (new TextEncoder().encode(text).length > 524288) throw new Error('消息超过大小限制'); return JSON.parse(text); };
function useAlive() { const ref = useRef(true); useEffect(() => { ref.current = true; return () => { ref.current = false; }; }, []); return ref; }
export function OfflineSyncPanel({ client }: { client: ExperimentalClient }) {
  const key = useMemo(() => ++identity, [client]); return <SyncBody key={key} client={client} />;
}
function SyncBody({ client }: { client: ExperimentalClient }) {
  const api = useMemo(() => offlineSyncClient(client), [client]);
  const records = useResource(signal => api.records(signal), [api]), catalog = useResource(signal => api.catalog(signal), [api]);
  const [selected, setSelected] = useState('');
  const reload = () => { records.reload(); catalog.reload(); }; const reloadRef = useRef(reload); reloadRef.current = reload;
  useEffect(() => { const focus = () => reloadRef.current(); window.addEventListener('focus', focus); return () => window.removeEventListener('focus', focus); }, []);
  const blocked = records.loading || !!records.error || catalog.loading || !!catalog.error;
  const channel = records.data?.channels.find(r => r.id === selected);
  return <section className="experimental-pane" aria-label="离线同步与人工交换">
    <Panel title="离线同步基础 · 外部网络关闭"><Badge>无自动联网、后台同步或云账号</Badge><p>先在原编辑器保存本机正文，再将已选章节的保存版本放入持久发件箱。收件箱仅保存候选；核对三方差异后才通过原章节版本检查写入。</p><p>此处提供手动 JSON 交换。配对标签用于防止串项目，不能证明对方身份。没有生产云服务、端到端加密或生产密钥生命周期承诺。</p><p>仅交换明确选定的章节正文，不包含资产、凭据、模型、缓存或路径元数据。包含检测到的本机路径或敏感串时会拒绝交换，不会偷偷改写原稿。</p><p>撤销和删除标记阻止后续交换；已经下载的副本及历史备份无法远程收回。</p><Button disabled={records.loading || catalog.loading} onClick={reload}>刷新本机同步状态与权限</Button><ResourceState loading={records.loading || catalog.loading} error={records.error || catalog.error} /></Panel>
    <div hidden={blocked}>
      {catalog.data && <NewChannel api={api} catalog={catalog.data} blocked={blocked} done={id => { setSelected(id); reload(); }} />}
      <Panel title="已选择的项目同步范围"><p>当前页面只操作当前项目；协作分支正文写入尚不支持，不能把基础章节当成分支内容。</p><ResourceState loading={false} empty={!records.data?.channels.length} />{records.data?.channels.map(row => <article className="experimental-record" key={row.id}><Button disabled={blocked} onClick={() => setSelected(row.id)}>{row.stream_id} · {row.endpoint_id} → {row.peer_id}</Button> <Badge>{labels[row.status]}</Badge><p>发出游标 {row.send_cursor} / 收到游标 {row.receive_cursor} · 范围版本 {row.version}</p></article>)}</Panel>
      {channel && catalog.data && <ChannelWork key={channel.id} api={api} channel={channel} catalog={catalog.data} outbox={records.data?.outbox.filter(r => r.channel_id === channel.id) || []} inbox={records.data?.inbox.filter(r => r.channel_id === channel.id) || []} blocked={blocked} reload={reload} />}
    </div>
  </section>;
}
function NewChannel({ api, catalog, blocked, done }: { api: SyncApi; catalog: SyncCatalog; blocked: boolean; done: (id: string) => void }) {
  const [stream, setStream] = useState(''), [endpoint, setEndpoint] = useState(''), [peer, setPeer] = useState(''), [selected, setSelected] = useState<string[]>([]), [allowNew, setAllowNew] = useState(false);
  const action = useAction(), alive = useAlive();
  return <Panel title="明确选择手动交换范围"><p>在两端填写相同的交换批次标签，并将本端／对端标签互换。每个批次固定初始基线；不要复用已撤销批次。先保存正文后再建立范围。</p><div className="experimental-grid"><Field label="交换批次标签"><input value={stream} maxLength={120} onChange={e => setStream(e.target.value)} /></Field><Field label="本端标签"><input value={endpoint} maxLength={120} onChange={e => setEndpoint(e.target.value)} /></Field><Field label="对端标签"><input value={peer} maxLength={120} onChange={e => setPeer(e.target.value)} /></Field></div><p>标签使用字母、数字、点、下划线、冒号或短横线；不要填写密钥或网址。</p>
    <fieldset disabled={blocked || action.busy}><legend>只选择需要交换的章节，默认全部不选</legend>{catalog.chapters.map(c => <label className="experimental-check" key={c.id}><input type="checkbox" checked={selected.includes(c.id)} onChange={e => setSelected(e.target.checked ? [...selected, c.id] : selected.filter(id => id !== c.id))} />同步范围：{c.title} · v{c.version}</label>)}<label className="experimental-check"><input type="checkbox" checked={allowNew} onChange={e => setAllowNew(e.target.checked)} />允许将收到的章节候选审阅后新增到当前项目</label></fieldset>
    {catalog.truncated && <StatusMessage tone="warning">只显示前 100 章。未显示内容不会加入范围。</StatusMessage>}<Button disabled={blocked || action.busy || !stream || !endpoint || !peer || endpoint === peer || (!selected.length && !allowNew) || selected.length > 20} onClick={() => void action.run(async () => { const row = await api.open({ stream_id: stream, endpoint_id: endpoint, peer_id: peer, chapter_ids: selected, allow_new_chapters: allowNew }); if (alive.current) done(row.id); }, '选定范围已保存，未发送任何内容。')}>保存选定交换范围</Button>{action.feedback}</Panel>;
}
function ChannelWork({ api, channel, catalog, outbox, inbox, blocked, reload }: { api: SyncApi; channel: SyncChannel; catalog: SyncCatalog; outbox: SyncRow[]; inbox: SyncRow[]; blocked: boolean; reload: () => void }) {
  const [cid, setCid] = useState(''), [tombstone, setTombstone] = useState(false), [revokeAck, setRevokeAck] = useState(false); const action = useAction();
  const request = useRef<{ key: string; id: string }>(); const alive = useAlive();
  if (channel.status !== 'ACTIVE') return <Panel title="已撤销的交换范围"><p>后续导出、接收和应用已停止。原稿与已有副本保留，不作物理抹除承诺。</p></Panel>;
  return <>
    <Panel title="把本机已保存版本放入发件箱"><p>即使对端断连，此步骤仍只写本机持久存储，不会覆盖任何对端内容。文本仍从原编辑器保存；这里不保存尚未落盘的输入。</p><Field label="加入发件箱的已选章节"><select disabled={blocked || action.busy} value={cid} onChange={e => setCid(e.target.value)}><option value="">选择当前范围章节</option>{channel.chapter_ids.map(id => <option value={id} key={id}>{catalog.chapters.find(c => c.id === id)?.title || id + '（已归档或需刷新）'}</option>)}</select></Field><label className="experimental-check"><input type="checkbox" checked={tombstone} onChange={e => setTombstone(e.target.checked)} />发送删除标记，必须已在原编辑器归档该章</label><Button disabled={blocked || action.busy || !cid} onClick={() => void action.run(async () => { const key = JSON.stringify([channel.id, cid, tombstone]); if (request.current?.key !== key) request.current = { key, id: crypto.randomUUID() }; try { await api.queue(channel, cid, request.current.id, tombstone); if (alive.current) request.current = undefined; } finally { if (alive.current) reload(); } }, '当前保存版本已进入持久发件箱，尚未交换。')}>保存到本机发件箱</Button>{action.feedback}</Panel>
    <Panel title="持久发件箱"><ResourceState loading={false} empty={!outbox.length} />{outbox.map(row => <Outbox key={row.id} api={api} row={row} blocked={blocked} reload={reload} />)}</Panel>
    <Receive api={api} channel={channel} catalog={catalog} blocked={blocked} reload={reload} />
    <Panel title="持久收件箱与差异审阅"><ResourceState loading={false} empty={!inbox.length} />{inbox.map(row => <Inbox key={row.id} api={api} row={row} blocked={blocked} reload={reload} />)}</Panel>
    <Panel title="撤销后续交换"><label className="experimental-check"><input type="checkbox" checked={revokeAck} onChange={e => setRevokeAck(e.target.checked)} />停止此范围后续交换，已有下载和备份仍可能存在</label><Button disabled={blocked || action.busy || !revokeAck} onClick={() => void action.run(async () => { try { await api.revoke(channel); } finally { if (alive.current) reload(); } }, '该范围已撤销。')}>撤销此交换范围</Button></Panel>
  </>;
}
function Outbox({ api, row, blocked, reload }: { api: SyncApi; row: SyncRow; blocked: boolean; reload: () => void }) {
  const [preview, setPreview] = useState<SyncExport>(), [ack, setAck] = useState(false), [receipt, setReceipt] = useState(''), [download, setDownload] = useState('');
  const action = useAction(), alive = useAlive(), url = useRef<string>();
  useEffect(() => () => { if (url.current) URL.revokeObjectURL(url.current); }, []);
  const deliver = (state: 'FAILED' | 'UNKNOWN' | 'ACKNOWLEDGED') => action.run(async () => { try { await api.delivery(row, state, state === 'ACKNOWLEDGED' ? json(receipt) : undefined); } finally { if (alive.current) reload(); } }, '已记录交换结果，不会自动重试写入。');
  return <article className="experimental-record"><Badge>{labels[row.status]} · #{row.sequence} · v{row.version}</Badge><p>消息 {row.id} · 原章节版本 {row.source_version} · {row.operation}</p><Button disabled={blocked || action.busy} onClick={() => void action.run(async () => { const value = await api.inspect(row); if (alive.current) { setPreview(value); setAck(false); } }, '已重新检查当前来源和导出范围。')}>预览此消息内容</Button>
    {preview && <><Details label="版本化同步信封，只含所选章节" value={preview.envelope} /><label className="experimental-check"><input type="checkbox" checked={ack} onChange={e => setAck(e.target.checked)} />我了解导出的本地副本无法远程撤回</label><Button disabled={blocked || action.busy || !ack || row.status === 'ACKNOWLEDGED' || (row.attempts || 0) >= 8} onClick={() => void action.run(async () => { const value = await api.export(row); if (alive.current) { setPreview(value); if (url.current) URL.revokeObjectURL(url.current); url.current = URL.createObjectURL(new Blob([JSON.stringify(value.envelope, null, 2)], { type: 'application/json' })); setDownload(url.current); reload(); } }, '手动交换文件已准备，接收结果尚未知。')}>生成手动交换文件</Button></>}
    {download && <a href={download} download={'novel-sync-' + row.sequence + '.json'}>下载本地同步消息</a>}
    {!!row.attempts && row.status !== 'ACKNOWLEDGED' && <><Field label={`接收回执 ${row.id}`}><textarea value={receipt} maxLength={4096} onChange={e => setReceipt(e.target.value)} /></Field><div className="experimental-actions"><Button disabled={blocked || action.busy || !receipt} onClick={() => void deliver('ACKNOWLEDGED')}>核对接收回执</Button><Button disabled={blocked || action.busy} onClick={() => void deliver('FAILED')}>记录传输未完成</Button><Button disabled={blocked || action.busy} onClick={() => void deliver('UNKNOWN')}>保留结果未知</Button></div><p>重取文件使用同一消息 ID，接收端去重。当前正文已变更时，旧文件不再导出；请把最新保存版本重新加入发件箱。</p></>}{action.feedback}</article>;
}
function Receive({ api, channel, catalog, blocked, reload }: { api: SyncApi; channel: SyncChannel; catalog: SyncCatalog; blocked: boolean; reload: () => void }) {
  const [text, setText] = useState(''), [preview, setPreview] = useState<unknown>(), [target, setTarget] = useState(''), [receipt, setReceipt] = useState<unknown>(); const action = useAction(), alive = useAlive();
  const invalidated = () => { setPreview(undefined); setReceipt(undefined); };
  return <Panel title="手动接收候选，不自动覆盖"><p>从本地交换文件复制 JSON。先核对源标签和正文，再选择已批准范围内的目标；批次、来源、版本和重放游标由后端重新检查。</p><Field label="收到的同步消息 JSON"><textarea value={text} maxLength={524288} onChange={e => { setText(e.target.value); invalidated(); }} /></Field><Field label="收到章节的本机目标"><select value={target} onChange={e => { setTarget(e.target.value); invalidated(); }}><option value="">选择目标章节</option>{channel.allow_new_chapters && <option value="__NEW__">审阅后新增独立章节</option>}{channel.chapter_ids.map(id => <option key={id} value={id}>{catalog.chapters.find(c => c.id === id)?.title || id}</option>)}</select></Field><Button disabled={blocked || action.busy || !text || !target} onClick={() => void action.run(async () => { setPreview(json(text)); }, '已预览输入，尚未接收或写入正文。')}>预览待接收消息</Button>
    {!!preview && <><Details value={preview} label="待接收信封预览" /><Button disabled={blocked || action.busy} onClick={() => void action.run(async () => { try { const result = await api.receive(channel, preview, target === '__NEW__' ? '' : target, target === '__NEW__'); if (alive.current) setReceipt(result.receipt); } finally { if (alive.current) reload(); } }, '候选已保存至本机收件箱，正文尚未修改。')}>接收到待审核收件箱</Button></>}
    {!!receipt && <Field label="可复制给发送端的接收回执"><textarea readOnly value={JSON.stringify(receipt, null, 2)} /></Field>}{action.feedback}</Panel>;
}
function Inbox({ api, row, blocked, reload }: { api: SyncApi; row: SyncRow; blocked: boolean; reload: () => void }) {
  const [plan, setPlan] = useState<SyncPlan>(), [choices, setChoices] = useState<SyncChoices>({}), [ack, setAck] = useState(false), [recovery, setRecovery] = useState<SyncRecovery>();
  const action = useAction(), alive = useAlive();
  useEffect(() => { setPlan(undefined); setRecovery(undefined); setAck(false); }, [row.version]);
  return <article className="experimental-record"><Badge>{labels[row.status]} · #{row.sequence} · v{row.version}</Badge><p>消息 {row.id} · {row.target_chapter_id || '待审阅新增章节'} · {row.operation}</p>
    {row.status === 'PENDING_REVIEW' && <><Button disabled={blocked || action.busy} onClick={() => void action.run(async () => { const result = await api.review(row, choices); if (alive.current) { setPlan(result); setAck(false); } }, '已读取当前本机、初始基线和收到的候选。')}>读取当前三方差异</Button><Button disabled={blocked || action.busy} onClick={() => void action.run(async () => { setChoices({}); setPlan(undefined); setAck(false); const result = await api.review(row, {}); if (alive.current) setPlan(result); }, '已丢弃旧选择并读取最新差异，尚未应用。')}>清除旧选择并重新读取</Button>
      {plan && <><Details value={{ base: plan.base, local: plan.current, incoming: plan.incoming }} label="完整候选与当前版本" />{plan.segments.map((segment, index) => <div className="experimental-record" key={segment.id || index}><Badge>{segment.kind}</Badge><Details value={segment} label={'差异 ' + (index + 1)} />{segment.kind === 'CONFLICT' && segment.id && <Field label={'冲突选择 ' + (index + 1)}><select value={choices[segment.id] || ''} disabled={blocked || action.busy} onChange={e => { const selected = e.target.value as 'LOCAL' | 'INCOMING'; setChoices({ ...choices, [segment.id!]: selected }); setAck(false); setPlan({ ...plan, can_apply: false }); }}><option value="" disabled>必须明确选择</option><option value="LOCAL">保留本机候选</option><option value="INCOMING">采用收到的候选</option></select></Field>}</div>)}{!plan.can_apply && <StatusMessage tone="warning">还有未核对的冲突或限制。作出选择后重新读取三方差异以确认最终版本。{plan.blocked.join(' / ')}</StatusMessage>}
        <label className="experimental-check"><input type="checkbox" checked={ack} disabled={!plan.can_apply} onChange={e => setAck(e.target.checked)} />已核对差异，允许通过原章节权限与版本检查应用</label><Button disabled={blocked || action.busy || !plan.can_apply || !ack} onClick={() => void action.run(async () => { try { await api.apply(row, plan); } finally { if (alive.current) { setPlan(undefined); setAck(false); reload(); } } }, '已通过原章节服务应用并保留历史。')}>应用已核对的候选</Button></>}
    </>}
    {['UNKNOWN', 'CLAIMED'].includes(row.status) && <><p>可能已写入，禁止自动重试。读取原章节检查点与当前结果；部分新增章节会保留，可在原编辑器核对。</p><Button disabled={blocked || action.busy} onClick={() => void action.run(async () => { const result = await api.recovery(row); if (alive.current) setRecovery(result); }, '已读取原章节实际状态。')}>核对未知写入结果</Button>{recovery && <><Details value={recovery} label="恢复观察，不自动重放" /><Button disabled={blocked || action.busy || !recovery.can_adopt} onClick={() => void action.run(async () => { try { await api.recovery(row, recovery); } finally { if (alive.current) reload(); } }, '完全匹配的已有结果已由人工确认，不重复写入。')}>确认采用完全匹配的已有结果</Button><Button disabled={blocked || action.busy} onClick={() => void action.run(async () => { try { await api.recovery(row, recovery, true); } finally { if (alive.current) reload(); } }, '该未知记录已人工关闭。原稿、候选和部分新增结果仍保留，未重试写入。')}>保留所有候选并关闭此未知记录</Button></>}</>}{action.feedback}</article>;
}
