import { useLayoutEffect, useRef, useState } from 'react';
import { Badge, Button, EmptyState, Panel, StatusMessage } from '../ui/primitives';
import { ErrorMessage, Field } from './shared';
import { useReviewAction } from './styleReviewClient';
import type { ComparisonModelCatalog, VersionComparison, revisionIntelligenceClient } from './revisionIntelligenceClient';
type Props = {api: ReturnType<typeof revisionIntelligenceClient>; row: VersionComparison; onChanged: (row: VersionComparison) => void};
export function RevisionComparisonModelPanel({api, row, onChanged}: Props) {
  const [catalog, setCatalog] = useState<ComparisonModelCatalog>(), [routeId, setRouteId] = useState(row.model_preview?.broker.chosen?.route_id || '');
  const [consent, setConsent] = useState(false), [hidden, setHidden] = useState(false);
  const action = useReviewAction(), epoch = useRef(0);
  useLayoutEffect(() => { setConsent(false); }, [row.version, row.model_preview?.preview_digest]);
  const preview = !row.stale && !hidden ? row.model_preview : undefined;
  const execution = row.model_execution;
  const change = (operation: () => Promise<VersionComparison>) => action.run(async current => {
    const ticket = ++epoch.current; setConsent(false);
    const result = await operation();
    if (current() && ticket === epoch.current) { setHidden(false); onChanged(result); }
  });
  return <Panel title="可选的本地版本语义意见"><section aria-label="已注册版本比较模型">
    <p>复用原模型中心、预算和 Generation Job。只发送这次原版本 A / B 的准确文本，自动上下文、当前正文尾部、Canon、风格、规划与导入意见均排除。LOCAL_ONLY，已知零费用；不会自动继续任务。</p>
    {!execution && <><Button disabled={action.busy || row.stale || row.status !== 'REVIEW'} onClick={() => void action.run(async current => {const ticket = ++epoch.current; const value = await api.comparisonModelCatalog(); if (current() && ticket === epoch.current) setCatalog(value);})}>查看已注册版本比较模型</Button>
    {catalog && <><Field label="本地版本比较模型"><select value={routeId} disabled={action.busy} onChange={e => {epoch.current++; setRouteId(e.target.value); setConsent(false); setHidden(true);}}><option value="">选择已注册本地路线</option>{catalog.routes.map(route => <option key={route.route_id} value={route.route_id} disabled={!route.available}>{route.display_name} · {route.provider_id}/{route.model_id}{route.synthetic ? ' · 合成协议测试' : ''}</option>)}</select></Field>{!catalog.routes.length && <EmptyState title="没有已注册本地文本模型" detail="请在原模型中心完成配置；这里不会安装模型或改用云端。" />}{catalog.routes.filter(route => !route.available).map(route => <StatusMessage key={route.route_id} tone="warning">{route.model_id}：{route.reasons.join('；')}</StatusMessage>)}<Button disabled={action.busy || row.stale || !routeId || !catalog.routes.some(route => route.route_id === routeId && route.available)} onClick={() => void change(() => api.comparisonModelPreview(row, routeId))}>准备准确版本模型预览</Button></>}
    </>}
    {preview && <section aria-label="准确版本模型预览"><Badge>{preview.quality_verification === 'SYNTHETIC_PROTOCOL_ONLY' ? '合成协议测试，非真实语义判断' : 'Model-derived · 文学质量 NOT_RUN'}</Badge><p>输入不截断；输出最多 {preview.max_output_bytes} 字节，截止 {preview.timeout_seconds} 秒。Token 数未知。</p><Field label="准确版本模型请求"><textarea readOnly rows={10} value={JSON.stringify(preview.request, null, 2)} /></Field><Field label="原版本模型身份与费用凭据"><textarea readOnly rows={5} value={JSON.stringify({sources: preview.sources, broker: preview.broker, budget: preview.budget}, null, 2)} /></Field>{!preview.execution_available && <StatusMessage tone="warning">路线、价格或预算不允许执行。不会自动更换模型或忽略预览。</StatusMessage>}{!execution && <><label className="experimental-check"><input type="checkbox" checked={consent} disabled={action.busy || !preview.execution_available} onChange={e => setConsent(e.target.checked)} />已核对原版本全文、模型身份与零费用预占</label><Button disabled={action.busy || row.stale || !consent || !preview.execution_available} onClick={() => void change(() => api.comparisonModelDispatch(row))}>明确发送此次本地版本比较</Button></>}</section>}
    {execution && <section aria-label="原版本模型任务"><p>原任务 {execution.job_id} · {execution.status} · {execution.receipt_state}</p><p>{execution.model_called ? '已有适配器调度，已发送的数据不能撤回。' : '尚未确认适配器调度。'} 用量：{execution.usage_state}</p>{execution.failure_code && <StatusMessage tone="warning">{execution.failure_code}；无效输出不会成为语义解释。</StatusMessage>}{execution.receipt_state === 'UNKNOWN_NO_AUTOMATIC_REPLAY' && <StatusMessage tone="warning">任务或结算状态未知；仅核对原任务，不自动重发或释放未知预占。</StatusMessage>}{!!execution.accounting && <Field label="版本比较原任务结算"><textarea readOnly value={JSON.stringify(execution.accounting, null, 2)} /></Field>}<div className="experimental-actions"><Button disabled={action.busy || row.stale || row.status !== 'REVIEW'} onClick={() => void change(() => api.comparisonModelRefresh(row))}>核对原版本模型任务</Button><Button disabled={action.busy || ['COMPLETED', 'FAILED', 'CANCELLED'].includes(execution.status)} onClick={() => void change(() => api.comparisonModelCancel(row))}>取消原版本模型任务</Button></div></section>}
    {(row.model_assessments || []).map(opinion => <article className="experimental-record" key={opinion.id}><Badge>Model-derived · 实际原模型任务</Badge><p>{opinion.model.provider_id}/{opinion.model.model_id} · {opinion.model.synthetic ? '合成协议测试' : '真实质量未验收'} · {opinion.decision}</p><p>{opinion.kind}：{opinion.explanation}</p><p>原版本 A v{opinion.before_version} 字符 {opinion.before_start}：{opinion.before_quote || '无'}</p><p>原版本 B v{opinion.after_version} 字符 {opinion.after_start}：{opinion.after_quote || '无'}</p><p>仅验证引文与位置；判断不等于作品事实，不会修改正文或 Canon。</p><div className="experimental-actions"><Button disabled={action.busy || row.stale || row.status !== 'REVIEW' || opinion.decision === 'ACCEPTED_INTERPRETATION'} onClick={() => void change(() => api.comparisonModelReview(row, opinion.id, 'accept'))}>接受为解读（不改稿）</Button><Button disabled={action.busy || row.stale || row.status !== 'REVIEW' || opinion.decision === 'IGNORED'} onClick={() => void change(() => api.comparisonModelReview(row, opinion.id, 'ignore'))}>忽略此模型解读</Button>{opinion.decision !== 'PENDING' && <Button disabled={action.busy || row.stale || row.status !== 'REVIEW'} onClick={() => void change(() => api.comparisonModelReview(row, opinion.id, 'reopen'))}>重开此模型解读</Button>}</div></article>)}
    {execution?.status === 'COMPLETED' && !row.stale && !row.model_assessments?.length && <StatusMessage>原任务已结束，没有可通过证据验证的模型意见。不会补造解释。</StatusMessage>}
    {!!action.error && <ErrorMessage error={action.error} />}
  </section></Panel>;
}
