import type { ExperimentalClient } from './api';
export type BatchInput = { kind: 'PROOF' | 'EXPORT' | 'SYNTHETIC_MEDIA' | 'REGISTERED_MEDIA' | 'VOICE_REDO'; chapter_ids?: string[]; start?: number; end?: number | null; format?: string; brief_id?: string; expected_brief_version?: number; adapter_id?: string; broker_preview_id?: string; expected_broker_version?: number; voice_job_id?: string; expected_voice_digest?: string };
export type BatchProposal = { id: string; version: number; status: string; asset_id?: string; media: { width?: number; height?: number }; verification: string };
export type BatchVoiceResult = { job_id: string; asset_id: string; asset_version: number; approval_status: string; duration_ms: number; media_type: string; verification: string };
export type BatchRecord = { id: string; version: number; status: string; snapshot_digest: string; confirmed?: boolean; approvals?: { actor: string; approved_version: number; snapshot_digest: string; budget_microusd: number; at: string }[]; preset?: { id: string; version: number; package_id: string } | null; stale?: boolean; retained_receipts?: { index: number; status: string; attempts: number; receipts: Record<string, unknown>[] }[]; concurrency?: number; budget?: { state: string; known_cost_microusd: number }; items?: { index: number; kind: string; status: string; attempts: number; chapter_ids: string[]; source_versions_digest: string; source_versions?: Record<string, number>; configuration_summary?: Record<string, unknown>; known_cost_microusd: number; cost_state?: string; resource_requirements?: Record<string, unknown>[]; voice_result?: BatchVoiceResult; permission: string; error_code?: string; download_available?: boolean; format?: string; findings?: { id: string; quote: string; explanation: string; chapter_id: string; offset: number }[]; proposals?: BatchProposal[]; satisfied_asset_ids?: string[]; receipts?: { attempt: number; status: string; task_id?: string; reservation_id?: string; cost_state?: string; approval_version?: number; snapshot_digest?: string }[] }[] };
export type BatchCatalog = { chapters: { id: string; title: string; version: number }[]; briefs: { id: string; title: string; version: number; kind: string }[]; presets?: { id: string; version: number; title: string; content: { proof: boolean; export_format: string | null; skip_satisfied: boolean } }[]; broker_previews?: { id: string; version: number; adapter_id?: string; audio_provider_id?: string; model_id: string; capability: string; source_ids: string[]; cost_state: string }[]; voice_jobs?: { id: string; chapter_id: string; segment_id: string; provider_id: string; model_id: string; request_digest: string; status: string; approval_status: string }[]; formats: string[]; unsupported: string[]; concurrency: number; known_cost_microusd: number };
const key = encodeURIComponent;
export function safeBatchesClient(client: ExperimentalClient) {
  return {
    catalog: (signal?: AbortSignal) => client.get<BatchCatalog>('/safe-batches/catalog', signal),
    list: (signal?: AbortSignal) => client.get<{ items: BatchRecord[] }>('/safe-batches', signal),
    preflight: (items: BatchInput[], skip_satisfied: boolean, preset?: { id: string; version: number }) => client.post<BatchRecord>('/safe-batches/preflight', { items, skip_satisfied, concurrency: 1, budget_microusd: 0, ...(preset ? { preset_id: preset.id, expected_preset_version: preset.version } : {}) }),
    confirm: (row: BatchRecord) => client.post<BatchRecord>(`/safe-batches/${key(row.id)}/confirm`, { expected_version: row.version, snapshot_digest: row.snapshot_digest, budget_microusd: 0, confirmed: true }),
    dispatch: (row: BatchRecord) => client.post<BatchRecord>(`/safe-batches/${key(row.id)}/dispatch-next`, { expected_version: row.version }),
    stop: (row: BatchRecord) => client.post<BatchRecord>(`/safe-batches/${key(row.id)}/stop`, { expected_version: row.version }),
    retry: (row: BatchRecord) => client.post<BatchRecord>(`/safe-batches/${key(row.id)}/retry-failed`, { expected_version: row.version }),
    reconcile: (row: BatchRecord) => client.post<BatchRecord>(`/safe-batches/${key(row.id)}/reconcile`, { expected_version: row.version }),
    download: (row: BatchRecord, index: number) => client.blob(`/safe-batches/${key(row.id)}/items/${index}/file`),
    voicePreview: (row: BatchRecord, index: number) => client.blob(`/safe-batches/${key(row.id)}/items/${index}/audio`),
    approveVoice: (row: BatchRecord, index: number, assetVersion: number) => client.post<BatchRecord>(`/safe-batches/${key(row.id)}/approve-voice`, { expected_version: row.version, snapshot_digest: row.snapshot_digest, confirmed: true, budget_microusd: 0, item_index: index, expected_asset_version: assetVersion }),
    preview: (row: BatchRecord, proposal: BatchProposal) => client.blob(`/safe-batches/${key(row.id)}/proposals/${key(proposal.id)}/preview`),
    approve: (row: BatchRecord, proposal: BatchProposal) => client.post<BatchRecord>(`/safe-batches/${key(row.id)}/approve-media`, { expected_version: row.version, snapshot_digest: row.snapshot_digest, confirmed: true, budget_microusd: 0, proposal_id: proposal.id, proposal_version: proposal.version }),
  };
}
