import { useEffect, useMemo, useRef, useState } from 'react';
import { Badge, Button, Panel, StatusMessage } from '../ui/primitives';
import type { ExperimentalClient } from './api';
import { Details, ErrorMessage, Field, ResourceState, useResource } from './shared';
import { useReviewAction } from './styleReviewClient';
import { sharedUniverseClient, type UniverseSnapshot, type UniversePinPreview, type UniverseRole, type UniverseSnapshotInput, type UniverseSnapshotPreview } from './sharedUniverseClient';
const roles: Record<UniverseRole, string> = { MAIN_NOVEL: '主作品', SEQUEL: '续作', PREQUEL: '前传', SIDE_STORY: '外传' };
const labels: Record<string, string> = { characters: '人物', locations: '地点', relationships: '关系', organization: '组织', rule: '规则', timeline: '时间线', geography: '地理' };
export function SharedUniversePanel({ client }: { client: ExperimentalClient }) {
  const api = useMemo(() => sharedUniverseClient(client), [client]); const action = useReviewAction();
  const catalog = useResource(signal => api.catalog(signal), [api]); const snapshots = useResource(signal => api.snapshots(signal), [api]); const pins = useResource(signal => api.pins(signal), [api]);
  const incoming = useResource(signal => api.incoming(signal), [api]); const [incomingView, setIncomingView] = useState<UniverseSnapshot>();
  const incomingEpoch = useRef(0);
  useEffect(() => { if (incoming.loading || incoming.error) { incomingEpoch.current++; setIncomingView(undefined); } }, [incoming.loading, incoming.error]);
  const [key, setKey] = useState(''), [title, setTitle] = useState(''), [license, setLicense] = useState(''), [selected, setSelected] = useState<string[]>([]), [permission, setPermission] = useState(false);
  const [snapshotPreview, setSnapshotPreview] = useState<{ input: UniverseSnapshotInput; result: UniverseSnapshotPreview; requestId: string }>();
  const [snapshotId, setSnapshotId] = useState(''), [targetId, setTargetId] = useState(''), [role, setRole] = useState<UniverseRole>('SEQUEL'), [pinPreview, setPinPreview] = useState<UniversePinPreview>(), [confirmed, setConfirmed] = useState(false);
  const rows = catalog.data?.records || []; const chosen = rows.filter(r => selected.includes(r.key));
  const missing = [...new Set(chosen.flatMap(r => r.references.filter(k => !selected.includes(k))))];
  const selectedSnapshot = snapshots.data?.items.find(s => s.id === snapshotId && !s.content_withheld);
  const currentPin = pins.data?.items.find(p => !p.content_withheld && p.universe_key === selectedSnapshot?.universe_key && p.target_project_id === targetId);
  const invalidate = () => { setSnapshotPreview(undefined); setPermission(false); };
  const refresh = () => { incomingEpoch.current++; setIncomingView(undefined); incoming.reload(); catalog.reload(); snapshots.reload(); pins.reload(); setSnapshotPreview(undefined); setPinPreview(undefined); setConfirmed(false); };
  const ready = !catalog.loading && !catalog.error && !snapshots.loading && !snapshots.error && !pins.loading && !pins.error;
  return <section className="experimental-section" aria-label="Shared Universe 版本固定">
    <Panel title="本作品固定的外部世界观引用"><p>读取来源项目的原始不可变快照。不会将引用自动写入本作品 Canon 或模型上下文。</p><ResourceState loading={incoming.loading} error={incoming.error} empty={!incoming.data?.items.length} />
      {!incoming.loading && !incoming.error && incoming.data?.items.map(pin => <article className="experimental-record" key={`${pin.source_project_id}:${pin.pin_id}`}><strong>{pin.source_project_title} · {pin.universe_key}</strong><p>{roles[pin.role]} · 快照 v{pin.snapshot_revision} · 引用 v{pin.pin_version}</p><Button disabled={action.busy} onClick={() => void action.run(async current => { const ticket = ++incomingEpoch.current; setIncomingView(undefined); const result = await api.readIncoming(pin); if (current() && ticket === incomingEpoch.current) setIncomingView(result.snapshot); })}>查看此作品固定的原世界观</Button></article>)}
      {incoming.data?.truncated && !incoming.error && <StatusMessage tone="warning">仅检查前 100 个项目并显示最多 30 个授权引用；列表可能不完整。</StatusMessage>}
      {incomingView && !incoming.loading && !incoming.error && <Details label="本作品当前固定世界观内容" value={incomingView.records} open />}
    </Panel>
    <Panel title="系列作品与世界观快照"><p>从当前项目原人物、地点及已批准的世界记录建立只读快照。为主作品、续作、前传或外传明确固定一个快照版本。原资料更新不会改写快照、其他作品正文或 Canon。</p>
      <StatusMessage>需要项目分叉与世界人物引擎同时启用。本机作者范围可用；不代表跨用户实时协作。来源被隐藏、删除、归档或隐私改变时会停止显示旧快照。</StatusMessage>
      <Button disabled={action.busy} onClick={refresh}>刷新世界观快照与固定版本</Button><ResourceState loading={catalog.loading} error={catalog.error} empty={ready && !rows.length} />
      <div className="experimental-grid"><Field label="Universe 标识"><input value={key} maxLength={80} disabled={action.busy} onChange={e => { setKey(e.target.value); invalidate(); }} /></Field><Field label="世界观快照名称"><input value={title} maxLength={160} disabled={action.busy} onChange={e => { setTitle(e.target.value); invalidate(); }} /></Field></div>
      {ready && rows.map(row => <label className="experimental-check" key={row.key}><input type="checkbox" checked={selected.includes(row.key)} disabled={action.busy || !selected.includes(row.key) && selected.length >= 60} onChange={e => { setSelected(old => e.target.checked ? [...old, row.key] : old.filter(k => k !== row.key)); invalidate(); }} />{labels[row.kind] || row.kind}：{row.title}{row.version ? ` · v${row.version}` : ''}</label>)}
      {ready && !!missing.length && <StatusMessage tone="warning">请一并选择引用资料：{missing.join('、')}</StatusMessage>}
      <Field label="世界观本地复制许可"><input value={license} maxLength={240} disabled={action.busy} onChange={e => { setLicense(e.target.value); invalidate(); }} /></Field>
      <label className="experimental-check"><input type="checkbox" checked={permission} disabled={action.busy} onChange={e => { setPermission(e.target.checked); setSnapshotPreview(undefined); }} />我有权为这些作品保留所选资料的本地只读快照</label>
      <Button disabled={!ready || action.busy || !permission || !key.trim() || !title.trim() || !license.trim() || !chosen.length || !!missing.length} onClick={() => void action.run(async current => { const input: UniverseSnapshotInput = { universe_key: key, title, license, allow_local_copy: true, records: chosen.map(r => ({ key: r.key, source_digest: r.source_digest })) }; const result = await api.previewSnapshot(input); if (current()) setSnapshotPreview({ input, result, requestId: crypto.randomUUID() }); })}>预览不可变世界观快照</Button>
      {snapshotPreview && <><Details label="世界观快照来源版本" value={snapshotPreview.result.source_records} open /><p>将冻结 {snapshotPreview.result.record_count} 条所选资料。不会自动为作品更新固定版本。</p><Button disabled={action.busy || !ready} onClick={() => void action.run(async current => { await api.createSnapshot(snapshotPreview.input, snapshotPreview.result, snapshotPreview.requestId); if (current()) refresh(); }, '不可变快照已保存。下一步为作品明确固定该版本。')}>确认创建只读世界观快照</Button><Button disabled={action.busy} onClick={() => setSnapshotPreview(undefined)}>取消快照预览</Button></>}
    </Panel>
    <Panel title="查看原始快照与来源变化"><ResourceState loading={snapshots.loading} error={snapshots.error} empty={ready && !snapshots.data?.items.length} />{ready && snapshots.data?.items.map(snapshot => <article className="experimental-record" key={snapshot.id}><Badge>快照 v{snapshot.snapshot_revision}</Badge>{snapshot.content_withheld ? <StatusMessage tone="warning">来源权限或隐私不可用，快照内容已停止显示。</StatusMessage> : <><strong>{snapshot.title} · {snapshot.universe_key}</strong>{!!snapshot.source_changes.length && <StatusMessage tone="warning">原资料已变化；当前仍是固定快照。重新选择来源并建立新快照后，才可明确更新作品引用。</StatusMessage>}<Details label={`快照 v${snapshot.snapshot_revision} 的不可变内容`} value={snapshot.records} /><p>摘要：{snapshot.snapshot_digest}</p></>}</article>)}</Panel>
    <Panel title="为作品固定或更新世界观版本"><ResourceState loading={pins.loading} error={pins.error} />
      <div className="experimental-grid"><Field label="要固定的世界观快照"><select value={snapshotId} disabled={action.busy || !ready} onChange={e => { setSnapshotId(e.target.value); setPinPreview(undefined); setConfirmed(false); }}><option value="">选择快照</option>{ready && snapshots.data?.items.filter(s => !s.content_withheld).map(s => <option key={s.id} value={s.id}>{s.title} · {s.universe_key} · v{s.snapshot_revision}</option>)}</select></Field><Field label="系列作品"><select value={targetId} disabled={action.busy || !ready} onChange={e => { setTargetId(e.target.value); setPinPreview(undefined); setConfirmed(false); }}><option value="">选择可访问作品</option>{ready && catalog.data?.projects.map(p => <option key={p.id} value={p.id}>{p.title}</option>)}</select></Field><Field label="作品关系"><select value={role} disabled={action.busy} onChange={e => { setRole(e.target.value as UniverseRole); setPinPreview(undefined); setConfirmed(false); }}>{Object.entries(roles).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field></div>
      <Button disabled={!ready || action.busy || !selectedSnapshot || !targetId} onClick={() => void action.run(async current => { const result = await api.previewPin({ snapshot_id: snapshotId, target_project_id: targetId, role, expected_version: currentPin?.version || 0 }); if (current()) { setPinPreview(result); setConfirmed(false); } })}>比较作品固定版本</Button>
      {pinPreview && <section aria-label="作品世界观版本确认"><p>{pinPreview.target_title}：{pinPreview.previous_snapshot_id ? '明确替换原固定引用' : '首次固定'} → 快照 v{pinPreview.snapshot_revision}。只改变只读引用，不覆盖作品资料、正文或 Canon。</p><label className="experimental-check"><input type="checkbox" checked={confirmed} disabled={action.busy} onChange={e => setConfirmed(e.target.checked)} />我确认仅为此作品固定这个世界观版本</label><Button disabled={!ready || action.busy || !confirmed} onClick={() => void action.run(async current => { await api.pin({ snapshot_id: pinPreview.snapshot_id, target_project_id: pinPreview.target_project_id, role: pinPreview.role, expected_version: pinPreview.expected_version }, pinPreview); if (current()) refresh(); }, '作品版本引用已持久化，其他作品保持原固定版本。')}>确认固定此作品世界观版本</Button></section>}
      {ready && pins.data?.items.map(pin => <article className="experimental-record" key={pin.id}>{pin.content_withheld ? <StatusMessage tone="warning">此作品或来源当前不可访问，固定引用详情已停止显示。</StatusMessage> : <><strong>{pin.target_title} · {pin.role && roles[pin.role]}</strong><p>{pin.universe_key} · 快照 v{pin.snapshot_revision} · 引用 v{pin.version} · {pin.status}</p>{!!pin.source_changes?.length && <StatusMessage tone="warning">原资料已变化，此作品仍使用原固定快照。</StatusMessage>}<p>历史引用版本：{pin.history_versions?.join('、') || '无'}</p></>}{pin.status === 'PINNED' && <Button disabled={action.busy} onClick={() => void action.run(async current => { await api.release(pin); if (current()) pins.reload(); }, '版本引用已解除，历史和作品内容保留。')}>解除此世界观固定引用</Button>}</article>)}
    </Panel>{!!action.error && <ErrorMessage error={action.error} />}{action.notice && <StatusMessage tone="success">{action.notice}</StatusMessage>}
  </section>;
}
