import { useEffect, useMemo, useState } from 'react';
import { Badge, Button, EmptyState, Panel, StatusMessage } from '../ui/primitives';
import type { ExperimentalClient } from './api';
import { segment } from './api';
import { Details, ErrorMessage, Field, ResourceState, useResource } from './shared';
import { useReviewAction } from './styleReviewClient';
import { downloadCaption, voiceSubtitleClient, type AudioPlan, type AudioSegment, type VoiceCatalog } from './voiceSubtitleClient';
let identity=0;
export function VoiceDirectionPanel(props:{client:ExperimentalClient;onOpenAudiobook?:()=>void}) {const key=useMemo(()=>++identity,[props.client]);return <VoiceContent key={key} {...props}/>;}
function VoiceContent({client,onOpenAudiobook}:{client:ExperimentalClient;onOpenAudiobook?:()=>void}) {
 const api=useMemo(()=>voiceSubtitleClient(client),[client]);const catalog=useResource(s=>api.voice(s),[api]);const jobs=useResource(s=>api.jobs(s),[api]);const action=useReviewAction();
 const [planId,setPlanId]=useState(''),[selected,setSelected]=useState<string[]>([]),[audio,setAudio]=useState('');
 const ready=!catalog.loading&&!catalog.error&&!!catalog.data;const plan=catalog.data?.plans.find(p=>p.id===planId);
 const refresh=()=>{catalog.reload();jobs.reload();};
 useEffect(()=>()=>{if(audio)URL.revokeObjectURL(audio);},[audio]);
 useEffect(()=>{setAudio('');},[planId,plan?.version,plan?.stale]);
 return <section className="experimental-section" aria-label="声音导演">
  <div className="experimental-actions"><h3>声音导演</h3><Button disabled={action.busy||catalog.loading} onClick={refresh}>刷新声音来源与任务</Button>{onOpenAudiobook&&<Button onClick={onOpenAudiobook}>打开原有声书审核</Button>}</div>
  <StatusMessage>不确定的说话人保持未分配。文本审核与声音授权分开确认；参考音频及克隆不受支持。选段排队后仍需显式执行，当前仅支持已配置本地服务、零外部费用。</StatusMessage>
  <ResourceState loading={catalog.loading} error={catalog.error}/>{!!action.error&&<ErrorMessage error={action.error}/>}<p role="status">{action.notice}</p>
  {ready&&<><Details label="真实能力与验证边界" value={catalog.data!.tts}/><Field label="声音导演有声计划"><select value={planId} disabled={action.busy} onChange={e=>{setPlanId(e.target.value);setSelected([]);}}><option value="">选择已有 R3 计划</option>{catalog.data!.plans.map(p=><option key={p.id} value={p.id}>{p.title} · v{p.version} · {p.status}</option>)}</select></Field>{!catalog.data!.plans.length&&<EmptyState title="还没有可编辑有声计划" detail="请先在原有声书入口创建计划和声音 Profile，再回到这里审核片段。"/>}</>}
  {plan&&<><Badge>{plan.status} · v{plan.version}</Badge>{plan.stale?<StatusMessage tone="warning">来源已变化。旧片段已隐藏，请从当前章节重建计划并重新审核。</StatusMessage>:<>
   <ol aria-label="片段轨道预览">{plan.segments?.map(s=><li key={s.id}>{s.kind} · {s.character_id||'未分配'} · {s.start_ms==null?'未测量':`${s.start_ms}–${s.end_ms??'?'} ms`} · 段后停顿 {s.direction?.pause_ms??0} ms（混音按实测帧应用，末段不追加）</li>)}</ol>
   {plan.segments?.map((s,index)=><article className="experimental-record" key={s.id}><label className="experimental-check"><input type="checkbox" checked={selected.includes(s.id)} disabled={action.busy||s.locked} onChange={()=>setSelected(old=>old.includes(s.id)?old.filter(id=>id!==s.id):[...old,s.id])}/>选择片段 {index+1} 重做</label><DirectionEditor client={client} plan={plan} item={s} catalog={catalog.data!} available={ready} refresh={refresh}/>
    <div className="experimental-actions"><Button disabled={!ready||action.busy||(!s.audio_asset_id&&!s.locked)} onClick={()=>void action.run(async current=>{await api.lock(plan,s);if(current())refresh();},s.locked?'已解锁片段':'已锁定满意音频')}>{s.locked?'解锁片段':'锁定满意片段'}</Button><Button disabled={!ready||action.busy||index===0||plan.status!=='PENDING_REVIEW'} onClick={()=>void action.run(async current=>{const ids=plan.segments!.map(v=>v.id);[ids[index-1],ids[index]]=[ids[index],ids[index-1]];await api.reorder(plan,ids);if(current())refresh();},'已调整顺序，字幕绑定会按来源检查')}>上移片段</Button></div>
   </article>)}
   <div className="experimental-actions"><Button disabled={!ready||action.busy||plan.status!=='APPROVED'||!selected.length} onClick={()=>void action.run(async current=>{await api.queue(plan,selected);if(current()){setSelected([]);refresh();}},'仅所选片段已进入原音频队列，尚未发送或接受结果')}>批准所选片段排队（本地）</Button><Button disabled={!ready||action.busy} onClick={()=>void action.run(async current=>{await client.post(`/audiobook/plans/${segment(plan.id)}/${plan.status==='PENDING_REVIEW'?'approve':'reopen'}`,{expected_version:plan.version});if(current())refresh();},'原有声计划审核状态已更新')}>{plan.status==='PENDING_REVIEW'?'审核并批准计划':'重开原有声计划审核'}</Button></div>
   <p>满意片段不会随选段重做重新生成。情绪是否有效由真实 Provider 检查，不支持会报错；真实音色质量尚未验证。</p>
   <Panel title="混音试听与导出">
    <p>绑定全部实测音频并批准当前计划后，可在本地按片段顺序、停顿和原有音乐 / 环境 / 音效轨道生成 WAV。各来源须为相同采样率和声道的 PCM16 WAV；生成后仍待试听和审核。</p>
    <Button disabled={!ready||action.busy||!plan.voice_direction||plan.status!=='APPROVED'||plan.timing_status!=='MEASURED'||!catalog.data?.mixer||catalog.data.mixer==='NOT_CONFIGURED'} onClick={()=>void action.run(async current=>{await api.mix(plan);if(current())catalog.reload();},'已生成本地实测混音，尚未批准为资产')}>生成含停顿混音候选</Button>
    {catalog.data?.mixer==='NOT_CONFIGURED'&&<StatusMessage tone="warning">本地混音器未配置。</StatusMessage>}
    {(catalog.data?.mixes||[]).filter(m=>m.plan_id===plan.id).map(mix=><article className="experimental-record" key={mix.id} aria-label={`混音候选 ${mix.id}`}><Badge>{mix.status}</Badge><p>{mix.stale?'计划或音频来源已变化，请重新生成候选':`${mix.media?.duration_ms??'?'} ms · ${mix.verification}`}</p>{!mix.stale&&['PENDING_REVIEW','APPROVING','APPROVED'].includes(mix.status||'')&&<div className="experimental-actions"><Button disabled={action.busy} onClick={()=>void action.run(async current=>{const blob=await api.mixAudio(mix);if(current())setAudio(URL.createObjectURL(blob));},'已读取含停顿混音，请试听完整轨道')}>试听含停顿混音</Button><Button disabled={action.busy} onClick={()=>void action.run(async current=>{const blob=await api.mixAudio(mix);if(current())downloadCaption(blob,`directed-mix-${mix.id}.wav`);},'已下载实测 WAV；下载不代表批准资产')}>下载混音 WAV</Button>{mix.status!=='APPROVED'&&<Button disabled={action.busy} onClick={()=>void action.run(async current=>{await api.reviewMix(mix,'approve');if(current())catalog.reload();},'混音已批准加入原资产库，保留来源与版本')}>{mix.status==='APPROVING'?'继续混音资产审核':'批准混音资产'}</Button>}{mix.status==='PENDING_REVIEW'&&<Button disabled={action.busy} onClick={()=>void action.run(async current=>{await api.reviewMix(mix,'reject');if(current()){setAudio('');catalog.reload();}},'已拒绝此混音候选')}>拒绝混音候选</Button>}</div>}</article>)}
   </Panel>
  </>}</>}
  <Panel title="选段执行与试听"><ResourceState loading={jobs.loading} error={jobs.error}/>{!jobs.loading&&!jobs.error&&!jobs.data?.items.length&&<EmptyState title="没有选段任务" detail="审核计划后，显式选择需要制作的片段。"/>}{!jobs.loading&&!jobs.error&&jobs.data?.items.map(job=><article className="experimental-record" key={job.id}><Badge>{job.status}</Badge><p>{job.stale?'来源已变化，不能执行或试听':`${job.id} · ${job.approval_status||'PENDING'}`}</p>{job.error_code&&<StatusMessage tone="error">{job.error_code}</StatusMessage>}{!job.stale&&<div className="experimental-actions">{job.status==='QUEUED'&&<Button disabled={action.busy} onClick={()=>void action.run(async current=>{await api.jobAction(job,'execute');if(current())jobs.reload();},'执行已结束，结果仍待试听和审核')}>执行此片段</Button>}{['QUEUED','RUNNING'].includes(job.status||'')&&<Button disabled={action.busy} onClick={()=>void action.run(async current=>{await api.jobAction(job,'cancel');if(current())jobs.reload();},'已请求取消；已发送数据无法撤回')}>取消片段任务</Button>}{['FAILED','CANCELLED'].includes(job.status||'')&&<Button disabled={action.busy} onClick={()=>void action.run(async current=>{await api.jobAction(job,'retry');if(current())jobs.reload();},'重试已排队，仍需显式执行')}>重新排队</Button>}{job.status==='SUCCEEDED'&&<><Button disabled={action.busy} onClick={()=>void action.run(async current=>{const blob=await api.audio(job);if(current())setAudio(URL.createObjectURL(blob));},'已读取实测音频，请使用播放器试听')}>试听已有片段</Button>{job.approval_status==='PENDING'&&<Button disabled={action.busy} onClick={()=>void action.run(async current=>{await api.jobAction(job,'approve');if(current())refresh();},'音频已批准加入原资产库；请在重开的原计划中显式绑定')}>批准此音频资产</Button>}<p>音频资产：{job.asset_id}</p></>}</div>}</article>)}{audio&&<audio controls src={audio} aria-label="实测片段试听播放器"/>}</Panel>
 </section>;
}
function DirectionEditor({client,plan,item,catalog,available,refresh}:{client:ExperimentalClient;plan:AudioPlan;item:AudioSegment;catalog:VoiceCatalog;available:boolean;refresh:()=>void}) {
 const api=useMemo(()=>voiceSubtitleClient(client),[client]);const action=useReviewAction();const [captured,setCaptured]=useState(plan);
 const defaults=()=>({kind:item.kind,character_id:item.character_id||'',profile_id:item.profile_id||'',reviewed_text:item.direction?.reviewed_text??item.text,attribution_reviewed:item.attribution_status!=='NEEDS_REVIEW',text_reviewed:item.direction?.text_reviewed??false,voice_authorized:item.direction?.voice_authorized??false,emotion:item.direction?.emotion??'neutral',speech_rate:item.direction?.speech_rate??1,pause_ms:item.direction?.pause_ms??280});
 const [draft,setDraft]=useState(defaults),[rules,setRules]=useState(item.direction?.pronunciation_rules.map(r=>`${r.term}=${r.pronunciation}`).join('\n')||''),[asset,setAsset]=useState('');
 const changed=captured.version!==plan.version;const disabled=!available||action.busy||item.locked||plan.status!=='PENDING_REVIEW';
 const field=(key:keyof typeof draft,value:any)=>setDraft(d=>({...d,[key]:value,...(key==='reviewed_text'?{text_reviewed:false}:{}),...(key==='profile_id'?{voice_authorized:false}:{}),...(['kind','character_id'].includes(key)?{attribution_reviewed:false}:{})}));
 return <><p>原文：{item.text}</p><Badge>{item.attribution_status==='NEEDS_REVIEW'?'未分配 / 待核对':item.attribution_status}</Badge>{changed&&<StatusMessage tone="warning">计划版本已变化，当前输入仍保留。请核对后载入当前版本，不能静默覆盖。</StatusMessage>}{!!action.error&&<ErrorMessage error={action.error}/>}<p role="status">{action.notice}</p>
 <Button disabled={action.busy} onClick={()=>{setCaptured(plan);setDraft(defaults());setRules(item.direction?.pronunciation_rules.map(r=>`${r.term}=${r.pronunciation}`).join('\n')||'');}}>载入当前片段并替换本地输入</Button>
 <Field label="片段类型"><select disabled={disabled} value={draft.kind} onChange={e=>field('kind',e.target.value)}><option value="NARRATION">旁白 / 引述</option><option value="DIALOGUE">角色对白</option></select></Field>
 <Field label="说话人"><select disabled={disabled||draft.kind==='NARRATION'} value={draft.character_id} onChange={e=>field('character_id',e.target.value)}><option value="">未分配</option>{catalog.characters.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>
 <Field label="使用的声音 Profile"><select disabled={disabled} value={draft.profile_id} onChange={e=>field('profile_id',e.target.value)}><option value="">未分配</option>{catalog.profiles.map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select></Field>
 <Field label="此片段审核朗读文本"><textarea disabled={disabled} value={draft.reviewed_text} onChange={e=>field('reviewed_text',e.target.value)}/></Field>
 <div className="experimental-grid"><Field label="情绪参数"><input disabled={disabled} value={draft.emotion} onChange={e=>field('emotion',e.target.value)}/></Field><Field label="朗读速度"><input disabled={disabled} type="number" min={.5} max={2} step={.05} value={draft.speech_rate} onChange={e=>field('speech_rate',Number(e.target.value))}/></Field><Field label="段后停顿毫秒"><input disabled={disabled} type="number" min={0} max={3000} value={draft.pause_ms} onChange={e=>field('pause_ms',Number(e.target.value))}/></Field></div>
 <Field label="片段发音规则（每行 原词=读音）"><textarea disabled={disabled} value={rules} onChange={e=>{setRules(e.target.value);field('text_reviewed',false);}}/></Field><p>发音规则只做同时的字面替换，不执行正则、SSML、参考音频或外部地址。</p>
 {(['attribution_reviewed','text_reviewed','voice_authorized'] as const).map((key,i)=><label className="experimental-check" key={key}><input type="checkbox" disabled={disabled} checked={draft[key]} onChange={e=>field(key,e.target.checked)}/>{['已核对说话人归属','已审核此片段朗读文本','已确认此声音的使用授权'][i]}</label>)}
 <Button disabled={disabled||changed} onClick={()=>void action.run(async current=>{const pronunciation_rules=rules.split('\n').filter(s=>s.trim()).map(line=>{const i=line.indexOf('=');if(i<1)throw new Error('每行需要 原词=读音');return {term:line.slice(0,i),pronunciation:line.slice(i+1)};});const next=await api.edit(captured,item,{...draft,character_id:draft.character_id||null,profile_id:draft.profile_id||null,pronunciation_rules});if(current()){setCaptured(next);refresh();}},'当前片段已保存，只有该片段的旧音频失效')}>保存声音方向</Button>
 <Field label="已批准实测音频资产 ID"><input disabled={disabled} value={asset} onChange={e=>setAsset(e.target.value)}/></Field><Button disabled={disabled||changed||!asset} onClick={()=>void action.run(async current=>{const next=await client.put<AudioPlan>(`/audiobook/plans/${segment(plan.id)}/segments/${segment(item.id)}/audio`,{expected_version:captured.version,asset_id:asset});if(current()){setCaptured(next);refresh();}},'已绑定原资产库的实测音频')}>绑定此片段实测音频</Button>
 </>;
}
