import {expect,test,type Page,type Route} from '@playwright/test';

const scope={workspaceId:'w-e2e',projectId:'p-e2e',storylineId:'s-e2e',branchId:'b-e2e'};
const scopeNamespace=[scope.workspaceId,scope.projectId,scope.storylineId,scope.branchId].join('\u001f');
function fingerprint(token:string){let hash=2166136261;for(const character of token)hash=Math.imul(hash^character.charCodeAt(0),16777619);return (hash>>>0).toString(36)}
const namespace=(token:string)=>`${scopeNamespace}\u001fclient:${fingerprint(token)}`;
const chapter=(version=2,content='Latest server content')=>({id:'chapter-e2e',novel_id:scope.projectId,number:1,title:'Recovery chapter',content,document:{type:'doc',content:[]},version,word_count:3,status:'DRAFT'});

async function seed(page:Page,token:string,{draft=true,branch=scope.branchId}:{draft?:boolean;branch?:string}={}){
 await page.addInitScript(({scope,token,branch,draft,key})=>{const selected={...scope,branchId:branch};localStorage.setItem('studio.session',token);localStorage.setItem('studio.scope',JSON.stringify(selected));if(draft)localStorage.setItem(`ai-novel-studio:draft:${key}:chapter-e2e`,JSON.stringify({chapterId:'chapter-e2e',content:'Preserved local content',baseVersion:1,updatedAt:'2026-08-10T10:00:00Z'}));},{scope,token,branch,draft,key:namespace(token)});
}

async function routes(page:Page,actorId:string,onPut?:(route:Route,body:any)=>Promise<void>,getChapter=()=>chapter()){
 await page.route('**/api/**',async route=>{const path=new URL(route.request().url()).pathname;if(path.endsWith('/bootstrap'))return route.fulfill({json:{actor:{actor_id:actorId,session_id:'session-e2e',client_id:'client-e2e'},scope:{workspace_id:scope.workspaceId,project_id:scope.projectId,storyline_id:scope.storylineId,branch_id:scope.branchId},capabilities:{}}});if(path.endsWith('/chapters')&&path.includes('/collaboration/'))return route.fulfill({json:{items:[getChapter()]}});if(path.endsWith('/api/chapters/chapter-e2e')&&route.request().method()==='GET')return route.fulfill({json:getChapter()});if(path.endsWith('/api/chapters/chapter-e2e')&&route.request().method()==='PUT'&&onPut)return onPut(route,route.request().postDataJSON());return route.fulfill({json:{items:[]}})});
}

for(const scenario of [{name:'different-user',actor:'actor-b',token:'session-b'},{name:'same-user second client',actor:'actor-a',token:'session-a-client-2'}])test(`${scenario.name} stale draft enters conflict without overwrite`,async({page})=>{await seed(page,scenario.token);await routes(page,scenario.actor);await page.goto('/');await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('dialog')).toContainText('Preserved local content');await expect(page.getByRole('dialog')).toContainText('Latest server content')});

test('refresh recovery, repeated conflict, then manual resolution succeeds',async({page})=>{const token='recovery-session';await seed(page,token);let attempts=0,server=chapter();await routes(page,'actor-recovery',async(route,body)=>{attempts++;expect(body.version).toBe(attempts===1?2:3);if(attempts===1){server=chapter(3,'Changed while resolving');return route.fulfill({status:409,json:{detail:{code:'VERSION_CONFLICT',message:'changed again',actual_version:3}}})}server=chapter(4,body.content);return route.fulfill({json:server})},()=>server);await page.goto('/');await expect(page.getByRole('dialog')).toBeVisible();await page.reload();await expect(page.getByRole('dialog')).toContainText('Preserved local content');let textarea=page.getByRole('textbox',{name:'手工解决草稿'});await textarea.fill('First resolution');await page.getByRole('button',{name:'应用手工解决并保存'}).click();await expect(page.getByRole('dialog')).toBeVisible();textarea=page.getByRole('textbox',{name:'手工解决草稿'});await textarea.fill('Final resolution');await page.getByRole('button',{name:'应用手工解决并保存'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect.poll(()=>attempts).toBe(2)});

test('wrong branch and different session cannot hydrate another recovery draft',async({page})=>{const owner='owner-session';await seed(page,'other-session',{draft:false,branch:'branch-other'});await page.addInitScript(({key})=>localStorage.setItem(`ai-novel-studio:draft:${key}:chapter-e2e`,JSON.stringify({chapterId:'chapter-e2e',content:'Owner secret draft',baseVersion:1,updatedAt:'2026-08-10T10:00:00Z'})),{key:namespace(owner)});await routes(page,'actor-other');await page.goto('/');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('.ProseMirror')).not.toContainText('Owner secret draft')});
