import fs from 'node:fs';
import path from 'node:path';
import {expect,test} from '@playwright/test';

const sessions=JSON.parse(fs.readFileSync(path.resolve('..','.runtime','acceptance-sessions.json'),'utf8').replace(/^\uFEFF/,''));
const admin=sessions.find((item:{role:string})=>item.role==='ADMIN');
const run=JSON.parse(fs.readFileSync(path.resolve('..','.runtime','v061-browser-run.json'),'utf8'));
const roundtrip=run.roundtrip_empty as {id:string;name:string};
const alpha={workspaceId:'acceptance-alpha',projectId:'acceptance-alpha-novel',storylineId:'acceptance-alpha-storyline',branchId:'acceptance-alpha-main'};
const evidence=path.resolve('..','.runtime','v061-browser-results.jsonl');

function record(name:string,result:string,started:number,extra:Record<string,unknown>={}){
  fs.appendFileSync(evidence,JSON.stringify({run_id:run.run_id,scenario:name,result,started_at:new Date(started).toISOString(),ended_at:new Date().toISOString(),duration_ms:Date.now()-started,...extra})+'\n');
}
async function enter(page:any,scope=alpha){await page.addInitScript(({token,value}:{token:string;value:any})=>{localStorage.setItem('studio.session',token);localStorage.setItem('studio.scope',JSON.stringify(value))},{token:admin.token,value:scope});await page.goto('/',{waitUntil:'domcontentloaded'});await expect(page.locator('.app-shell')).toBeVisible()}
async function management(page:any){await page.getByRole('button',{name:'团队成员'}).click();await expect(page.locator('.workspace-management')).toBeVisible()}
async function switchTo(page:any,label:string,workspaceId:string){await page.locator('.workspace-list__item').filter({hasText:label}).click();await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('studio.scope')!).workspaceId)).toBe(workspaceId);return page.evaluate(()=>JSON.parse(localStorage.getItem('studio.scope')!))}
async function createScenarioWorkspace(page:any,prefix:string){const id=`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;const headers={'X-Session-Token':admin.token};expect((await page.request.post('/api/collaboration/admin/workspaces',{headers,data:{id,name:id}})).status()).toBe(201);return id}

test.afterEach(async({page},info)=>record(info.title,info.status||'unknown',(page as any).__startedAt||Date.now(),{errors:info.errors.map(error=>error.message),console_errors:(page as any).__consoleErrors||[],network_errors:(page as any).__networkErrors||[]}));
test.beforeEach(async({page})=>{const consoleErrors:string[]=[],networkErrors:string[]=[];(page as any).__startedAt=Date.now();(page as any).__consoleErrors=consoleErrors;(page as any).__networkErrors=networkErrors;page.on('pageerror',error=>consoleErrors.push(error.message));page.on('console',message=>{if(message.type()==='error')consoleErrors.push(message.text())});page.on('response',response=>{if(response.status()>=400)networkErrors.push(`${response.status()} ${response.url()}`)})});

test('A1 Empty Workspace',async({page})=>{expect(roundtrip.id).toBe(`acceptance-roundtrip-empty-${run.run_id}`);expect(roundtrip.id).not.toBe('acceptance-empty');await enter(page);await management(page);const scope=await switchTo(page,roundtrip.name,roundtrip.id);expect(scope).toMatchObject({workspaceId:roundtrip.id,projectId:'',storylineId:'',branchId:''});await expect(page.locator('.app-shell')).toBeVisible();await expect(page.locator('.context-bar')).toContainText('NONE');await page.evaluate(()=>localStorage.removeItem('studio.scope'));const entry=await page.context().newPage();await entry.goto('/',{waitUntil:'domcontentloaded'});await entry.getByRole('button',{name:roundtrip.name,exact:true}).click();await expect(entry.getByLabel('项目名称')).toBeVisible();await expect(entry.getByRole('button',{name:'创建并打开'})).toBeVisible();await entry.close()});
test('A2 Chapter Empty State',async({page})=>{const workspace=await createScenarioWorkspace(page,'acceptance-a2');await page.addInitScript(t=>localStorage.setItem('studio.session',t),admin.token);await page.goto('/',{waitUntil:'domcontentloaded'});await page.getByRole('button',{name:workspace}).click();const title=`验收小说 ${Date.now()}`;await page.getByLabel('项目名称').fill(title);await page.getByRole('button',{name:'创建并打开'}).click();await expect(page.getByText('当前还没有打开的章节')).toBeVisible();await page.getByRole('button',{name:'新建章节'}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByLabel('章节标题').fill('第一章 新的开始');await page.getByRole('button',{name:'创建章节',exact:true}).click();await page.locator('.novel-tree-select').filter({hasText:'第一章 新的开始'}).click();await expect(page.getByRole('heading',{name:'第一章 新的开始'})).toBeVisible()});
test('A3 Story DB No Project',async({page})=>{await enter(page,{workspaceId:'acceptance-empty',projectId:'',storylineId:'',branchId:''});await page.getByRole('button',{name:'故事资料库'}).click();await expect(page.getByText(/请先新建或选择一个章节/)).toBeVisible()});
test('A4 Story DB Empty Category',async({page})=>{const workspace=await createScenarioWorkspace(page,'acceptance-a4');const headers={'X-Session-Token':admin.token};expect((await page.request.post(`/api/collaboration/admin/workspaces/${workspace}/projects`,{headers,data:{title:'Story DB Empty',genre:''}})).status()).toBe(201);const navigation=await (await page.request.get(`/api/collaboration/admin/workspaces/${workspace}/navigation`,{headers})).json();const path=navigation.default_path;expect((await page.request.post(`/api/collaboration/workspaces/${workspace}/projects/${path.project_id}/storylines/${path.storyline_id}/branches/${path.branch_id}/chapters`,{headers,data:{title:'Story DB Empty Chapter'}})).status()).toBe(201);await enter(page,{workspaceId:workspace,projectId:path.project_id,storylineId:path.storyline_id,branchId:path.branch_id});await Promise.all([page.waitForResponse(response=>response.url().includes('/story-database/characters')&&response.ok()),page.getByRole('button',{name:'故事资料库'}).click()]);await expect(page.getByText(/还没有.*记录/).first()).toBeVisible()});
test('B1 Alpha to Beta',async({page})=>{await enter(page);await management(page);const scope=await switchTo(page,'Workspace Beta','acceptance-beta');expect(scope.projectId).not.toContain('alpha')});
test('B2 Beta to Empty',async({page})=>{await enter(page,{workspaceId:'acceptance-beta',projectId:'acceptance-beta-novel',storylineId:'acceptance-beta-storyline',branchId:'acceptance-beta-main'});await management(page);const scope=await switchTo(page,roundtrip.name,roundtrip.id);expect(scope).toMatchObject({workspaceId:roundtrip.id,projectId:'',storylineId:'',branchId:''})});
test('B3 Empty to Alpha',async({page})=>{await enter(page,{workspaceId:roundtrip.id,projectId:'',storylineId:'',branchId:''});await management(page);const scope=await switchTo(page,'Workspace Alpha','acceptance-alpha');expect(scope.projectId).toContain('alpha');const managementMain=page.locator('.workspace-management__main');await expect(managementMain).toContainText('Acceptance Admin');await expect(managementMain).not.toContainText('acceptance-admin')});
test('B4 Story DB Isolation',async({page})=>{await enter(page);await page.getByRole('button',{name:'故事资料库'}).click();await expect(page.locator('.novel-story-database')).toBeVisible();await management(page);await switchTo(page,roundtrip.name,roundtrip.id);await page.getByRole('button',{name:'故事资料库'}).click();await expect(page.locator('.novel-story-database')).toHaveCount(0);await expect(page.getByText(/请先新建或选择一个章节/)).toBeVisible()});
test('B5 Permission Refresh',async({page})=>{const memberUrls:string[]=[];page.on('response',response=>{if(response.url().includes('/admin/workspaces/')&&response.url().endsWith('/members')&&response.status()===200)memberUrls.push(response.url())});await enter(page);await management(page);await switchTo(page,'Workspace Beta','acceptance-beta');expect(memberUrls.some(url=>url.includes('/acceptance-beta/members'))).toBe(true);await switchTo(page,roundtrip.name,roundtrip.id);expect(memberUrls.some(url=>url.includes(`/${roundtrip.id}/members`))).toBe(true)});
test('C1 autosave and C2 reload persistence',async({page})=>{const workspace=await createScenarioWorkspace(page,'acceptance-c1');const headers={'X-Session-Token':admin.token};const projectResponse=await page.request.post(`/api/collaboration/admin/workspaces/${workspace}/projects`,{headers,data:{title:'Autosave Acceptance',genre:''}});expect(projectResponse.status()).toBe(201);const navigation=await (await page.request.get(`/api/collaboration/admin/workspaces/${workspace}/navigation`,{headers})).json();const path=navigation.default_path;await enter(page,{workspaceId:workspace,projectId:path.project_id,storylineId:path.storyline_id,branchId:path.branch_id});await page.getByRole('button',{name:'新建章节'}).click();await page.getByLabel('章节标题').fill('Autosave Chapter');await page.getByRole('button',{name:'创建章节',exact:true}).click();await page.locator('.novel-tree-select').filter({hasText:'Autosave Chapter'}).click();const editor=page.locator('.ProseMirror');await expect(editor).toBeVisible();const marker=`V061_ACCEPTANCE_${Date.now()}`;await editor.fill(marker);await expect(page.locator('.editorbar')).toContainText('已保存',{timeout:5_000});await page.reload({waitUntil:'domcontentloaded'});await expect(page.locator('.ProseMirror')).toContainText(marker)});
test('C3 touched accessibility and C4 audit',async({page})=>{await enter(page);await expect(page.getByRole('button',{name:'新建章节'})).toBeVisible();await expect(page.getByRole('button',{name:'团队成员'})).toBeVisible();await page.getByRole('button',{name:'新建章节'}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByLabel('章节标题')).toBeFocused();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);expect((page as any).__consoleErrors.filter((value:string)=>value.includes('body stream already read'))).toEqual([]);expect((page as any).__consoleErrors).toEqual([]);expect((page as any).__networkErrors).toEqual([])});
