"""Stable reason codes for the Phase 2B Windows sandbox prototype."""

from __future__ import annotations


REASON_WINDOWS_SANDBOX_UNAVAILABLE = "WINDOWS_SANDBOX_UNAVAILABLE"
REASON_SANDBOX_PROFILE_CREATE_FAILED = "SANDBOX_PROFILE_CREATE_FAILED"
REASON_SANDBOX_SID_FAILED = "SANDBOX_SID_FAILED"
REASON_SANDBOX_ACL_FAILED = "SANDBOX_ACL_FAILED"
REASON_SANDBOX_LAUNCH_FAILED = "SANDBOX_LAUNCH_FAILED"
REASON_SANDBOX_TOKEN_VERIFICATION_FAILED = "SANDBOX_TOKEN_VERIFICATION_FAILED"
REASON_SANDBOX_JOB_ASSIGNMENT_FAILED = "SANDBOX_JOB_ASSIGNMENT_FAILED"
REASON_SANDBOX_STAGING_FAILED = "SANDBOX_STAGING_FAILED"
REASON_PYTHON_APPCONTAINER_COMPATIBILITY_BLOCKED = "PYTHON_APPCONTAINER_COMPATIBILITY_BLOCKED"

PROCESS_MEMORY_LIMIT_BYTES = 512 * 1024 * 1024


class SandboxError(RuntimeError):
    def __init__(self, code: str, *, winerr: int | None = None):
        self.code = code
        self.winerr = winerr
        extra = f" winerr={winerr}" if winerr else ""
        super().__init__(f"{code}{extra}")
