BEGIN;
CREATE TABLE workspaces(id TEXT PRIMARY KEY,payload JSONB NOT NULL);
CREATE TABLE project_workspaces(project_id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id));
CREATE TABLE storylines(id TEXT PRIMARY KEY,payload JSONB NOT NULL);
CREATE TABLE storyline_branches(id TEXT PRIMARY KEY,payload JSONB NOT NULL);
ALTER TABLE novels ADD COLUMN workspace_id TEXT REFERENCES workspaces(id);
INSERT INTO workspaces(id,payload) VALUES ('default-workspace',jsonb_build_object('id','default-workspace','name','Default Workspace','created_at',now()::text,'updated_at',now()::text));
INSERT INTO project_workspaces(project_id,workspace_id) SELECT slug,'default-workspace' FROM novels;
UPDATE novels SET workspace_id='default-workspace';
ALTER TABLE novels ALTER COLUMN workspace_id SET DEFAULT 'default-workspace';
ALTER TABLE novels ALTER COLUMN workspace_id SET NOT NULL;
INSERT INTO storylines(id,payload) SELECT 'default-storyline:'||slug,jsonb_build_object('id','default-storyline:'||slug,'workspace_id','default-workspace','project_id',slug,'name','Default Storyline','description','','created_at',now()::text,'updated_at',now()::text) FROM novels;
INSERT INTO storyline_branches(id,payload) SELECT 'main:default-storyline:'||slug,jsonb_build_object('id','main:default-storyline:'||slug,'workspace_id','default-workspace','project_id',slug,'storyline_id','default-storyline:'||slug,'name','main','parent_branch_id',NULL,'created_at',now()::text,'updated_at',now()::text) FROM novels;
ALTER TABLE narrative_threads ADD COLUMN storyline_id TEXT,ADD COLUMN branch_id TEXT;
ALTER TABLE narrative_foreshadowing ADD COLUMN storyline_id TEXT,ADD COLUMN branch_id TEXT;
ALTER TABLE narrative_events ADD COLUMN storyline_id TEXT,ADD COLUMN branch_id TEXT;
ALTER TABLE narrative_expectations ADD COLUMN storyline_id TEXT,ADD COLUMN branch_id TEXT;
ALTER TABLE narrative_findings ADD COLUMN storyline_id TEXT,ADD COLUMN branch_id TEXT;
ALTER TABLE narrative_mysteries ADD COLUMN storyline_id TEXT,ADD COLUMN branch_id TEXT;
ALTER TABLE narrative_character_goals ADD COLUMN storyline_id TEXT,ADD COLUMN branch_id TEXT;
ALTER TABLE narrative_chapter_links ADD COLUMN storyline_id TEXT,ADD COLUMN branch_id TEXT;
ALTER TABLE narrative_change_proposals ADD COLUMN storyline_id TEXT,ADD COLUMN branch_id TEXT;
CREATE FUNCTION fill_default_narrative_scope() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.storyline_id=COALESCE(NEW.storyline_id,'default-storyline:'||NEW.project_id);NEW.branch_id=COALESCE(NEW.branch_id,'main:default-storyline:'||NEW.project_id);RETURN NEW;END $$;
DO $$ DECLARE t TEXT; BEGIN FOREACH t IN ARRAY ARRAY['narrative_threads','narrative_foreshadowing','narrative_events','narrative_expectations','narrative_findings','narrative_mysteries','narrative_character_goals','narrative_chapter_links','narrative_change_proposals'] LOOP EXECUTE format('UPDATE %I SET storyline_id=%L||project_id,branch_id=%L||project_id',t,'default-storyline:','main:default-storyline:'); EXECUTE format('CREATE TRIGGER fill_scope BEFORE INSERT ON %I FOR EACH ROW EXECUTE FUNCTION fill_default_narrative_scope()',t); EXECUTE format('ALTER TABLE %I ALTER COLUMN storyline_id SET NOT NULL,ALTER COLUMN branch_id SET NOT NULL',t); EXECUTE format('CREATE INDEX %I ON %I(project_id,storyline_id,branch_id,id)','idx_'||t||'_scope',t); END LOOP; END $$;
INSERT INTO schema_versions(version) VALUES ('0.5.5-collaboration-scope-foundation');
COMMIT;
