import { useEffect, useRef, useState } from 'react';
import { ApiError } from '../api';
import { Badge, Button, EmptyState, Panel, StatusMessage } from '../ui/primitives';
import { DirectorModelControls } from './DirectorModelControls';
import { DirectorFields, CreativeField } from './CreativeCanvas';
import type { CreativeClient, DirectorProposal } from './client';
import type { CreativeDocument, DirectorSceneNote } from './types';
import type { AssetSelection } from './AssetBrowser';
export function AIDirectorPanel({ client, documents, canMutate, onDocument, onDenied, asset, onOpenModels, environment, onBusyChange }: { client: CreativeClient; documents: CreativeDocument[]; canMutate: boolean; onDocument: (document: CreativeDocument) => void; onDenied: () => void; asset?: AssetSelection; onOpenModels: () => void; environment?: React.ReactNode; onBusyChange?: (busy: boolean) => void }) {
  const [proposals, setProposals] = useState<DirectorProposal[]>([]), [proposal, setProposal] = useState<DirectorProposal>(), [sourceId, setSourceId] = useState(''), [title, setTitle] = useState(''), [notes, setNotes] = useState<DirectorSceneNote[]>([]), [reviewed, setReviewed] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [uncertain, setUncertain] = useState(false);
  const live = useRef(true), lock = useRef(false), epoch = useRef(0);
  useEffect(() => { live.current = true; return () => { live.current = false; epoch.current++; }; }, []);
  useEffect(() => { onBusyChange?.(busy); return () => onBusyChange?.(false); }, [busy, onBusyChange]);
  const read = async (signal?: AbortSignal) => { const ticket = ++epoch.current; try { const result = await client.proposals(signal); if (!signal?.aborted && live.current && ticket === epoch.current) { setProposals(result.items); setError(''); return true; } return false; } catch (value) { if (!signal?.aborted && live.current && ticket === epoch.current) { setError(value instanceof ApiError ? `${value.message} (${value.problem.code})` : '导演建议暂时不可读。'); if (value instanceof ApiError && (value.status === 401 || value.status === 403)) onDenied(); } return false; } };
  useEffect(() => { const controller = new AbortController(); void read(controller.signal); return () => controller.abort(); }, [client]);
  const sources = documents.filter(row => row.mode === 'SCREENPLAY' && row.scenes.length);
  const source = sources.find(row => row.id === sourceId) || sources[0];
  const select = (row: DirectorProposal) => { setProposal(row); setNotes(structuredClone(row.director_notes)); setTitle(row.title); setReviewed(false); setNotice(''); };
  const run = async (action: () => Promise<void>) => { if (lock.current || !canMutate || uncertain) return; lock.current = true; setBusy(true); setError(''); setNotice(''); try { await action(); } catch (value) { if (live.current) { setError(value instanceof ApiError ? `${value.message} (${value.problem.code})` : '操作回执不确定。请重新读取建议，勿重复创建或采用。'); setReviewed(false); if (!(value instanceof ApiError) || value.status >= 500 || value.status === 409) setUncertain(true); if (value instanceof ApiError && (value.status === 401 || value.status === 403)) onDenied(); } } finally { lock.current = false; if (live.current) setBusy(false); } };
  // A fast receipt can release the lock before the second native double-click.
  // Keep one proposal per gesture; keyboard (0) and later single clicks (1) still work.
  const prepareProposal = (clickCount: number) => { if (clickCount > 1 || !source) return; void run(async () => { const result = await client.propose(source); if (live.current) { select(result); setProposals(rows => [result, ...rows]); setNotice('建议已生成，等待逐项核对。未调用模型。'); } }); };
  return <div className="creative-director-panel" aria-label="AI 导演面板"><header><span className="creative-eyebrow">AI Director</span><h2>导演协作与审核</h2></header>{asset && <Panel title="选中资产"><strong>{asset.title}</strong><p>{asset.kind} · {asset.detail}</p><small>{asset.id}</small></Panel>}
    <Panel title="从剧本准备导演建议"><p>本地规则辅助会整理场景调度草案。不会调用模型；采用后新增独立导演文档。</p><CreativeField label="导演建议来源剧本"><select value={source?.id || ''} disabled={busy} onChange={e => setSourceId(e.target.value)}><option value="">选择已保存剧本</option>{sources.map(row => <option key={row.id} value={row.id}>{row.title} · v{row.version}</option>)}</select></CreativeField><Button disabled={!canMutate || busy || uncertain || !source} onClick={event => prepareProposal(event.detail)}>{busy ? '处理中…' : '准备待审导演建议'}</Button>{!sources.length && <p>先保存一份含场景的剧本，再准备导演建议。</p>}</Panel>
    {error && <StatusMessage tone="error">{error}</StatusMessage>}{notice && <StatusMessage tone="success">{notice}</StatusMessage>}{uncertain && <StatusMessage tone="warning">操作结果需核对。当前审核内容已保留。<Button disabled={busy} onClick={() => { setProposal(undefined); setReviewed(false); void read().then(success => { if (success && live.current) setUncertain(false); }); }}>重新读取建议状态</Button></StatusMessage>}
    <Panel title="建议审核队列" actions={<Button disabled={busy} onClick={() => void read()}>刷新</Button>}><div className="creative-proposal-list">{proposals.map(row => <Button key={row.id} disabled={busy} aria-pressed={proposal?.id === row.id} onClick={() => select(row)}>{row.title}<Badge>{row.status}</Badge></Button>)}</div>{!proposals.length && !error && <EmptyState title="没有待审导演建议" detail="手动编辑始终可用。只有明确核对并采用建议才会创建导演文档。" />}
      {proposal && <section aria-label="导演建议审核"><p>来源 v{proposal.source_version} · 建议 v{proposal.version}</p><Badge tone="info">{proposal.provenance?.model_called ? '模型产出 · 需审核' : '本地规则辅助 · 未调用模型'}</Badge><DirectorModelControls key={proposal.id} client={client} proposal={proposal} disabled={busy || !canMutate || uncertain} run={run} onUpdate={row => { if (!live.current) return; select(row); setProposals(rows => rows.map(item => item.id === row.id ? row : item)); }} />
        <fieldset disabled={busy || !canMutate || proposal.status !== 'NEEDS_REVIEW' || uncertain}><legend className="creative-sr-only">建议内容</legend><CreativeField label="采用后的导演文档标题"><input maxLength={240} value={title} onChange={e => { setTitle(e.target.value); setReviewed(false); }} /></CreativeField>{notes.map((note, index) => <details key={note.id}><summary>场景调度 {index + 1}</summary><DirectorFields value={note} prefix={`建议 ${index + 1} `} onChange={next => { setNotes(rows => rows.map(row => row.id === next.id ? next : row)); setReviewed(false); }} /></details>)}<label className="creative-review-check"><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)} />已核对来源、场面调度与导演建议；创建独立导演文档</label><div className="creative-actions"><Button variant="primary" disabled={!reviewed || !title.trim()} onClick={() => void run(async () => { const result = await client.review(proposal, title, notes); if (live.current) { setProposal(result.proposal); setReviewed(false); setProposals(rows => rows.map(row => row.id === result.proposal.id ? result.proposal : row)); setNotice('已创建导演文档。小说正文保持原有保存与审核流程。'); onDocument(result.document); } })}>审核并采用</Button><Button onClick={() => void run(async () => { const result = await client.cancelProposal(proposal); if (live.current) { setProposal(result); setReviewed(false); setProposals(rows => rows.map(row => row.id === result.id ? result : row)); setNotice('建议已取消。'); } })}>取消建议</Button></div></fieldset></section>}
    </Panel>{environment}<Panel title="模型与执行能力"><p>模型调用需要已配置且可用的 Provider。此工作区不会自动启动模型或渲染音视频。</p><Button onClick={onOpenModels}>打开模型控制中心</Button></Panel>
  </div>;
}
