import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { AIEnvironmentSummary } from '../AIEnvironmentSummary';
import { ApiError, type Chapter, type CollaborationContext } from '../api';
import { AppShell, type ScopeLabels, type StudioModule } from '../ui/AppShell';
import { Badge, Button, EmptyState, StatusMessage } from '../ui/primitives';
import { creativeClient, type CreativeHistory } from './client';
import { AssetBrowser, type AssetSelection } from './AssetBrowser';
import { ProjectTimeline } from './ProjectTimeline';
import { CreativeCanvas } from './CreativeCanvas';
import { ProductionTimeline } from './ProductionTimeline';
import { AIDirectorPanel } from './AIDirectorPanel';
import { documentInput, modeForDocument, newDocument, newScene, type CreativeAsset, type CreativeCapabilities, type CreativeDocument, type CreativeInput, type CreativeReferences, type WorkspaceMode } from './types';
import './creative.css';

type Draft = { value: CreativeInput; base?: CreativeDocument; dirty: boolean; blocked?: boolean };
export type CreativeWorkspaceProps = { enabled: boolean; novelId: string; context: CollaborationContext; scope: ScopeLabels; actor: string; chapter?: Chapter; chapterCount: number; manuscriptReady: boolean; novelMain: ReactNode; novelSidebar: ReactNode; novelInspector: ReactNode; novelStatus: ReactNode; onExit: () => void; onModuleChange: (module: StudioModule) => void; onGlobalSearch?: () => void };
/** This route supplies module content to the one protected AppShell. It never owns manuscript writes. */
export function CreativeWorkspace(props: CreativeWorkspaceProps) {
  const identity = JSON.stringify([props.novelId, props.context.sessionToken, props.context.localHostToken, props.context.actor?.id, props.context.scope]);
  if (!props.enabled) return <EmptyState title="V2 创作工作台未启用" detail="实验功能默认关闭，V1 验收模式不加载此工作台。" />;
  return <CreativeWorkspaceSession key={identity} {...props} />;
}
function CreativeWorkspaceSession({ novelId, context, scope, actor, chapter, chapterCount, manuscriptReady, novelMain, novelSidebar, novelInspector, novelStatus, onExit, onModuleChange, onGlobalSearch }: CreativeWorkspaceProps) {
  const client = useMemo(() => creativeClient(novelId, context), [novelId, context.sessionToken, context.localHostToken, context.actor?.id, context.scope?.workspaceId, context.scope?.projectId, context.scope?.storylineId, context.scope?.branchId]);
  const [mode, setMode] = useState<WorkspaceMode>('NOVEL'), [capabilities, setCapabilities] = useState<CreativeCapabilities>(), [documents, setDocuments] = useState<CreativeDocument[]>([]), [drafts, setDrafts] = useState<Partial<Record<WorkspaceMode, Draft>>>({}), [loading, setLoading] = useState(true), [documentsReady, setDocumentsReady] = useState(false), [busy, setBusy] = useState(false), [directorBusy, setDirectorBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [denied, setDenied] = useState(false), [references, setReferences] = useState<CreativeReferences>(), [assets, setAssets] = useState<CreativeAsset[]>(), [assetLoading, setAssetLoading] = useState(false), [assetError, setAssetError] = useState(false), [asset, setAsset] = useState<AssetSelection>(), [sceneId, setSceneId] = useState<string>(), [shotId, setShotId] = useState<string>(), [history, setHistory] = useState<CreativeHistory>(), [restoreVersion, setRestoreVersion] = useState<number>(), [pendingNavigation, setPendingNavigation] = useState<(() => void)>(), [discardChecked, setDiscardChecked] = useState(false), [serverCandidate, setServerCandidate] = useState<CreativeDocument>();
  const revoked = useRef(false);
  const mounted = useRef(true), mutationLock = useRef(false), readEpoch = useRef(0), assetEpoch = useRef(0);
  const currentMode = useRef(mode); currentMode.current = mode;
  const currentDrafts = useRef(drafts); currentDrafts.current = drafts;
  const draft = drafts[mode], dirtyModes = Object.entries(drafts).filter(([, value]) => value?.dirty).map(([key]) => key as WorkspaceMode);
  const canEdit = capabilities?.enabled === true && capabilities.can_mutate === true && !denied && !draft?.blocked;
  const deny = () => { revoked.current = true; readEpoch.current++; assetEpoch.current++; setLoading(false); setAssetLoading(false); setDenied(true); setCapabilities(undefined); setDocumentsReady(false); setDocuments([]); setReferences(undefined); setAssets(undefined); setAsset(undefined); setServerCandidate(undefined); setHistory(undefined); setRestoreVersion(undefined); setNotice(''); setPendingNavigation(undefined); setDiscardChecked(false); setError('当前身份或分支已失去访问权限。内容已锁定；请恢复授权后重新打开工作台。'); };
  const describe = (value: unknown) => value instanceof ApiError ? `${value.message} (${value.problem.code})` : '请求未完成，请检查连接后重试。';
  const read = async (signal?: AbortSignal) => { const ticket = ++readEpoch.current; setLoading(true); try { const caps = await client.capabilities(signal); if (!mounted.current || revoked.current || signal?.aborted || ticket !== readEpoch.current) return; setCapabilities(caps); if (!caps.enabled) { setDocumentsReady(false); setDocuments([]); return; } const rows = await client.list(signal); if (!mounted.current || revoked.current || signal?.aborted || ticket !== readEpoch.current) return; setDocuments(rows.items); setDocumentsReady(true); setError(''); } catch (value) { if (mounted.current && !revoked.current && !signal?.aborted && ticket === readEpoch.current) { setError(describe(value)); if (value instanceof ApiError && [401, 403].includes(value.status)) deny(); } } finally { if (mounted.current && !revoked.current && !signal?.aborted && ticket === readEpoch.current) setLoading(false); } };
  const readAssets = async (signal?: AbortSignal) => { if (revoked.current) return; const ticket = ++assetEpoch.current; setAssetLoading(true); const result = await Promise.allSettled([client.references(signal), client.assets(signal)]); if (!mounted.current || revoked.current || signal?.aborted || ticket !== assetEpoch.current) return; setReferences(result[0].status === 'fulfilled' ? result[0].value : undefined); setAssets(result[1].status === 'fulfilled' ? result[1].value : undefined); setAssetError(result.some(row => row.status === 'rejected')); setAssetLoading(false); };
  useEffect(() => { mounted.current = true; const controller = new AbortController(); void read(controller.signal); return () => { mounted.current = false; controller.abort(); readEpoch.current++; assetEpoch.current++; }; }, [client]);
  useEffect(() => { if (!capabilities?.enabled || denied) return; const controller = new AbortController(); void readAssets(controller.signal); return () => controller.abort(); }, [client, capabilities?.enabled, denied]);
  // A stage chosen during bootstrap must wait for a successful scoped list, not
  // mistake the initial empty array for an empty project. Existing drafts encode
  // user intent (including clean explicit-new drafts) and must never be replaced.
  useEffect(() => {
    if (mode === 'NOVEL' || loading || !documentsReady || !capabilities?.enabled || denied || revoked.current) return;
    setDrafts(current => {
      if (revoked.current || current[mode]) return current;
      const existing = documents.find(row => modeForDocument(row.mode) === mode);
      return { ...current, [mode]: existing ? { value: documentInput(existing), base: existing, dirty: false } : { value: newDocument(mode, manuscriptReady ? chapter?.id : undefined), dirty: false } };
    });
  }, [mode, loading, documentsReady, capabilities?.enabled, denied, documents, manuscriptReady, chapter?.id]);
  useEffect(() => { if (!dirtyModes.length) return; const prevent = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = ''; }; window.addEventListener('beforeunload', prevent); return () => window.removeEventListener('beforeunload', prevent); }, [dirtyModes.length]);
  const setDraft = (next: Draft, target: WorkspaceMode = mode) => setDrafts(current => ({ ...current, [target]: next }));
  const changeMode = (next: WorkspaceMode) => {
    if (busy || directorBusy || denied) return;
    setMode(next); setHistory(undefined); setRestoreVersion(undefined); setServerCandidate(undefined); setSceneId(undefined); setShotId(undefined); setAsset(undefined); setNotice(''); setError('');
  };
  const change = (value: CreativeInput) => { if (!canEdit || busy) return; setDraft({ ...draft, value, dirty: true }); setNotice(''); };
  const navigate = (action: () => void) => { if (busy || directorBusy) return; if (revoked.current) { action(); return; } if (dirtyModes.length) { setPendingNavigation(() => action); setDiscardChecked(false); } else action(); };
  const openDocument = (row: CreativeDocument) => { if (revoked.current) return; const target = modeForDocument(row.mode); if (currentDrafts.current[target]?.dirty) { setNotice(`“${row.title}”已保存在服务端。请先保存或处理${target}中的未保存草稿，再打开。`); return; } setMode(target); setDraft({ value: documentInput(row), base: row, dirty: false }, target); setHistory(undefined); setRestoreVersion(undefined); setServerCandidate(undefined); setSceneId(undefined); setShotId(undefined); setError(''); };
  const save = async () => {
    if (!draft || !canEdit || mutationLock.current || !draft.dirty || !draft.value.title.trim()) return;
    const originMode = mode, originDraft = draft; mutationLock.current = true; setBusy(true); setError(''); setNotice('');
    try { const row = originDraft.base ? await client.update(originDraft.base.id, originDraft.base.version, originDraft.value) : await client.create(originDraft.value); if (!mounted.current || revoked.current) return; setDocuments(rows => [...rows.filter(item => item.id !== row.id), row]); setDraft({ value: documentInput(row), base: row, dirty: false }, originMode); setNotice(`已保存“${row.title}” · v${row.version}`); }
    catch (value) { if (!mounted.current || revoked.current) return; setError(describe(value)); const uncertain = !(value instanceof ApiError) || value.status >= 500 || value.status === 409; if (uncertain) { setDraft({ ...originDraft, blocked: true }, originMode); setNotice('草稿已保留。版本冲突或写入回执不确定，继续写入前需核对服务端。'); } if (value instanceof ApiError && [401, 403].includes(value.status)) deny(); }
    finally { mutationLock.current = false; if (mounted.current) setBusy(false); }
  };
  const checkServer = async () => { if (!draft || busy) return; setBusy(true); setError(''); try { if (draft.base) { const row = await client.get(draft.base.id); if (mounted.current && !revoked.current) { setServerCandidate(row); setDiscardChecked(false); } } else { await read(); if (mounted.current && !revoked.current) setNotice('已重新读取文档列表。请核对是否已经创建；导出本地草稿后再放弃此草稿，避免重复创建。'); } } catch (value) { if (mounted.current && !revoked.current) { setError(describe(value)); if (value instanceof ApiError && [401, 403].includes(value.status)) deny(); } } finally { if (mounted.current) setBusy(false); } };
  const download = (value: unknown, name: string) => { const url = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], { type: 'application/json' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); };
  const exportDocument = async () => { if (!draft?.base || busy) return; try { const result = await client.export(draft.base.id); if (mounted.current && !revoked.current) download(result, `creative-${draft.base.id}.json`); } catch (value) { if (mounted.current && !revoked.current) { setError(describe(value)); if (value instanceof ApiError && [401, 403].includes(value.status)) deny(); } } };
  const readHistory = async () => { if (!draft?.base || busy) return; const id = draft.base.id; try { const result = await client.history(id); if (mounted.current && !revoked.current && currentMode.current === mode && currentDrafts.current[mode]?.base?.id === id) setHistory(result); } catch (value) { if (mounted.current && !revoked.current) { setError(describe(value)); if (value instanceof ApiError && [401, 403].includes(value.status)) deny(); } } };
  const derive = async () => {
    if (!draft?.base || draft.dirty || !canEdit || mutationLock.current) return;
    const target = draft.value.mode === 'STORYBOARD' ? 'PRODUCTION' : 'STORYBOARD';
    mutationLock.current = true; setBusy(true); setError('');
    try { const row = await client.derive(draft.base, target); if (mounted.current && !revoked.current) { setDocuments(rows => [...rows.filter(item => item.id !== row.id), row]); openDocument(row); setNotice(`已从当前已保存版本建立“${row.title}”。新文档保留来源绑定；没有调用模型或生成媒体。`); } }
    catch (value) { if (mounted.current && !revoked.current) { setError(describe(value)); if (!(value instanceof ApiError) || value.status >= 500 || value.status === 409) { setDraft({ ...draft, blocked: true }); setNotice('派生操作需核对服务端结果，请勿重复建立。'); } if (value instanceof ApiError && [401, 403].includes(value.status)) deny(); } }
    finally { mutationLock.current = false; if (mounted.current) setBusy(false); }
  };
  const scaffold = () => {
    if (!chapter || !manuscriptReady || mode !== 'SCREENPLAY' || !draft || draft.base || draft.value.scenes.length || chapter.content.length > 32000 || !canEdit) return;
    const scene = { ...newScene(1, chapter.id), heading: chapter.title, action: chapter.content };
    setDraft({ value: { ...draft.value, title: draft.value.title || `${chapter.title.slice(0, 220)} · 剧本底稿`, source_chapter_ids: [chapter.id], source_independent: false, scenes: [scene] }, dirty: true });
    setSceneId(scene.id); setNotice('已复制当前已保存章节到场景动作底稿。尚未进行剧本改编或调用模型，请自行拆分、编辑并保存。');
  };
  const restore = async () => {
    if (!draft?.base || draft.dirty || !restoreVersion || !canEdit || mutationLock.current) return;
    mutationLock.current = true; setBusy(true); setError('');
    try { const row = await client.restore(draft.base, restoreVersion); if (mounted.current && !revoked.current) { setDocuments(rows => rows.map(item => item.id === row.id ? row : item)); setDraft({ value: documentInput(row), base: row, dirty: false }); setHistory(undefined); setRestoreVersion(undefined); setNotice(`已将所选历史内容恢复为新版本 v${row.version}，其他历史版本仍保留。`); } }
    catch (value) { if (mounted.current && !revoked.current) { setError(describe(value)); if (!(value instanceof ApiError) || value.status >= 500 || value.status === 409) setDraft({ ...draft, blocked: true }); if (value instanceof ApiError && [401, 403].includes(value.status)) deny(); } }
    finally { mutationLock.current = false; if (mounted.current) setBusy(false); }
  };
  const newDraft = () => { if (mode !== 'NOVEL' && !draft?.dirty && canEdit) { setDraft({ value: newDocument(mode, manuscriptReady ? chapter?.id : undefined), dirty: false }); setHistory(undefined); setRestoreVersion(undefined); setServerCandidate(undefined); } };
  const content = <div className="creative-workspace"><ProjectTimeline mode={mode} onChange={changeMode} documents={denied ? [] : documents} chapterCount={chapterCount} dirtyModes={dirtyModes} />
    {pendingNavigation && <section className="creative-navigation-confirm" role="alert"><p>离开会关闭未保存的创作草稿。可以取消离开，先保存或导出。</p><Button onClick={() => { for (const [key, row] of Object.entries(drafts)) if (row?.dirty) download(row.value, `creative-unsaved-${key}.json`); }}>导出全部未保存草稿</Button><label><input type="checkbox" checked={discardChecked} onChange={e => setDiscardChecked(e.target.checked)} />确认放弃未保存草稿并离开</label><Button disabled={!discardChecked} onClick={() => { const action = pendingNavigation; setPendingNavigation(undefined); action(); }}>确认离开</Button><Button onClick={() => setPendingNavigation(undefined)}>继续编辑</Button></section>}
    {error && <StatusMessage tone="error">{error}</StatusMessage>}{notice && <StatusMessage tone="info">{notice}</StatusMessage>}
    {loading && <StatusMessage>正在核对创作文档与权限…</StatusMessage>}{!loading && !denied && (!capabilities || (capabilities.enabled && !documentsReady)) && <Button onClick={() => void read()}>重试读取工作台</Button>}
    {capabilities && !capabilities.enabled && <EmptyState title="服务端尚未启用创作 V2" detail="请由管理员启用 narrative_production_v2。当前工作台不会写入创作文档。" />}
    {denied ? <EmptyState title="访问已锁定" detail="当前身份不可继续查看或写入创作文档。原正文的权限和草稿恢复仍由小说工作区管理。" /> : <><div id="creative-canvas-NOVEL" role="tabpanel" aria-labelledby="creative-stage-NOVEL" hidden={mode !== 'NOVEL'}>{novelMain}</div>{mode !== 'NOVEL' && <section id={`creative-canvas-${mode}`} role="tabpanel" aria-labelledby={`creative-stage-${mode}`}>
      {draft?.blocked && <section className="creative-conflict" role="alert"><strong>需要核对版本 · 本地草稿仍保留</strong><p>不会自动覆盖服务端，也不会自动重试不确定的写入。</p><Button disabled={busy} onClick={() => void checkServer()}>核对服务端版本</Button><Button onClick={() => download(draft.value, 'creative-unsaved-draft.json')}>导出保留草稿</Button>{!draft.base && <><label><input type="checkbox" checked={discardChecked} onChange={e => setDiscardChecked(e.target.checked)} />已核对文档列表，放弃本地未保存草稿</label><Button disabled={!discardChecked || busy} onClick={() => { setDraft({ value: newDocument(mode, manuscriptReady ? chapter?.id : undefined), dirty: false }); setNotice(''); setError(''); }}>放弃此草稿</Button></>}</section>}
      {serverCandidate && <section className="creative-conflict" aria-label="服务端版本核对"><h3>服务端 v{serverCandidate.version} · {serverCandidate.title}</h3><p>{serverCandidate.scenes.length} 场景 · {serverCandidate.shots.length} 镜头</p><details><summary>查看服务端完整内容</summary><pre>{JSON.stringify(documentInput(serverCandidate), null, 2)}</pre></details><label><input type="checkbox" checked={discardChecked} onChange={e => setDiscardChecked(e.target.checked)} />已核对并确认用服务端版本替换当前本地草稿</label><Button disabled={!discardChecked} onClick={() => { setDraft({ value: documentInput(serverCandidate), base: serverCandidate, dirty: false }); setServerCandidate(undefined); setHistory(undefined); setRestoreVersion(undefined); setError(''); setNotice('已采用核对后的服务端版本。'); }}>使用核对后的服务端版本</Button><Button onClick={() => setServerCandidate(undefined)}>保留本地草稿</Button></section>}
      {draft && <CreativeCanvas draft={draft.value} version={draft.base?.version} dirty={draft.dirty} canEdit={canEdit && capabilities?.modes.includes(draft.value.mode) === true} busy={busy} selectedSceneId={sceneId} selectedShotId={shotId} onScene={setSceneId} onShot={setShotId} onChange={change} onSave={() => void save()} onNew={newDraft} onExport={draft.base ? () => void exportDocument() : undefined} onHistory={draft.base ? () => void readHistory() : undefined} onDerive={draft.base && ['SCREENPLAY', 'DIRECTOR', 'STORYBOARD'].includes(draft.value.mode) ? () => void derive() : undefined} onScaffold={mode === 'SCREENPLAY' && !draft.base && !draft.value.scenes.length && manuscriptReady && chapter && chapter.content.length <= 32000 ? scaffold : undefined} sourceChapterTitle={draft.value.source_chapter_ids.includes(chapter?.id || '') ? chapter?.title : undefined} />}
      {history && <section className="creative-history" aria-label="创作文档历史"><h3>版本历史 · 当前 v{history.current_version}</h3><Button onClick={() => setHistory(undefined)}>关闭历史</Button>{history.items.map(row => <details key={row.version}><summary>v{row.version} · {row.title}</summary><pre>{JSON.stringify(documentInput(row), null, 2)}</pre><label className="creative-review-check"><input type="checkbox" disabled={busy || !canEdit || !!draft?.dirty || row.version === history.current_version} checked={restoreVersion === row.version} onChange={event => setRestoreVersion(event.target.checked ? row.version : undefined)} />已核对 v{row.version} 的完整内容；恢复会新建当前版本</label><Button disabled={busy || !canEdit || !!draft?.dirty || restoreVersion !== row.version} onClick={() => void restore()}>恢复 v{row.version} 为新版本</Button></details>)}</section>}
    </section>}<ProductionTimeline draft={mode === 'NOVEL' ? undefined : draft?.value} editable={canEdit && !busy} onChange={change} onShot={setShotId} /></>}
  </div>;
  return <AppShell module="NOVEL" onModuleChange={target => navigate(() => onModuleChange(target))} scope={scope} actor={actor} onGlobalSearch={onGlobalSearch} sidebar={<AssetBrowser mode={mode} documents={documents} draft={denied ? undefined : draft?.value} references={references} assets={assets} loading={assetLoading} error={assetError} selectedDocumentId={draft?.base?.id} onDocument={openDocument} onSelect={selected => { setAsset(selected); if (selected.kind === 'Scene') setSceneId(selected.id); if (selected.kind === 'Shot') setShotId(selected.id); }} onRetry={() => void readAssets()} novelSidebar={novelSidebar} onExit={() => navigate(onExit)} />} main={content} inspector={<><div hidden={mode !== 'NOVEL'}>{novelInspector}</div><div hidden={mode === 'NOVEL'}>{denied || !capabilities?.enabled ? <EmptyState title="导演协作暂不可用" detail="需要服务端启用 V2 并授权当前身份。" /> : <AIDirectorPanel client={client} documents={documents} canMutate={capabilities.can_mutate && !busy} onBusyChange={setDirectorBusy} onDenied={deny} asset={asset} environment={<AIEnvironmentSummary enabled={true} onOpenModels={() => navigate(() => onModuleChange('CONTROL'))} />} onOpenModels={() => navigate(() => onModuleChange('CONTROL'))} onDocument={row => { if (revoked.current) return; setDocuments(rows => [...rows.filter(item => item.id !== row.id), row]); openDocument(row); }} />}</div></>} status={<>{novelStatus}<span> · V2 {mode} · {dirtyModes.length ? `${dirtyModes.length} 份草稿未保存（仅本页内存）` : '无未保存创作草稿'}</span>{!capabilities?.can_mutate && <Badge tone="warning">{capabilities ? '只读' : '权限待核对'}</Badge>}</>} />;
}
