import type { ReactNode } from 'react';
import { Plus, Save, FilePlus, Download, History, ArrowLeft, ArrowRight } from 'lucide-react';
import { Badge, Button, EmptyState } from '../ui/primitives';
import { creativeId, newScene, newShot, type CreativeInput, type CreativeScene, type CreativeShot, type DirectorSceneNote } from './types';
export function CreativeField({ label, children }: { label: string; children: ReactNode }) { return <label className="creative-field"><span>{label}</span>{children}</label>; }
export function DirectorFields({ value, onChange, prefix = '' }: { value: DirectorSceneNote; onChange: (value: DirectorSceneNote) => void; prefix?: string }) {
  const update = (patch: Partial<DirectorSceneNote>) => onChange({ ...value, ...patch });
  return <div className="creative-form-grid"><CreativeField label={`${prefix}导演意图`}><textarea maxLength={8000} value={value.note} onChange={e => update({ note: e.target.value })} /></CreativeField><CreativeField label={`${prefix}场面调度`}><textarea maxLength={4000} value={value.blocking} onChange={e => update({ blocking: e.target.value })} /></CreativeField><CreativeField label={`${prefix}景别`}><input maxLength={80} value={value.shot_size} onChange={e => update({ shot_size: e.target.value })} /></CreativeField><CreativeField label={`${prefix}机位角度`}><input maxLength={80} value={value.camera_angle} onChange={e => update({ camera_angle: e.target.value })} /></CreativeField><CreativeField label={`${prefix}运镜`}><input maxLength={80} value={value.camera_motion} onChange={e => update({ camera_motion: e.target.value })} /></CreativeField><CreativeField label={`${prefix}时长（秒）`}><input type="number" min={1} max={600} value={value.duration_seconds} onChange={e => update({ duration_seconds: Number(e.target.value) })} /></CreativeField><CreativeField label={`${prefix}情绪`}><textarea maxLength={2000} value={value.emotion} onChange={e => update({ emotion: e.target.value })} /></CreativeField><CreativeField label={`${prefix}节奏`}><textarea maxLength={2000} value={value.pacing} onChange={e => update({ pacing: e.target.value })} /></CreativeField><CreativeField label={`${prefix}表演指导`}><textarea maxLength={4000} value={value.performance} onChange={e => update({ performance: e.target.value })} /></CreativeField></div>;
}
export function CreativeCanvas({ draft, version, dirty, canEdit, busy, selectedSceneId, selectedShotId, onScene, onShot, onChange, onSave, onNew, onExport, onHistory, onDerive, onScaffold, sourceChapterTitle }: { draft: CreativeInput; version?: number; dirty: boolean; canEdit: boolean; busy: boolean; selectedSceneId?: string; selectedShotId?: string; onScene: (id: string) => void; onShot: (id: string) => void; onChange: (draft: CreativeInput) => void; onSave: () => void; onNew: () => void; onExport?: () => void; onHistory?: () => void; onDerive?: () => void; onScaffold?: () => void; sourceChapterTitle?: string }) {
  const scene = draft.scenes.find(row => row.id === selectedSceneId) || draft.scenes[0];
  const shot = draft.shots.find(row => row.id === selectedShotId) || draft.shots[0];
  const update = (patch: Partial<CreativeInput>) => onChange({ ...draft, ...patch });
  const updateScene = (next: CreativeScene) => update({ scenes: draft.scenes.map(row => row.id === next.id ? next : row) });
  const updateShot = (next: CreativeShot) => update({ shots: draft.shots.map(row => row.id === next.id ? next : row) });
  const addScene = () => { const row = newScene(Math.max(0, ...draft.scenes.map(item => item.sequence)) + 1, draft.source_chapter_ids[0]); update({ scenes: [...draft.scenes, row] }); onScene(row.id); };
  const addShot = () => { if (!scene) return; const row = newShot(Math.max(0, ...draft.shots.map(item => item.number)) + 1, scene.id); update({ shots: [...draft.shots, row] }); onShot(row.id); };
  const moveShot = (index: number, delta: number) => { const rows = [...draft.shots]; [rows[index], rows[index + delta]] = [rows[index + delta], rows[index]]; update({ shots: rows.map((row, i) => ({ ...row, number: i + 1 })) }); };
  const directing = draft.mode === 'DIRECTOR', screenplay = draft.mode === 'SCREENPLAY';
  const notes = draft.director_notes.filter(row => row.scene_id === scene?.id);
  const addNote = () => { if (!scene) return; update({ director_notes: [...draft.director_notes, { id: creativeId(), number: Math.max(0, ...draft.director_notes.map(row => row.number)) + 1, scene_id: scene.id, note: '', shot_size: 'MEDIUM', camera_angle: 'EYE_LEVEL', camera_motion: 'STATIC', duration_seconds: 5, emotion: '', pacing: '', performance: '', blocking: '' }] }); };
  return <section className="creative-canvas" aria-label="创作画布"><header className="creative-document-toolbar"><div><span className="creative-eyebrow">Creative Canvas</span><h2>{draft.title || '未命名创作文档'}</h2><Badge tone={dirty ? 'warning' : 'neutral'}>{dirty ? '未保存' : version ? `已保存 · v${version}` : '新草稿'}</Badge></div><div className="creative-actions"><Button onClick={onNew} disabled={busy || dirty || !canEdit}><FilePlus aria-hidden="true" />新建文档</Button><Button variant="primary" onClick={onSave} disabled={busy || !canEdit || !dirty || !draft.title.trim() || (!draft.source_independent && !draft.source_chapter_ids.length && !version)}><Save aria-hidden="true" />{busy ? '保存中…' : '保存草稿'}</Button>{onDerive && <Button disabled={busy || dirty || !canEdit} onClick={onDerive}>{draft.mode === 'STORYBOARD' ? '建立制作计划' : '建立分镜草稿'}</Button>}{onExport && <Button onClick={onExport} disabled={busy || dirty}><Download aria-hidden="true" />导出</Button>}{onHistory && <Button onClick={onHistory} disabled={busy}><History aria-hidden="true" />历史</Button>}</div></header>
    <fieldset className="creative-document-fields" disabled={!canEdit || busy}><legend className="creative-sr-only">创作文档内容</legend><CreativeField label="文档标题"><input maxLength={240} required value={draft.title} onChange={e => update({ title: e.target.value })} /></CreativeField><div className="creative-source"><span>来源：{draft.source_chapter_ids.length ? `${sourceChapterTitle || draft.source_chapter_ids.join('、')}（保存时核对版本）` : draft.source_independent ? '独立创作' : version ? '服务端绑定的创作文档' : '请选择独立创作，或从已保存的章节开始'}</span>{!version && !draft.source_chapter_ids.length && <label><input type="checkbox" checked={draft.source_independent} onChange={e => update({ source_independent: e.target.checked })} />这是独立创作</label>}</div>
      <div className="creative-actions">{onScaffold && <Button onClick={onScaffold}>从当前已保存章节建立场景底稿</Button>}<Button onClick={addScene} disabled={draft.scenes.length >= 200}><Plus aria-hidden="true" />添加场景</Button>{!screenplay && !directing && <Button onClick={addShot} disabled={!scene || draft.shots.length >= 200}><Plus aria-hidden="true" />添加镜头</Button>}{directing && <Button onClick={addNote} disabled={!scene || draft.director_notes.length >= 200}><Plus aria-hidden="true" />添加导演调度</Button>}</div>
      <div className="creative-scene-strip" aria-label="场景选择">{draft.scenes.map(row => <button type="button" key={row.id} aria-pressed={scene?.id === row.id} onClick={() => onScene(row.id)}><small>SCENE {String(row.sequence).padStart(2, '0')}</small><strong>{row.heading}</strong></button>)}</div>
      {!scene && <EmptyState title="从一个场景开始" detail="添加场景后，可填写地点、动作、对白，再安排导演调度与镜头。" />}
      {scene && <section className="creative-scene-editor" aria-label="当前场景"><div className="creative-form-grid"><CreativeField label="场景标题"><input maxLength={500} value={scene.heading} onChange={e => updateScene({ ...scene, heading: e.target.value })} /></CreativeField><CreativeField label="场景地点"><input maxLength={1000} value={scene.location} onChange={e => updateScene({ ...scene, location: e.target.value })} /></CreativeField><CreativeField label="场景时间"><input maxLength={1000} value={scene.time} onChange={e => updateScene({ ...scene, time: e.target.value })} /></CreativeField><CreativeField label="场景情绪"><input maxLength={4000} value={scene.emotion} onChange={e => updateScene({ ...scene, emotion: e.target.value })} /></CreativeField></div><CreativeField label="动作与叙事"><textarea className="creative-action-text" maxLength={32000} value={scene.action} onChange={e => updateScene({ ...scene, action: e.target.value })} /></CreativeField>
        {(screenplay || directing) && <section aria-label="场景对白"><h3>对白</h3>{scene.dialogue.map((line, index) => <div className="creative-dialogue" key={index}><CreativeField label={`对白 ${index + 1} 人物`}><input maxLength={240} value={line.speaker} onChange={e => updateScene({ ...scene, dialogue: scene.dialogue.map((row, i) => i === index ? { ...row, speaker: e.target.value } : row) })} /></CreativeField><CreativeField label={`对白 ${index + 1} 内容`}><textarea maxLength={16000} value={line.text} onChange={e => updateScene({ ...scene, dialogue: scene.dialogue.map((row, i) => i === index ? { ...row, text: e.target.value } : row) })} /></CreativeField><CreativeField label={`对白 ${index + 1} 语气`}><input maxLength={2000} value={line.delivery} onChange={e => updateScene({ ...scene, dialogue: scene.dialogue.map((row, i) => i === index ? { ...row, delivery: e.target.value } : row) })} /></CreativeField><Button variant="ghost" onClick={() => updateScene({ ...scene, dialogue: scene.dialogue.filter((_, i) => i !== index) })}>移除对白 {index + 1}</Button></div>)}<Button onClick={() => updateScene({ ...scene, dialogue: [...scene.dialogue, { speaker: '', text: '', delivery: '' }] })} disabled={scene.dialogue.length >= 200}>添加对白</Button></section>}
        {directing && <section aria-label="导演场面调度">{notes.map(note => <article className="creative-director-note" key={note.id}><h3>调度 {note.number}</h3><DirectorFields value={note} onChange={next => update({ director_notes: draft.director_notes.map(row => row.id === next.id ? next : row) })} /></article>)}{!notes.length && <p>当前场景尚未安排导演调度。手动添加，或在右侧从已保存剧本准备待审建议。</p>}</section>}
      </section>}
      {!screenplay && !directing && <section aria-label="分镜画布"><div className="creative-shot-grid">{draft.shots.map((row, index) => <article key={row.id} className="creative-shot-entry"><button type="button" className="creative-shot-card" aria-pressed={shot?.id === row.id} onClick={() => { onShot(row.id); onScene(row.scene_id); }}><span><strong>SHOT {String(row.number).padStart(2, '0')}</strong><Badge>{row.duration_seconds}s</Badge></span><p>{row.frame_prompt || '填写画面描述'}</p><small>{row.shot_size} · {row.camera_motion}</small></button><div className="creative-actions"><Button aria-label={`前移镜头 ${row.number}`} disabled={index === 0} onClick={() => moveShot(index, -1)}><ArrowLeft aria-hidden="true" />前移</Button><Button aria-label={`后移镜头 ${row.number}`} disabled={index === draft.shots.length - 1} onClick={() => moveShot(index, 1)}><ArrowRight aria-hidden="true" />后移</Button></div></article>)}</div>{shot && <ShotEditor shot={shot} scenes={draft.scenes} onChange={updateShot} />}{!draft.shots.length && scene && <p>没有分镜。添加镜头以编辑景别、镜头参数、光线和声音。</p>}</section>}
    </fieldset>
  </section>;
}
function ShotEditor({ shot, scenes, onChange }: { shot: CreativeShot; scenes: CreativeScene[]; onChange: (shot: CreativeShot) => void }) {
  const update = (patch: Partial<CreativeShot>) => onChange({ ...shot, ...patch });
  const fields: { key: keyof Pick<CreativeShot, 'shot_size' | 'camera_angle' | 'camera_motion' | 'lens' | 'lighting' | 'environment' | 'composition' | 'color' | 'sound'>; label: string; max: number }[] = [{ key: 'shot_size', label: '镜头景别', max: 80 }, { key: 'camera_angle', label: '镜头角度', max: 80 }, { key: 'camera_motion', label: '镜头运动', max: 80 }, { key: 'lens', label: '镜头与焦距', max: 1000 }, { key: 'lighting', label: '光线设计', max: 4000 }, { key: 'environment', label: '环境设计', max: 4000 }, { key: 'composition', label: '构图', max: 4000 }, { key: 'color', label: '色彩', max: 2000 }, { key: 'sound', label: '声音设计', max: 4000 }];
  return <section className="creative-shot-editor" aria-label={`镜头 ${shot.number} 参数`}><h3>镜头 {shot.number} · 参数</h3><div className="creative-form-grid"><CreativeField label="镜头所属场景"><select value={shot.scene_id} onChange={e => update({ scene_id: e.target.value })}>{scenes.map(scene => <option value={scene.id} key={scene.id}>{scene.heading}</option>)}</select></CreativeField><CreativeField label="镜头时长（秒）"><input type="number" min={1} max={600} value={shot.duration_seconds} onChange={e => update({ duration_seconds: Number(e.target.value) })} /></CreativeField>{fields.map(({ key, label, max }) => <CreativeField key={key} label={label}><input maxLength={max} value={shot[key] || ''} onChange={e => update({ [key]: e.target.value })} /></CreativeField>)}</div><CreativeField label="画面描述"><textarea maxLength={16000} value={shot.frame_prompt} onChange={e => update({ frame_prompt: e.target.value })} /></CreativeField><CreativeField label="镜头动作"><textarea maxLength={16000} value={shot.action} onChange={e => update({ action: e.target.value })} /></CreativeField></section>;
}
