import { ArrowLeft, ArrowRight, Plus } from 'lucide-react';
import { Badge, Button, EmptyState } from '../ui/primitives';
import { CreativeField } from './CreativeCanvas';
import type { CreativeInput, VideoPlan } from './types';
export function ProductionTimeline({ draft, editable, onChange, onShot }: { draft?: CreativeInput; editable: boolean; onChange: (draft: CreativeInput) => void; onShot: (id: string) => void }) {
  const plan = draft?.video_plan;
  const segments = plan?.segments || draft?.shots.map(shot => ({ shot_id: shot.id, duration_seconds: shot.duration_seconds, note: '' })) || [];
  const total = segments.reduce((sum, segment) => sum + segment.duration_seconds, 0);
  const update = (patch: Partial<VideoPlan>) => { if (draft && plan && editable) onChange({ ...draft, video_plan: { ...plan, ...patch } }); };
  const move = (index: number, delta: number) => { const ordered = [...segments]; [ordered[index], ordered[index + delta]] = [ordered[index + delta], ordered[index]]; update({ segments: ordered }); };
  let offset = 0;
  return <section className="creative-production-timeline" aria-label="制作时间轴"><header><div><span className="creative-eyebrow">Production Timeline</span><h2>制作序列</h2></div><Badge>{segments.length} 段 · {total}s</Badge><small>结构化计划 · 尚未渲染媒体</small></header>
    {!!plan && <fieldset disabled={!editable} className="creative-timeline-settings"><legend className="creative-sr-only">制作设置</legend><CreativeField label="帧率"><input type="number" min={1} max={120} value={plan.frame_rate} onChange={e => update({ frame_rate: Number(e.target.value) })} /></CreativeField><CreativeField label="画面宽度"><input type="number" min={16} max={7680} value={plan.width} onChange={e => update({ width: Number(e.target.value) })} /></CreativeField><CreativeField label="画面高度"><input type="number" min={16} max={7680} value={plan.height} onChange={e => update({ height: Number(e.target.value) })} /></CreativeField><CreativeField label="添加镜头到序列"><select value="" disabled={!draft?.shots.length || segments.length >= 200} onChange={e => { const shot = draft?.shots.find(row => row.id === e.target.value); if (shot) update({ segments: [...segments, { shot_id: shot.id, duration_seconds: shot.duration_seconds, note: '' }] }); }}><option value="">选择已编排的镜头</option>{draft?.shots.map(shot => <option key={shot.id} value={shot.id}>镜头 {shot.number} · {shot.duration_seconds}s</option>)}</select></CreativeField>{!segments.length && !!draft?.shots.length && <Button onClick={() => update({ segments: draft.shots.map(shot => ({ shot_id: shot.id, duration_seconds: shot.duration_seconds, note: '' })) })}><Plus aria-hidden="true" />按镜头顺序编排</Button>}</fieldset>}
    <ol className="creative-timeline-track">{segments.map((segment, index) => { const start = offset; offset += segment.duration_seconds; const shot = draft?.shots.find(row => row.id === segment.shot_id); return <li key={`${segment.shot_id}:${index}`} style={{ flexGrow: segment.duration_seconds }}><button className="creative-timeline-clip" onClick={() => onShot(segment.shot_id)}><small>{start}s → {offset}s</small><strong>镜头 {shot?.number || '?'}</strong><span>{segment.duration_seconds}s</span></button>{plan && <div className="creative-clip-controls"><Button aria-label={`前移第 ${index + 1} 段`} disabled={!editable || index === 0} onClick={() => move(index, -1)}><ArrowLeft aria-hidden="true" /></Button><Button aria-label={`后移第 ${index + 1} 段`} disabled={!editable || index === segments.length - 1} onClick={() => move(index, 1)}><ArrowRight aria-hidden="true" /></Button><Button disabled={!editable} onClick={() => update({ segments: segments.filter((_, i) => i !== index) })}>移除第 {index + 1} 段</Button></div>}{plan && <CreativeField label={`第 ${index + 1} 段时长`}><input disabled={!editable} type="number" min={1} max={600} value={segment.duration_seconds} onChange={e => update({ segments: segments.map((row, i) => i === index ? { ...row, duration_seconds: Number(e.target.value) } : row) })} /></CreativeField>}</li>; })}</ol>
    {!segments.length && <EmptyState title="尚无制作片段" detail={plan ? '在画布添加镜头，再选择镜头加入序列。编排不会调用媒体生成或剪辑服务。' : '分镜的真实时长会显示在这里；在制作模式中可建立可编辑的剪辑序列。'} />}
    {plan && <CreativeField label="制作备注"><textarea disabled={!editable} maxLength={8000} value={plan.notes} onChange={e => update({ notes: e.target.value })} /></CreativeField>}
  </section>;
}
