import {useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {api} from '../api';
import {Badge,Button,EmptyState,Panel} from '../ui/primitives';

const targets=[['COMMERCIAL','商业小说'],['LITERARY','文学小说'],['SCREEN','影视版本'],['CUSTOM','自定义风格']] as const;

function BlueprintEditor({item,novelId,branchId,onSaved}:{item:any;novelId:string;branchId?:string;onSaved:()=>void}){
  const [draft,setDraft]=useState(()=>structuredClone(item.blueprint));const save=useMutation({mutationFn:()=>api.updateAdaptationBlueprint(novelId,item.id,draft,branchId),onSuccess:onSaved});
  return <section className="novel-draft-review"><p className="novel-help">蓝图修订 v{item.blueprint_revision||1}</p><label>改编重点<textarea value={draft.focus} onChange={event=>setDraft({...draft,focus:event.target.value})}/></label><label>节奏策略<textarea value={draft.pacing} onChange={event=>setDraft({...draft,pacing:event.target.value})}/></label><label>输出格式<input value={draft.format} onChange={event=>setDraft({...draft,format:event.target.value})}/></label><label>约束（每行一条）<textarea value={draft.constraints.join('\n')} onChange={event=>setDraft({...draft,constraints:event.target.value.split('\n')})}/></label><ol>{draft.chapter_map.map((mapping:any,index:number)=><li key={mapping.source_chapter_id}><strong>{mapping.source_title}</strong><label>目标单元<input value={mapping.unit} onChange={event=>{const chapter_map=[...draft.chapter_map];chapter_map[index]={...mapping,unit:event.target.value};setDraft({...draft,chapter_map})}}/></label><label>改编动作<textarea value={mapping.action} onChange={event=>{const chapter_map=[...draft.chapter_map];chapter_map[index]={...mapping,action:event.target.value};setDraft({...draft,chapter_map})}}/></label></li>)}</ol><Button disabled={save.isPending} onClick={()=>save.mutate()}>{save.isPending?'正在保存…':'保存蓝图修订'}</Button></section>;
}

export function AdaptationPanel({novelId,branchId}:{novelId?:string;branchId?:string}){
  const qc=useQueryClient();const [target,setTarget]=useState('COMMERCIAL'),[title,setTitle]=useState(''),[instruction,setInstruction]=useState(''),[draftMode,setDraftMode]=useState<'deterministic'|'model'>('deterministic'),[modelRoute,setModelRoute]=useState('');
  const refresh=()=>void qc.invalidateQueries({queryKey:['adaptation-proposals',novelId]});
  const models=useQuery({queryKey:['text-models'],queryFn:api.textModels,retry:false});const selectedModel=models.data?.find(model=>`${model.provider_id}:${model.model_id}`===modelRoute);
  const proposals=useQuery({queryKey:['adaptation-proposals',novelId,branchId],queryFn:()=>api.adaptationProposals(novelId!,branchId),enabled:!!novelId});
  const create=useMutation({mutationFn:()=>api.createAdaptationProposal(novelId!,{target,title,instruction},branchId),onSuccess:async()=>{setTitle('');setInstruction('');await qc.invalidateQueries({queryKey:['adaptation-proposals',novelId]})}});
  const approve=useMutation({mutationFn:(id:string)=>api.approveAdaptationProposal(novelId!,id,branchId),onSuccess:()=>qc.invalidateQueries({queryKey:['adaptation-proposals',novelId]})});
  const materialize=useMutation({mutationFn:(id:string)=>api.materializeAdaptation(novelId!,id,branchId),onSuccess:()=>qc.invalidateQueries({queryKey:['adaptation-proposals',novelId]})});
  const generateDraft=useMutation({mutationFn:(value:{proposalId:string;taskId:string})=>api.generateAdaptationDraft(novelId!,value.proposalId,value.taskId,{mode:draftMode,provider_id:selectedModel?.provider_id,model_id:selectedModel?.model_id},branchId),onSuccess:refresh});
  const reviewDraft=useMutation({mutationFn:(value:{proposalId:string;taskId:string;decision:'ACCEPTED'|'REJECTED'})=>api.reviewAdaptationDraft(novelId!,value.proposalId,value.taskId,value.decision,branchId),onSuccess:refresh});
  const applyDraft=useMutation({mutationFn:(value:{proposalId:string;taskId:string})=>api.applyAdaptationDraft(novelId!,value.proposalId,value.taskId,branchId),onSuccess:refresh});
  return <Panel title="智能改编">
    {!novelId?<EmptyState title="尚未打开小说" detail="打开一部小说后创建改编方案。"/>:<section className="novel-draft-review">
      <label>改编目标<select aria-label="改编目标" value={target} onChange={event=>setTarget(event.target.value)}>{targets.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
      <label>方案名称<input aria-label="改编方案名称" value={title} maxLength={200} onChange={event=>setTitle(event.target.value)} placeholder="留空则自动命名"/></label>
      <label>改编要求<textarea aria-label="改编要求" value={instruction} onChange={event=>setInstruction(event.target.value)} placeholder="例如：压缩为六集，保留主要人物关系"/></label>
      <label>草稿生成<select aria-label="改编草稿生成模式" value={draftMode} onChange={event=>setDraftMode(event.target.value as 'deterministic'|'model')}><option value="deterministic">本地准备稿</option><option value="model">真实模型改写</option></select></label>
      {draftMode==='model'&&<label>文本模型<select aria-label="改编文本模型" value={modelRoute} onChange={event=>setModelRoute(event.target.value)}><option value="">选择 Provider / 模型</option>{models.data?.filter(model=>model.available).map(model=><option key={`${model.provider_id}:${model.model_id}`} value={`${model.provider_id}:${model.model_id}`}>{model.display_name}</option>)}</select></label>}
      <Button variant="primary" disabled={create.isPending} onClick={()=>create.mutate()}>{create.isPending?'正在创建…':'创建改编方案'}</Button>
      {!proposals.data?.length&&<EmptyState title="暂无改编方案" detail="原作章节不会因创建方案而被修改。"/>}
      <ul className="novel-record-list">{proposals.data?.map(item=><li key={item.id}><article><header><strong>{item.title}</strong><Badge tone={item.status==='MATERIALIZED'?'success':'warning'}>{item.status}</Badge></header><p className="novel-help">{targets.find(([value])=>value===item.target)?.[1]||item.target} · 锁定 {item.source_chapter_count} 章</p><p>{item.instruction||'未填写额外要求'}</p>{item.status==='DRAFT'&&item.blueprint?<details><summary>编辑改编蓝图</summary><BlueprintEditor item={item} novelId={novelId!} branchId={branchId} onSaved={refresh}/></details>:item.blueprint&&<details><summary>查看已冻结蓝图</summary><p><strong>重点：</strong>{item.blueprint.focus}</p><p><strong>节奏：</strong>{item.blueprint.pacing}</p><p><strong>格式：</strong>{item.blueprint.format}</p><ol>{item.blueprint.chapter_map.map((mapping:any)=><li key={mapping.source_chapter_id}>{mapping.unit} · {mapping.source_title}：{mapping.action}</li>)}</ol></details>}<details><summary>查看原作版本快照</summary><ul>{item.source_versions.map((source:{chapter_id:string;version:number})=><li key={source.chapter_id}>{source.chapter_id} · v{source.version}</li>)}</ul></details>{item.execution_manifest&&<details><summary>查看改编执行清单</summary><p className="novel-help">当前状态：{item.execution_status}</p><ol>{item.execution_manifest.map((task:any)=><li key={task.id}><strong>{task.unit}</strong> · {task.action} <Badge>{task.status}</Badge>{['PENDING_REWRITE','REJECTED','FAILED'].includes(task.status)?<Button disabled={draftMode==='model'&&!selectedModel} onClick={()=>generateDraft.mutate({proposalId:item.id,taskId:task.id})}>生成草稿</Button>:null}{task.status==='AWAITING_REVIEW'?<><Button onClick={()=>reviewDraft.mutate({proposalId:item.id,taskId:task.id,decision:'ACCEPTED'})}>接受草稿</Button><Button onClick={()=>reviewDraft.mutate({proposalId:item.id,taskId:task.id,decision:'REJECTED'})}>驳回草稿</Button></>:null}{task.status==='ACCEPTED'&&<Button disabled={applyDraft.isPending} onClick={()=>applyDraft.mutate({proposalId:item.id,taskId:task.id})}>写入工作副本</Button>}{task.draft&&<p className="novel-help">{task.draft.note||`${task.draft.provider||''} ${task.draft.model||''}`}</p>}{task.error&&<p className="novel-error">{task.error_code}：{task.error}</p>}</li>)}</ol></details>}{item.status==='DRAFT'&&<Button disabled={approve.isPending} onClick={()=>approve.mutate(item.id)}>批准方案</Button>}{['APPROVED','MATERIALIZING'].includes(item.status)&&<Button disabled={materialize.isPending} onClick={()=>materialize.mutate(item.id)}>{item.status==='MATERIALIZING'?'继续生成改编版本':'生成改编版本'}</Button>}{item.status==='MATERIALIZED'&&<p className="novel-help">改编工作副本已创建：{item.adapted_novel_id}。章节等待改写，不代表已经完成改编。</p>}</article></li>)}</ul>
    </section>}
  </Panel>;
}
