import {useEffect,useState} from 'react';
import {api} from '../api';
import {Badge,Button,Panel,StatusMessage} from '../ui/primitives';
import {FOCUS_FAILED_TASKS_EVENT,publishTaskSummary} from '../ui/taskSummary';
import type {AudioInspection} from './AudioTaskInspector';

const tone=(status:string):'neutral'|'info'|'success'|'warning'|'error'=>status==='SUCCEEDED'?'success':status==='FAILED'?'error':status==='CANCELLED'?'neutral':status==='RUNNING'?'info':'warning';
export function AudiobookManifestPanel({novelId,onInspect}:{novelId?:string;onInspect?:(inspection:AudioInspection)=>void}){
  const [data,setData]=useState<any>(),[jobs,setJobs]=useState<any[]>([]),[mix,setMix]=useState<any>(),[loading,setLoading]=useState(false),[error,setError]=useState('');
  const [providerId,setProviderId]=useState('openai'),[modelId,setModelId]=useState('gpt-4o-mini-tts'),[voice,setVoice]=useState('alloy'),[emotion,setEmotion]=useState('neutral');
  const [speechRate,setSpeechRate]=useState(1),[pauseMs,setPauseMs]=useState(280);
  const [characterId,setCharacterId]=useState(''),[term,setTerm]=useState(''),[pronunciation,setPronunciation]=useState(''),[settings,setSettings]=useState<{voice_bindings:any[];pronunciation_dictionary:any[]}>({voice_bindings:[],pronunciation_dictionary:[]});
  const refresh=async()=>{if(!novelId)return;setLoading(true);setError('');try{const [manifest,queue,plan,audioSettings]=await Promise.all([api.audiobookManifest(novelId),api.audiobookJobs(novelId),api.audiobookMixPlan(novelId),api.audioProductionSettings(novelId)]);setData(manifest);setJobs(queue.items||[]);setMix(plan);setSettings(audioSettings)}catch{setError('声音工作区数据加载失败。')}finally{setLoading(false)}};
  useEffect(()=>{refresh()},[novelId]);
  useEffect(()=>{publishTaskSummary('audiobook',jobs);},[jobs]);
  useEffect(()=>{const listener=(event:Event)=>{const detail=(event as CustomEvent).detail;if(detail?.source!=='audiobook')return;const job=jobs.find(item=>String(item.id)===String(detail.taskId));onInspect?.(job?{kind:'audiobook',id:String(job.id),status:job.status,chapterId:job.chapter_id,providerId:job.provider_id,modelId:job.model_id,voice:job.voice,audioUri:job.audio_uri,error:job.error}:{kind:'audiobook',id:String(detail.taskId||'audiobook-job'),status:'FAILED',pendingRefresh:true});};window.addEventListener(FOCUS_FAILED_TASKS_EVENT,listener);return()=>window.removeEventListener(FOCUS_FAILED_TASKS_EVENT,listener)},[jobs,onInspect]);
  const saveSettings=async(next:typeof settings)=>{if(!novelId)return;await api.updateAudioProductionSettings(novelId,next);setSettings(next)};
  const inspect=(job:any)=>onInspect?.({kind:'audiobook',id:String(job.id),status:job.status,chapterId:job.chapter_id,providerId:job.provider_id,modelId:job.model_id,voice:job.voice,audioUri:job.audio_uri,error:job.error});
  return <Panel title="有声小说编排" actions={<Button variant="ghost" loading={loading} onClick={refresh}>刷新</Button>}>
    {error&&<StatusMessage tone="error">{error}</StatusMessage>}
    <details><summary>制作配置</summary>
      <label>Provider<input value={providerId} onChange={event=>setProviderId(event.target.value)}/></label><label>模型<input value={modelId} onChange={event=>setModelId(event.target.value)}/></label><label>默认音色<input value={voice} onChange={event=>setVoice(event.target.value)}/></label><label>情绪<input value={emotion} onChange={event=>setEmotion(event.target.value)}/></label><label>语速<input aria-label="有声书语速" type="number" min="0.5" max="2" step="0.1" value={speechRate} onChange={event=>setSpeechRate(Number(event.target.value)||1)}/></label><label>句间停顿（毫秒）<input aria-label="句间停顿毫秒" type="number" min="0" max="3000" step="20" value={pauseMs} onChange={event=>setPauseMs(Number(event.target.value)||0)}/></label>
      <label>角色 ID<input value={characterId} onChange={event=>setCharacterId(event.target.value)}/></label><Button variant="ghost" disabled={!characterId.trim()} onClick={()=>saveSettings({...settings,voice_bindings:[...settings.voice_bindings.filter(item=>item.character_id!==characterId.trim()),{character_id:characterId.trim(),provider_id:providerId,model_id:modelId,voice,emotion}]})}>保存角色声线</Button>
      {settings.voice_bindings.map(binding=><p className="novel-help" key={binding.character_id}>{binding.character_id} · {binding.provider_id}/{binding.model_id} · {binding.voice}</p>)}
      <label>词条<input value={term} onChange={event=>setTerm(event.target.value)}/></label><label>读音替换<input value={pronunciation} onChange={event=>setPronunciation(event.target.value)}/></label><Button variant="ghost" disabled={!term.trim()||!pronunciation.trim()} onClick={()=>{const next={...settings,pronunciation_dictionary:[...settings.pronunciation_dictionary.filter(item=>item.term!==term.trim()),{term:term.trim(),pronunciation:pronunciation.trim()}]};saveSettings(next);setTerm('');setPronunciation('')}}>加入发音词典</Button>
      {settings.pronunciation_dictionary.map(entry=><p className="novel-help" key={entry.term}>{entry.term} → {entry.pronunciation}</p>)}
    </details>
    {jobs.length>0&&<section aria-label="有声书任务队列"><p className="novel-help">合成队列 {jobs.length} · 排队 {jobs.filter(job=>job.status==='QUEUED').length} · 运行 {jobs.filter(job=>job.status==='RUNNING').length} · 失败 {jobs.filter(job=>job.status==='FAILED').length}</p>{jobs.map(job=><article key={job.id}><strong>{job.chapter_id}</strong> <Badge tone={tone(job.status)}>{job.status}</Badge><p className="novel-help">{job.provider_id}/{job.model_id} · {job.voice} · 尝试 {job.attempt||0} 次 {job.error&&` · ${job.error}`}</p>{job.timing_status==='ESTIMATED'&&<p className="novel-help">字幕时间码：估算 · {job.segments?.length||0} 段 · {((job.estimated_duration_ms||0)/1000).toFixed(1)} 秒</p>}<Button variant="ghost" onClick={()=>inspect(job)}>检查</Button>{job.status==='QUEUED'&&<><Button variant="ghost" onClick={()=>novelId&&api.executeAudiobookJob(novelId,job.id).catch(()=>undefined).then(refresh)}>执行</Button><Button variant="ghost" onClick={()=>novelId&&api.cancelAudiobookJob(novelId,job.id).then(refresh)}>取消</Button></>}{['FAILED','CANCELLED'].includes(job.status)&&<Button variant="ghost" onClick={()=>novelId&&api.retryAudiobookJob(novelId,job.id).then(refresh)}>重试</Button>}</article>)}</section>}
    {mix&&<details><summary>混音计划：{mix.tracks?.length||0} 条轨道 · {mix.mix_status}</summary>{(mix.tracks||[]).map((track:any)=><p key={track.track_id} className="novel-help">轨道 {track.track_id} · {track.clips?.length||0} 个片段</p>)}</details>}
    {data&&<><p className="novel-help">已准备 {data.ready_chapters}/{data.total_chapters} 个章节</p>{data.chapters.map((chapter:any)=><article key={chapter.chapter_id}><strong>{chapter.title||chapter.chapter_id}</strong><p>文本 {chapter.text_length} 字 · 音频 {chapter.audio_count} 条</p>{chapter.audio.map((audio:any,index:number)=><audio key={`${audio.created_at}-${index}`} controls src={audio.audio_uri} style={{width:'100%'}}/>)}{chapter.audio_count===0&&<Button variant="ghost" onClick={()=>novelId&&api.queueAudiobookChapter(novelId,chapter.chapter_id,{provider_id:providerId,model_id:modelId,voice,emotion,speech_rate:speechRate,pause_ms:pauseMs}).then(refresh)}>加入合成队列</Button>}</article>)}</>}
  </Panel>;
}
