import {useEffect,useState,useRef} from 'react';
import {api,apiErrorView,getCollaborationContext} from '../api';
import {AuthenticatedMedia} from './AuthenticatedMedia';
import {Badge,Button,Panel,StatusMessage} from '../ui/primitives';
import {FOCUS_FAILED_TASKS_EVENT,publishTaskSummary} from '../ui/taskSummary';
import type {AudioInspection} from './AudioTaskInspector';
import './AudiobookManifestPanel.css';

const tone=(status:string):'neutral'|'info'|'success'|'warning'|'error'=>status==='SUCCEEDED'?'success':status==='FAILED'?'error':status==='CANCELLED'?'neutral':status==='RUNNING'?'info':'warning';
export function AudiobookManifestPanel({novelId,onInspect,requestedTaskId}:{novelId?:string;onInspect?:(inspection:AudioInspection)=>void;requestedTaskId?:string}){
 const targetFocused=useRef('');
  const [data,setData]=useState<any>(),[jobs,setJobs]=useState<any[]>([]),[mix,setMix]=useState<any>(),[loading,setLoading]=useState(false),[error,setError]=useState('');
  const [providerId,setProviderId]=useState('openai'),[modelId,setModelId]=useState('gpt-4o-mini-tts'),[voice,setVoice]=useState('alloy'),[emotion,setEmotion]=useState('neutral');
  const [speechRate,setSpeechRate]=useState(1),[pauseMs,setPauseMs]=useState(280),[licenseNote,setLicenseNote]=useState('');
  const [characterId,setCharacterId]=useState(''),[term,setTerm]=useState(''),[pronunciation,setPronunciation]=useState(''),[settings,setSettings]=useState<{voice_bindings:any[];pronunciation_dictionary:any[]}>({voice_bindings:[],pronunciation_dictionary:[]});
  const [queueAction,setQueueAction]=useState<'next'|'all'|''>('');
  const context=getCollaborationContext(),scopeKey=JSON.stringify([novelId,context.actor?.id,context.scope?.branchId,context.sessionToken]);
  const currentScope=useRef<string|null>(scopeKey);currentScope.current=scopeKey;
  const [pending,setPending]=useState('');const pendingRef=useRef(new Set<string>());
  const refresh=async()=>{if(!novelId||currentScope.current!==scopeKey)return;setLoading(true);setError('');try{const [manifest,queue,plan,audioSettings]=await Promise.all([api.audiobookManifest(novelId),api.audiobookJobs(novelId),api.audiobookMixPlan(novelId),api.audioProductionSettings(novelId)]);if(currentScope.current!==scopeKey)return;setData(manifest);setJobs(queue.items||[]);setMix(plan);setSettings(audioSettings)}catch{if(currentScope.current===scopeKey)setError('声音工作区数据加载失败。')}finally{if(currentScope.current===scopeKey)setLoading(false)}};
  useEffect(()=>{currentScope.current=scopeKey;setData(undefined);setJobs([]);setMix(undefined);setError('');setPending('');pendingRef.current.clear();void refresh();return()=>{currentScope.current=null}},[scopeKey]);
  useEffect(()=>{publishTaskSummary('audiobook',jobs);},[jobs]);
  useEffect(()=>{const listener=(event:Event)=>{const detail=(event as CustomEvent).detail;if(detail?.source!=='audiobook')return;const job=jobs.find(item=>String(item.id)===String(detail.taskId));onInspect?.(job?{kind:'audiobook',id:String(job.id),status:job.status,chapterId:job.chapter_id,providerId:job.provider_id,modelId:job.model_id,voice:job.voice,audioUri:job.audio_uri,assetId:job.asset_id,error:job.error}:{kind:'audiobook',id:String(detail.taskId||'audiobook-job'),status:'FAILED',pendingRefresh:true});};window.addEventListener(FOCUS_FAILED_TASKS_EVENT,listener);return()=>window.removeEventListener(FOCUS_FAILED_TASKS_EVENT,listener)},[jobs,onInspect]);
  const saveSettings=async(next:typeof settings)=>{if(!novelId)return;setError('');try{await api.updateAudioProductionSettings(novelId,next);setSettings(next)}catch(reason){setError(apiErrorView(reason,'声音配置保存失败。').message)}};
  const perform=async(key:string,action:()=>Promise<unknown>)=>{if(pendingRef.current.has(key))return;pendingRef.current.add(key);setPending(key);setError('');try{await action();if(currentScope.current===scopeKey)await refresh()}catch(reason){if(currentScope.current===scopeKey)setError(apiErrorView(reason,'任务操作失败。').message)}finally{pendingRef.current.delete(key);if(currentScope.current===scopeKey)setPending('')}};
  const inspect=(job:any)=>onInspect?.({kind:'audiobook',id:String(job.id),status:job.status,chapterId:job.chapter_id,providerId:job.provider_id,modelId:job.model_id,voice:job.voice,audioUri:job.audio_uri,assetId:job.asset_id,error:job.error});
  const consume=async(limit:number,action:'next'|'all')=>{if(!novelId||queueAction)return;setQueueAction(action);setError('');try{await api.consumeAudiobookJobs(novelId,limit);if(currentScope.current===scopeKey)await refresh()}catch{if(currentScope.current===scopeKey)setError('队列处理失败。任务状态已保留，可刷新后重试。')}finally{if(currentScope.current===scopeKey)setQueueAction('')}};
  const downloadSubtitles=async(job:any,format:'srt'|'vtt')=>{if(!novelId)return;setError('');try{const blob=await api.audiobookSubtitles(novelId,job.id,format);const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`${job.chapter_id||'chapter'}-${String(job.id).slice(-8)}.${format}`;anchor.click();URL.revokeObjectURL(url)}catch{setError('字幕导出失败。请确认任务包含已估算的字幕分段。')}};
  const statusLabel=(status:string)=>({NOT_QUEUED:'未排队',QUEUED:'已排队',RUNNING:'合成中',SUCCEEDED:'已完成',FAILED:'失败',CANCELLED:'已取消'}[status]||status);
  const queuedCount=jobs.filter(job=>job.status==='QUEUED').length;
  return <Panel className="audiobook-manifest" title="有声小说编排" actions={<Button variant="ghost" loading={loading} onClick={refresh}>刷新</Button>}>
    {requestedTaskId && data && !loading && !error && !jobs.some(job=>job.id===requestedTaskId) && <StatusMessage tone="warning">请求的原音频任务当前不可读或已移除。</StatusMessage>}
    {error&&<StatusMessage tone="error">{error}</StatusMessage>}
    <details><summary>制作配置</summary>
      <label>Provider<input value={providerId} onChange={event=>setProviderId(event.target.value)}/></label><label>模型<input value={modelId} onChange={event=>setModelId(event.target.value)}/></label><label>默认音色<input value={voice} onChange={event=>setVoice(event.target.value)}/></label><label>情绪<select value={emotion} onChange={event=>setEmotion(event.target.value)}><option value="neutral">自然（当前已映射能力）</option></select></label><p className="novel-help">未声明情绪能力的 Provider 只允许自然语气；不会将情绪标签读入正文。请仅使用已获许可的声音。停顿参数用于字幕估算和分段 WAV 拼接，不会伪称 Provider 已控制整章停顿。</p><label>语速<input aria-label="有声书语速" type="number" min="0.5" max="2" step="0.1" value={speechRate} onChange={event=>setSpeechRate(Number(event.target.value)||1)}/></label><label>句间停顿（毫秒）<input aria-label="句间停顿毫秒" type="number" min="0" max="3000" step="20" value={pauseMs} onChange={event=>setPauseMs(Number(event.target.value)||0)}/></label>
      <label>声音授权来源<input aria-label="声音授权来源" value={licenseNote} placeholder="Provider 标准音色许可或素材授权说明" onChange={event=>setLicenseNote(event.target.value)}/></label><label>角色 ID<input value={characterId} onChange={event=>setCharacterId(event.target.value)}/></label><Button variant="ghost" disabled={!characterId.trim()} onClick={()=>saveSettings({...settings,voice_bindings:[...settings.voice_bindings.filter(item=>item.character_id!==characterId.trim()),{character_id:characterId.trim(),provider_id:providerId,model_id:modelId,voice,emotion,...(licenseNote?{license_note:licenseNote}:{})}]})}>保存角色声线</Button>
      {settings.voice_bindings.map(binding=><p className="novel-help" key={binding.character_id}>{binding.character_id} · {binding.provider_id}/{binding.model_id} · {binding.voice}</p>)}
      <label>词条<input value={term} onChange={event=>setTerm(event.target.value)}/></label><label>读音替换<input value={pronunciation} onChange={event=>setPronunciation(event.target.value)}/></label><Button variant="ghost" disabled={!term.trim()||!pronunciation.trim()} onClick={()=>{const next={...settings,pronunciation_dictionary:[...settings.pronunciation_dictionary.filter(item=>item.term!==term.trim()),{term:term.trim(),pronunciation:pronunciation.trim()}]};saveSettings(next);setTerm('');setPronunciation('')}}>加入发音词典</Button>
      {settings.pronunciation_dictionary.map(entry=><p className="novel-help" key={entry.term}>{entry.term} → {entry.pronunciation}</p>)}
    </details>
    {jobs.length>0&&<section aria-label="有声书任务队列"><div className="audiobook-manifest__queue-head"><p className="novel-help">合成队列 {jobs.length} · 排队 {queuedCount} · 运行 {jobs.filter(job=>job.status==='RUNNING').length} · 失败 {jobs.filter(job=>job.status==='FAILED').length}</p><div><Button variant="secondary" loading={queueAction==='next'} disabled={!queuedCount||!!queueAction} onClick={()=>consume(1,'next')}>处理下一个</Button><Button variant="ghost" loading={queueAction==='all'} disabled={!queuedCount||!!queueAction} onClick={()=>consume(Math.min(queuedCount,20),'all')}>连续处理</Button></div></div><p className="novel-help">连续处理由当前桌面会话触发，逐项保存结果；不会在后台静默完成。取消会丢弃晚到结果，不保证远端立即停止计算。</p>{jobs.map(job=><article className="audiobook-manifest__row" key={job.id} aria-current={requestedTaskId===job.id?"true":undefined} tabIndex={requestedTaskId===job.id?0:undefined} ref={element=>{if(element&&requestedTaskId===job.id&&targetFocused.current!==requestedTaskId){targetFocused.current=String(requestedTaskId);element.focus();element.scrollIntoView?.({block:"nearest"})}}}><div><strong>{job.chapter_id}</strong><p>任务 ID：{job.id}</p> <Badge tone={tone(job.status)}>{statusLabel(job.status)}</Badge><p className="novel-help">{job.provider_id}/{job.model_id} · {job.voice} · 尝试 {job.attempt||0} 次 {job.error&&` · ${job.error}`}</p>{job.duration_ms!=null&&<p className="novel-help">音频实测：{(job.duration_ms/1000).toFixed(2)} 秒 · {job.media_validation}</p>}{job.timing_status==='ESTIMATED'&&<p className="novel-help">字幕时间码：估算 · {job.segments?.length||0} 段 · {((job.estimated_duration_ms||0)/1000).toFixed(1)} 秒</p>}</div><div className="audiobook-manifest__actions"><Button variant="ghost" onClick={()=>inspect(job)}>检查</Button>{job.segments?.length>0&&<><Button variant="ghost" onClick={()=>downloadSubtitles(job,'srt')}>SRT</Button><Button variant="ghost" onClick={()=>downloadSubtitles(job,'vtt')}>VTT</Button></>}{['QUEUED','RUNNING'].includes(job.status)&&<><Button variant="ghost" disabled={job.status!=='QUEUED'||!!pending} onClick={()=>novelId&&void perform('execute-'+job.id,()=>api.executeAudiobookJob(novelId,job.id))}>执行</Button><Button variant="ghost" disabled={pending==='cancel-'+job.id} onClick={()=>novelId&&void perform('cancel-'+job.id,()=>api.cancelAudiobookJob(novelId,job.id))}>取消</Button></>}{['FAILED','CANCELLED'].includes(job.status)&&<Button variant="ghost" disabled={!!pending} onClick={()=>novelId&&void perform('retry-'+job.id,()=>api.retryAudiobookJob(novelId,job.id))}>重试</Button>}</div></article>)}</section>}
    {mix&&<details><summary>混音计划：{mix.tracks?.length||0} 条轨道 · {mix.mix_status}</summary>{(mix.tracks||[]).map((track:any)=><p key={track.track_id} className="novel-help">轨道 {track.track_id} · {track.clips?.length||0} 个片段</p>)}</details>}
    {data&&<section aria-label="章节制作状态"><p className="novel-help">已产出音频 {data.ready_chapters}/{data.total_chapters} 个章节</p>{data.chapters.map((chapter:any)=><article className="audiobook-manifest__row" key={chapter.chapter_id}><div><strong>{chapter.title||chapter.chapter_id}</strong> <Badge tone={tone(chapter.production_status)}>{statusLabel(chapter.production_status)}</Badge><p className="novel-help">文本 {chapter.text_length} 字 · 音频 {chapter.audio_count} 条</p>{chapter.audio_count>0&&<Button variant="ghost" onClick={async()=>{if(!novelId)return;try{const ids=chapter.audio.filter((item:any)=>item.job_id&&item.asset_id).map((item:any)=>item.job_id);if(!ids.length)throw new Error('旧音频尚未通过本地资源校验，请重新生成。');const blob=await api.downloadAudiobookChapter(novelId,chapter.chapter_id,ids);const url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`${chapter.chapter_id}.${blob.type.includes('wav')?'wav':'audio'}`;anchor.click();URL.revokeObjectURL(url)}catch(reason){setError(apiErrorView(reason,'章节音频导出失败。').message)}}}>导出已验证音频</Button>}{chapter.audio.map((audio:any,index:number)=><AuthenticatedMedia key={`${audio.created_at}-${index}`} kind="audio" label="章节朗读音频" novelId={novelId} assetId={audio.asset_id} uri={audio.audio_uri}/>)}</div>{!['QUEUED','RUNNING'].includes(chapter.production_status)&&<Button variant="ghost" disabled={!!pending} onClick={()=>novelId&&void perform('queue-'+chapter.chapter_id,()=>api.queueAudiobookChapter(novelId,chapter.chapter_id,{provider_id:providerId,model_id:modelId,voice,emotion,...(licenseNote?{license_note:licenseNote}:{}),speech_rate:speechRate,pause_ms:pauseMs}))}>{chapter.audio_count===0?'加入合成队列':'重新合成'}</Button>} {!['QUEUED','RUNNING'].includes(chapter.production_status)&&<Button variant="ghost" onClick={async()=>{if(!novelId)return;try{await api.queueAudiobookSegments(novelId,chapter.chapter_id,{provider_id:providerId,model_id:modelId,voice,emotion,...(licenseNote?{license_note:licenseNote}:{}),character_id:characterId||undefined,speech_rate:speechRate,pause_ms:pauseMs});await refresh()}catch(reason){setError(apiErrorView(reason,'分段排队失败。').message)}}}>按句分段排队</Button>}</article>)}</section>}
  </Panel>;
}
