import { useEffect, useState } from 'react';
import { Button } from '../ui/primitives';
import { api } from '../api';
import type { DirectorShot } from './MultimodalDirectorWorkspace';

export function DirectorShotCard({ shot, index, profiles, onChange, novelId, onSaveConstraints, onConstraintStatus }: { shot: DirectorShot; index: number; profiles: { name: string }[]; onChange: (index: number, patch: Partial<DirectorShot>) => void; novelId?: string; onSaveConstraints?: (shot: DirectorShot) => Promise<void> | void; onConstraintStatus?: (key: string, status: string) => void }) {
  const [state, setState] = useState<{ loading?: boolean; uri?: string; error?: string }>({});
  const [saveState, setSaveState] = useState<'idle' | 'saving' | 'saved' | 'failed'>('idle');
  const [savedAt, setSavedAt] = useState('');
  const [confirmedAt, setConfirmedAt] = useState('');
  const [historyWarning, setHistoryWarning] = useState(false);
  useEffect(() => {
    if (!novelId) return;
    const apply = (selected: any) => { if (!shot.screenplay_id && !shot.motion_task_id && selected?.screenplay_id && selected?.motion_task_id) onChange(index, { screenplay_id: selected.screenplay_id, motion_task_id: selected.motion_task_id }); };
    try { apply(JSON.parse(localStorage.getItem(`multimodal-selected-motion:${novelId}`) || 'null')); } catch { /* optional local binding */ }
    const handle = (event: Event) => { const detail = (event as CustomEvent).detail; if (detail?.novelId === novelId) apply(detail); };
    window.addEventListener('multimodal-motion-binding', handle); return () => window.removeEventListener('multimodal-motion-binding', handle);
  }, [novelId, index, onChange, shot.motion_task_id, shot.screenplay_id]);
  const text = (shot.dialogue || shot.subtitle || '').trim();
  const synthesize = async () => { setState({ loading: true }); try { const result = await api.synthesizeDirectorShotDialogue(shot, { provider_id: 'openai', model_id: 'gpt-4o-mini-tts', voice: shot.voice || '', emotion: shot.emotion || 'neutral', novel_id: novelId }); setState({ uri: result.audio_uri }); } catch { setState({ error: '配音生成失败，请检查声音模型与凭据。' }); } };
  return <article className="multimodal-director__shot-card">
    <input aria-label="镜头名称" value={shot.name} onChange={e => onChange(index, { name: e.target.value })}/><input aria-label="镜头时长" value={shot.duration} onChange={e => onChange(index, { duration: e.target.value })}/><input aria-label="镜头运动" value={shot.camera} onChange={e => onChange(index, { camera: e.target.value })}/><textarea aria-label="镜头动作" rows={2} value={shot.action} onChange={e => onChange(index, { action: e.target.value })}/>
    <select aria-label="镜头一致性档案" value={shot.profile || ''} onChange={e => onChange(index, { profile: e.target.value })}><option value="">不绑定档案</option>{profiles.map(p => <option key={p.name}>{p.name}</option>)}</select><input aria-label="剧本 ID" placeholder="绑定剧本 ID" value={shot.screenplay_id || ''} onChange={e => onChange(index, { screenplay_id: e.target.value, binding_source: 'manual' })}/>{shot.binding_candidates?.length ? <><select aria-label="候选 Motion Task" value={shot.motion_task_id || ''} onChange={e => onChange(index, { motion_task_id: e.target.value, binding_source: 'manual', binding_candidates: [] })}><option value="">选择候选任务</option>{shot.binding_candidates.map(id => <option key={id}>{id}</option>)}</select><small className="novel-help">发现 {shot.binding_candidates.length} 个候选任务，需要人工选择</small></> : <input aria-label="Motion Task ID" placeholder="绑定 Motion Task ID" value={shot.motion_task_id || ''} onChange={e => onChange(index, { motion_task_id: e.target.value, binding_source: 'manual' })}/>} {shot.motion_task_id && <small className="novel-help">{shot.binding_source === 'auto' ? '自动绑定' : '手动绑定'}</small>}
    <input aria-label="镜头对白" placeholder="对白 / 旁白" value={shot.dialogue || ''} onChange={e => onChange(index, { dialogue: e.target.value })}/><input aria-label="镜头环境音" placeholder="环境音" value={shot.ambience || ''} onChange={e => onChange(index, { ambience: e.target.value })}/><input aria-label="镜头音效" placeholder="动作音效" value={shot.sound_effect || ''} onChange={e => onChange(index, { sound_effect: e.target.value })}/><input aria-label="镜头音乐" placeholder="音乐情绪 / 入点" value={shot.music || ''} onChange={e => onChange(index, { music: e.target.value })}/><input aria-label="镜头字幕" placeholder="字幕文本" value={shot.subtitle || ''} onChange={e => onChange(index, { subtitle: e.target.value })}/><input aria-label="镜头声音" placeholder="声音档案" value={shot.voice || ''} onChange={e => onChange(index, { voice: e.target.value })}/><select aria-label="镜头情绪" value={shot.emotion || 'neutral'} onChange={e => onChange(index, { emotion: e.target.value })}><option value="neutral">中性</option><option value="calm">平静</option><option value="urgent">紧迫</option><option value="sad">悲伤</option></select>
    <Button variant="ghost" disabled={!text || !shot.voice || state.loading} onClick={synthesize}>{state.loading ? '生成中…' : '生成配音'}</Button>{onSaveConstraints && <Button variant="ghost" disabled={!novelId || !shot.screenplay_id || !shot.motion_task_id || saveState === 'saving'} onClick={async () => { const key=shot.shot_id||String(index); setSaveState('saving'); onConstraintStatus?.(key,'saving'); setHistoryWarning(false); try { await onSaveConstraints(shot); const at = new Date().toISOString(); setSavedAt(at); setSaveState('saved'); try { const history = await api.motionFrameHistory(novelId!, shot.screenplay_id!, shot.motion_task_id!); const latest = history.history?.[0] || history.current; setConfirmedAt(latest?.changed_at || latest?.updated_at || '已确认'); onConstraintStatus?.(key,'confirmed'); } catch { setHistoryWarning(true); onConstraintStatus?.(key,'pending_confirmation'); } } catch { setSaveState('failed'); onConstraintStatus?.(key,'failed'); } }}>{saveState === 'saving' ? '保存中…' : '保存镜头约束'}</Button>}{saveState === 'saved' && <small role="status">镜头约束已保存{savedAt && ` · ${new Date(savedAt).toLocaleTimeString()}`} · 任务 {shot.motion_task_id}{confirmedAt && ` · 后端版本 ${confirmedAt}`}</small>}{historyWarning && <small role="status">约束已保存，但帧历史暂未确认。</small>}{saveState === 'failed' && <small role="alert">保存失败，请检查任务绑定与服务状态。</small>}{state.uri && <audio controls src={state.uri}/>} {state.error && <small role="alert">{state.error}</small>}
  </article>;
}
