// @vitest-environment jsdom
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,describe,expect,it,vi} from 'vitest';
import {EntryExperience} from './EntryExperience';
import {api} from '../api';

afterEach(()=>{cleanup();vi.restoreAllMocks()});
const workspace={id:'workspace-a',name:'作者空间'};
const workspaceB={id:'workspace-b',name:'协作空间'};
const novel={workspace_id:'workspace-a',project_id:'novel-a',storyline_id:'story-a',branch_id:'branch-a',project_name:'雾港来信',storyline_name:'默认故事线',branch_name:'主分支'};
function navigation(paths=[novel]){return {workspace_id:'workspace-a',eligible_paths:paths,default_path:paths[0]||null}}
function packaged(items=[workspace]){vi.spyOn(api,'adminWorkspaces').mockResolvedValue(items);vi.spyOn(api,'adminWorkspaceNavigation').mockResolvedValue(navigation())}

describe('EntryExperience',()=>{
  it('keeps the legacy connection entry available outside packaged mode',()=>{render(<EntryExperience initialToken="" onEnter={vi.fn()}/>);expect(screen.getByRole('heading',{name:'AI Novel Studio'})).toBeTruthy();expect(screen.getByText('连接已有创作空间')).toBeTruthy();expect(screen.getByLabelText('访问凭证')).toBeTruthy()});
  it('renders a dedicated packaged launch screen with both author entry modes',async()=>{packaged();render(<EntryExperience packagedHost initialToken="" onEnter={vi.fn()}/>);expect(await screen.findByRole('heading',{name:'AI Novel Studio'})).toBeTruthy();expect(screen.getByRole('button',{name:/个人创作/})).toBeTruthy();expect(screen.getByRole('button',{name:/团队协作/})).toBeTruthy();expect(screen.queryByText('我的小说')).toBeNull()});
  it('provisions once without authoritative arguments and uses the server workspace identity',async()=>{packaged([]);const created={id:'server-workspace',name:'我的创作空间'};let finish!:(value:typeof created)=>void;const create=vi.spyOn(api,'packagedProvisionInitialWorkspace').mockImplementation(()=>new Promise(resolve=>{finish=resolve}));vi.mocked(api.adminWorkspaceNavigation).mockResolvedValue({workspace_id:created.id,eligible_paths:[],default_path:null});render(<EntryExperience packagedHost initialToken="" onEnter={vi.fn()}/>);const personal=await screen.findByRole('button',{name:/个人创作/});fireEvent.click(personal);fireEvent.click(personal);expect(await screen.findByText('正在准备你的创作空间…')).toBeTruthy();expect(create).toHaveBeenCalledTimes(1);expect(create).toHaveBeenCalledWith();finish(created);await screen.findByRole('heading',{name:'我的小说'});expect((screen.getByLabelText('小说名称') as HTMLInputElement).disabled).toBe(false)});
  it('keeps novel controls hidden when packaged provisioning fails',async()=>{packaged([]);vi.spyOn(api,'packagedProvisionInitialWorkspace').mockRejectedValue(new Error('internal'));render(<EntryExperience packagedHost initialToken="" onEnter={vi.fn()}/>);fireEvent.click(await screen.findByRole('button',{name:/个人创作/}));expect((await screen.findByRole('alert')).textContent).toContain('创作空间建立失败，请重试。');expect(screen.queryByLabelText('小说名称')).toBeNull()});
  it('does not guess among existing workspaces in personal mode',async()=>{packaged([workspace,workspaceB]);render(<EntryExperience packagedHost initialToken="" onEnter={vi.fn()}/>);fireEvent.click(await screen.findByRole('button',{name:/个人创作/}));expect(await screen.findByRole('heading',{name:'选择个人创作空间'})).toBeTruthy();expect(screen.getByRole('button',{name:/作者空间/})).toBeTruthy();expect(screen.getByRole('button',{name:/协作空间/})).toBeTruthy();expect(api.adminWorkspaceNavigation).not.toHaveBeenCalled()});
  it('shows only server-authorized workspaces for team mode and explains an empty result',async()=>{packaged([]);const view=render(<EntryExperience packagedHost initialToken="" onEnter={vi.fn()}/>);fireEvent.click(await screen.findByRole('button',{name:/团队协作/}));expect(await screen.findByText('目前还没有可加入的团队创作空间')).toBeTruthy();view.unmount();packaged([workspaceB]);render(<EntryExperience packagedHost initialToken="" onEnter={vi.fn()}/>);fireEvent.click(await screen.findByRole('button',{name:/团队协作/}));expect(await screen.findByRole('button',{name:/协作空间/})).toBeTruthy()});
  it('selects an authorized workspace, opens an existing novel, and exposes no internal ids',async()=>{packaged();const enter=vi.fn();render(<EntryExperience packagedHost initialToken="" onEnter={enter}/>);fireEvent.click(await screen.findByRole('button',{name:/个人创作/}));fireEvent.click(await screen.findByRole('button',{name:/作者空间/}));const card=await screen.findByRole('button',{name:/雾港来信.*打开小说/});fireEvent.click(card);expect(enter).toHaveBeenCalledWith('',expect.objectContaining({workspaceId:'workspace-a',projectId:'novel-a'}));expect(screen.queryByText(/workspace-a|story-a|branch-a/)).toBeNull()});
  it('creates and enters a novel after workspace resolution',async()=>{packaged();const enter=vi.fn();vi.spyOn(api,'adminCreateProject').mockResolvedValue({id:'novel-new',title:'新故事'} as any);vi.mocked(api.adminWorkspaceNavigation).mockResolvedValueOnce({workspace_id:workspace.id,eligible_paths:[],default_path:null}).mockResolvedValueOnce({workspace_id:workspace.id,eligible_paths:[{...novel,project_id:'novel-new',project_name:'新故事'}],default_path:null});render(<EntryExperience packagedHost initialToken="" onEnter={enter}/>);fireEvent.click(await screen.findByRole('button',{name:/个人创作/}));fireEvent.click(await screen.findByRole('button',{name:/作者空间/}));const input=await screen.findByLabelText('小说名称') as HTMLInputElement;expect(input.disabled).toBe(false);fireEvent.change(input,{target:{value:'新故事'}});fireEvent.keyDown(input,{key:'Enter'});await waitFor(()=>expect(api.adminCreateProject).toHaveBeenCalledWith('workspace-a','新故事'));await waitFor(()=>expect(enter).toHaveBeenCalledWith('',expect.objectContaining({projectId:'novel-new'})))});
  it('requires confirmation before deleting a novel and refreshes the library',async()=>{packaged();vi.spyOn(api,'deleteNovel').mockResolvedValue(undefined);render(<EntryExperience packagedHost initialToken="" onEnter={vi.fn()}/>);fireEvent.click(await screen.findByRole('button',{name:/个人创作/}));fireEvent.click(await screen.findByRole('button',{name:/作者空间/}));fireEvent.click(await screen.findByRole('button',{name:'删除小说雾港来信'}));expect(api.deleteNovel).not.toHaveBeenCalled();expect(screen.getByRole('alertdialog').textContent).toContain('无法撤销');vi.mocked(api.adminWorkspaceNavigation).mockResolvedValueOnce(navigation([]));fireEvent.click(screen.getByRole('button',{name:'永久删除小说'}));await waitFor(()=>expect(api.deleteNovel).toHaveBeenCalledWith('novel-a'));await waitFor(()=>expect(screen.getByText('还没有小说')).toBeTruthy())});
});
