import {useEffect,useState} from 'react';
import {Badge, Button, EmptyState, Panel} from '../ui/primitives';
import {api} from '../api';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import './novel.css';

export type StoryDatabaseKind='outline'|'volumes'|'scenes'|'story_routes'|'characters'|'world'|'locations'|'timeline'|'foreshadowing'|'relationships';
export type StoryDatabaseRecord={id:string;title:string;summary?:string;status?:string};
export type StoryDatabaseSection={kind:StoryDatabaseKind;records:StoryDatabaseRecord[];availability?:'available'|'partial'|'unavailable';loading?:boolean;error?:string|null};
const labels:Record<StoryDatabaseKind,string>={outline:'小说大纲',volumes:'卷规划',scenes:'场景规划',story_routes:'剧情路线',characters:'角色',world:'世界观',locations:'地点',timeline:'时间线',foreshadowing:'伏笔',relationships:'人物关系'};

export function StoryDatabase({sections,activeKind,onSelectKind,onSelectRecord}:{sections:StoryDatabaseSection[];activeKind:StoryDatabaseKind;onSelectKind:(kind:StoryDatabaseKind)=>void;onSelectRecord?:(kind:StoryDatabaseKind,id:string)=>void}){
  const section=sections.find(item=>item.kind===activeKind);
  const [relationshipFilter,setRelationshipFilter]=useState('');
  const records=section?.kind==='relationships'&&relationshipFilter.trim()?section.records.filter(record=>`${record.title} ${record.summary||''} ${record.status||''}`.toLocaleLowerCase().includes(relationshipFilter.trim().toLocaleLowerCase())):section?.records||[];
  return <Panel className="novel-story-database" title="故事资料库"><div className="novel-tabs" role="tablist" aria-label="故事资料分类">{sections.map(item=><button key={item.kind} role="tab" aria-selected={item.kind===activeKind} onClick={()=>onSelectKind(item.kind)}>{labels[item.kind]}{item.availability==='partial'&&<Badge tone="warning">部分可用</Badge>}{item.availability==='unavailable'&&<Badge>暂未开放</Badge>}</button>)}</div>
    {!section?<EmptyState title="暂无资料分类" detail="当前项目还没有可用的故事资料。"/>:section.availability==='unavailable'?<EmptyState title={`${labels[section.kind]}暂未开放`} detail="此能力尚未接入，现有作品内容不会受影响。"/>:section.loading?<p role="status">正在加载{labels[section.kind]}…</p>:section.error?<div className="novel-error" role="alert"><strong>无法加载{labels[section.kind]}</strong><p>{section.error}</p></div>:!section.records.length?<EmptyState title={`还没有${labels[section.kind]}记录`} detail="创建内容后，相关资料会显示在这里。"/>:<>{section.kind==='relationships'&&<><label className="relationship-filter">筛选关系<input value={relationshipFilter} onChange={event=>setRelationshipFilter(event.target.value)} placeholder="人物、关系类型或说明" /></label><div className="relationship-graph" aria-label="人物关系图谱">{records.map(record=><div className="relationship-edge" key={`graph-${record.id}`}><strong>{record.title}</strong>{record.status&&<Badge>{record.status}</Badge>}<small>{record.summary||'未填写关系说明'}</small></div>)}</div></>}<ul className="novel-record-list">{records.map(record=><li key={record.id}><button onClick={()=>onSelectRecord?.(section.kind,record.id)}><strong>{record.title}</strong>{record.status&&<Badge>{record.status}</Badge>}{record.summary&&<p>{record.summary}</p>}</button></li>)}</ul></>}
  </Panel>;
}

export function WorldSummaryEditor({value='',saving=false,onSave}:{value?:string;saving?:boolean;onSave:(value:string)=>Promise<void>|void}){
  const [draft,setDraft]=useState(value),[saved,setSaved]=useState('');
  useEffect(()=>setDraft(value),[value]);
  return <section className="novel-draft-review" aria-labelledby="world-summary-title">
    <header><strong id="world-summary-title">世界观概要</strong><Badge tone={draft===value?'success':'warning'}>{draft===value?'已保存':'未保存'}</Badge></header>
    <label>核心设定<textarea value={draft} onChange={event=>{setDraft(event.target.value);setSaved('')}} placeholder="描述世界规则、时代背景、力量体系和不可违背的设定。"/></label>
    <p className="novel-help">概要会进入小说上下文，帮助后续生成保持世界规则一致。</p>
    <p role="status" aria-live="polite">{saved}</p>
    <div className="novel-actions"><Button variant="primary" disabled={saving||draft===value} onClick={async()=>{await onSave(draft.trim());setSaved('世界观概要已保存。')}}>{saving?'正在保存…':'保存世界观概要'}</Button></div>
  </section>
}
export function WorldRulesPanel({novelId}:{novelId:string}){
 const qc=useQueryClient(); const [status,setStatus]=useState(''); const rules=useQuery({queryKey:['world-rules',novelId,status],queryFn:()=>api.worldRules(novelId,status||undefined),enabled:!!novelId}); const [statement,setStatement]=useState(''); const [forbidden,setForbidden]=useState('');
 const create=useMutation({mutationFn:()=>api.createWorldRule(novelId,{statement,forbidden_terms:forbidden.split(/[,，\n]/).map(item=>item.trim()).filter(Boolean)}),onSuccess:()=>{setStatement('');setForbidden('');qc.invalidateQueries({queryKey:['world-rules',novelId]})}});
 const review=useMutation({mutationFn:({id,approve}:{id:string;approve:boolean})=>approve?api.approveLoreProposal(novelId,id):api.rejectLoreProposal(novelId,id),onSuccess:()=>qc.invalidateQueries({queryKey:['world-rules',novelId]})});
 return <section className="novel-draft-review"><header><strong>世界规则库</strong><Badge tone="neutral">{rules.data?.items?.length||0} 条</Badge></header><label>审核状态<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部状态</option><option value="PENDING">待审核</option><option value="APPROVED">已批准</option><option value="REJECTED">已拒绝</option></select></label><label>新增规则<textarea value={statement} onChange={e=>setStatement(e.target.value)} placeholder="例如：施放能力会消耗记忆，不能连续使用。" /></label><label>违规词或模式<input value={forbidden} onChange={e=>setForbidden(e.target.value)} placeholder="用逗号分隔，例如：永生,无需代价" /><small className="novel-help">连续性检查会在事件、地点和知识内容中搜索这些词。</small></label><Button variant="primary" disabled={!statement.trim()||create.isPending} onClick={()=>create.mutate()}>提交待审核规则</Button>{(create.error||review.error)&&<p role="alert">规则操作失败，请检查权限或稍后重试。</p>}<div>{(rules.data?.items||[]).map((rule:any)=>{const terms=rule.payload?.forbidden_terms||rule.payload?.forbidden||[]; return <div key={rule.id} className="novel-help"><span>{rule.payload?.statement} · {rule.status}{terms.length?` · 约束：${terms.join('、')}`:''}</span>{rule.status==='PENDING'&&<><Button variant="ghost" disabled={review.isPending} onClick={()=>review.mutate({id:rule.id,approve:true})}>批准</Button><Button variant="ghost" disabled={review.isPending} onClick={()=>review.mutate({id:rule.id,approve:false})}>拒绝</Button></>}</div>})}</div></section>;
}
export function RelationshipGraph({relationships=[],characters=[]}:{relationships:any[];characters:any[]}){const names=new Map(characters.map(item=>[String(item.id),String(item.name||item.title||item.id)]));return <section className="novel-draft-review"><header><strong>人物关系图谱</strong><Badge tone="neutral">{relationships.length} 条关系</Badge></header><div className="relationship-graph">{relationships.map(item=><div className="relationship-edge" key={item.id}><b>{names.get(String(item.source_character_id))||item.source_character_id}</b><span>{item.relationship_type||item.type||'关系'}</span><b>{names.get(String(item.target_character_id))||item.target_character_id}</b></div>)}</div></section>}

export type CharacterDraft={id:string;name:string;age?:number;role:string;personality:string;goal:string;current_location:string;status:string};
const emptyCharacter:CharacterDraft={id:'',name:'',role:'',personality:'',goal:'',current_location:'',status:'ALIVE'};
export function CharacterEvolutionPanel({novelId,characterId,characterName}:{novelId:string;characterId?:string;characterName?:string}){
 const qc=useQueryClient(); const [event,setEvent]=useState(''); const [phase,setPhase]=useState(''); const [chapter,setChapter]=useState(''); const [initialState,setInitialState]=useState(''); const [change,setChange]=useState(''); const [result,setResult]=useState('');
 const rows=useQuery({queryKey:['character-evolution',novelId,characterId],queryFn:()=>api.characterEvolution(novelId,characterId!),enabled:!!novelId&&!!characterId});
 const create=useMutation({mutationFn:()=>api.createCharacterEvolution(novelId,characterId!,{event,phase,chapter:chapter?Number(chapter):null,initial_state:initialState,psychological_change:change,resulting_state:result,status:'DRAFT'}),onSuccess:()=>{setEvent('');setPhase('');setChapter('');setInitialState('');setChange('');setResult('');qc.invalidateQueries({queryKey:['character-evolution',novelId,characterId]})}});
 if(!characterId) return <section className="novel-draft-review"><header><strong>人物成长路线</strong></header><p className="novel-help">先在上方人物列表中选择一个角色。</p></section>;
 return <section className="novel-draft-review"><header><strong>{characterName||'人物'}的成长路线</strong><Badge tone="neutral">{rows.data?.total||0} 个节点</Badge></header><label>发生章节<input type="number" min="1" value={chapter} onChange={e=>setChapter(e.target.value)} /></label><label>阶段<input value={phase} onChange={e=>setPhase(e.target.value)} placeholder="例如：觉醒、转折、终局" /></label><label>关键事件<textarea value={event} onChange={e=>setEvent(e.target.value)} placeholder="描述推动人物变化的关键事件。" /></label><label>事件前状态<textarea value={initialState} onChange={e=>setInitialState(e.target.value)} /></label><label>心理变化<textarea value={change} onChange={e=>setChange(e.target.value)} /></label><label>事件后状态<textarea value={result} onChange={e=>setResult(e.target.value)} /></label><Button variant="primary" disabled={!event.trim()||create.isPending} onClick={()=>create.mutate()}>记录成长节点</Button><div>{(rows.data?.items||[]).map((item:any)=><div key={item.id} className="novel-help"><strong>{item.chapter?`第 ${item.chapter} 章 · `:''}{item.phase||'未命名阶段'}</strong><p>{item.event}</p>{item.psychological_change&&<small>心理变化：{item.psychological_change}</small>}</div>)}</div></section>;
}
export function CharacterConsistencyPanel({novelId,draft,chapter,characters}:{novelId:string;draft:string;chapter:number;characters:any[]}){
 const key=`character-consistency-history:${novelId}`; const [findings,setFindings]=useState<any[]>([]); const [history,setHistory]=useState<any[]>(()=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}}); const [error,setError]=useState(''); const [running,setRunning]=useState(false);
 async function run(){setRunning(true);setError('');try{const result=await api.characterConsistencyCheck(novelId,{draft,chapter,characters});const next=result.findings||[];setFindings(next);const entry={id:`${Date.now()}`,at:new Date().toISOString(),chapter,count:next.length};const updated=[entry,...history].slice(0,10);setHistory(updated);localStorage.setItem(key,JSON.stringify(updated))}catch(reason){setError(String(reason))}finally{setRunning(false)}}
 return <section className="novel-draft-review"><header><strong>人物一致性检查</strong><Badge tone={findings.length?'warning':'neutral'}>{findings.length?`${findings.length} 个问题`:'未运行'}</Badge></header><p className="novel-help">检查当前章节正文与人物档案中的状态、年龄和秘密约束。</p><Button variant="primary" disabled={running||!draft.trim()} onClick={run}>{running?'检查中…':'检查当前章节'}</Button>{error&&<p role="alert">{error}</p>}{findings.map(item=><div key={item.id} className="novel-help"><Badge tone="warning">{item.code}</Badge> {item.description}</div>)}{history.length>0&&<details><summary>最近检查记录（{history.length}）</summary>{history.map(item=><div key={item.id} className="novel-help">{new Date(item.at).toLocaleString()} · 第 {item.chapter} 章 · {item.count} 个问题</div>)}</details>}</section>;
}
export function CharacterEditor({value,locations=[],saving=false,onSave}:{value?:Partial<CharacterDraft>;locations?:{id:string;name:string}[];saving?:boolean;onSave:(value:CharacterDraft)=>Promise<void>|void}){
  const [draft,setDraft]=useState<CharacterDraft>({...emptyCharacter,...value});
  useEffect(()=>setDraft({...emptyCharacter,...value}),[value]);
  const set=(key:keyof CharacterDraft,value:string|number|undefined)=>setDraft(current=>({...current,[key]:value}));
  return <section className="novel-draft-review" aria-labelledby="character-editor-title"><header><strong id="character-editor-title">{draft.id?'编辑人物':'新建人物'}</strong><Badge tone={draft.name.trim()?'info':'warning'}>{draft.name.trim()?'可保存':'需要姓名'}</Badge></header>
    <label>姓名<input value={draft.name} onChange={event=>set('name',event.target.value)}/></label>
    <label>身份 / 定位<input value={draft.role} onChange={event=>set('role',event.target.value)} placeholder="例如：调查记者、王室继承人"/></label>
    <label>年龄<input type="number" value={draft.age??''} onChange={event=>set('age',event.target.value?Number(event.target.value):undefined)}/></label>
    <label>性格<textarea value={draft.personality} onChange={event=>set('personality',event.target.value)}/></label>
    <label>当前目标<textarea value={draft.goal} onChange={event=>set('goal',event.target.value)}/></label>
    <label>当前位置<input list="character-location-options" value={draft.current_location} onChange={event=>set('current_location',event.target.value)}/><datalist id="character-location-options">{locations.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</datalist></label>
    <label>状态<select value={draft.status} onChange={event=>set('status',event.target.value)}><option value="ALIVE">存活</option><option value="MISSING">失踪</option><option value="DEAD">死亡</option><option value="UNKNOWN">未知</option></select></label>
    <div className="novel-actions"><Button variant="primary" disabled={saving||!draft.name.trim()} onClick={()=>onSave({...draft,id:draft.id||draft.name.trim()})}>{saving?'正在保存…':'保存人物'}</Button></div>
  </section>;
}

export type LocationDraft={id:string;name:string;location_type:string;description:string;rules:string;atmosphere:string;status:string};
const emptyLocation:LocationDraft={id:'',name:'',location_type:'',description:'',rules:'',atmosphere:'',status:'ACTIVE'};
export function LocationEditor({value,saving=false,onSave}:{value?:Partial<LocationDraft>;saving?:boolean;onSave:(value:LocationDraft)=>Promise<void>|void}){
  const [draft,setDraft]=useState<LocationDraft>({...emptyLocation,...value});useEffect(()=>setDraft({...emptyLocation,...value}),[value]);const set=(key:keyof LocationDraft,value:string)=>setDraft(current=>({...current,[key]:value}));
  return <section className="novel-draft-review" aria-labelledby="location-editor-title"><header><strong id="location-editor-title">{draft.id?'编辑地点':'新建地点'}</strong><Badge tone={draft.name.trim()?'info':'warning'}>{draft.name.trim()?'可保存':'需要名称'}</Badge></header>
    <label>地点名称<input value={draft.name} onChange={event=>set('name',event.target.value)}/></label><label>地点类型<input value={draft.location_type} onChange={event=>set('location_type',event.target.value)} placeholder="城市、建筑、区域、星球…"/></label><label>地点描述<textarea value={draft.description} onChange={event=>set('description',event.target.value)}/></label><label>特殊规则<textarea value={draft.rules} onChange={event=>set('rules',event.target.value)} placeholder="进入条件、力量限制、社会规则等"/></label><label>氛围<textarea value={draft.atmosphere} onChange={event=>set('atmosphere',event.target.value)}/></label><label>状态<select value={draft.status} onChange={event=>set('status',event.target.value)}><option value="ACTIVE">可用</option><option value="DESTROYED">已毁</option><option value="INACCESSIBLE">不可进入</option><option value="UNKNOWN">未知</option></select></label><div className="novel-actions"><Button variant="primary" disabled={saving||!draft.name.trim()} onClick={()=>onSave({...draft,id:draft.id||draft.name.trim()})}>{saving?'正在保存…':'保存地点'}</Button></div>
  </section>;
}

export type TimelineDraft={id:string;title:string;sequence:number;time:string;description:string;location:string;characters:string[];chapter_id:string;status:string};
const emptyTimeline:TimelineDraft={id:'',title:'',sequence:1,time:'',description:'',location:'',characters:[],chapter_id:'',status:'CONFIRMED'};
export function TimelineEditor({value,locations=[],characters=[],chapters=[],saving=false,onSave}:{value?:Partial<TimelineDraft>;locations?:{id:string;name:string}[];characters?:{id:string;name:string}[];chapters?:{id:string;title:string}[];saving?:boolean;onSave:(value:TimelineDraft)=>Promise<void>|void}){
  const [draft,setDraft]=useState<TimelineDraft>({...emptyTimeline,...value});useEffect(()=>setDraft({...emptyTimeline,...value}),[value]);const set=(key:keyof TimelineDraft,value:string|number|string[])=>setDraft(current=>({...current,[key]:value}));
  return <section className="novel-draft-review" aria-labelledby="timeline-editor-title"><header><strong id="timeline-editor-title">{draft.id?'编辑时间线事件':'新建时间线事件'}</strong><Badge tone={draft.title.trim()?'info':'warning'}>{draft.title.trim()?'可保存':'需要标题'}</Badge></header>
    <label>事件标题<input value={draft.title} onChange={event=>set('title',event.target.value)}/></label><label>顺序<input type="number" min="0" value={draft.sequence} onChange={event=>set('sequence',Number(event.target.value))}/></label><label>故事时间<input value={draft.time} onChange={event=>set('time',event.target.value)} placeholder="例如：帝国历 1203 年冬"/></label><label>事件描述<textarea value={draft.description} onChange={event=>set('description',event.target.value)}/></label><label>地点<select value={draft.location} onChange={event=>set('location',event.target.value)}><option value="">未关联地点</option>{locations.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>关联人物<select multiple value={draft.characters} onChange={event=>set('characters',[...event.target.selectedOptions].map(option=>option.value))}>{characters.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>关联章节<select value={draft.chapter_id} onChange={event=>set('chapter_id',event.target.value)}><option value="">未关联章节</option>{chapters.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>状态<select value={draft.status} onChange={event=>set('status',event.target.value)}><option value="CONFIRMED">已确认</option><option value="PLANNED">计划中</option><option value="DISPUTED">存疑</option></select></label><div className="novel-actions"><Button variant="primary" disabled={saving||!draft.title.trim()} onClick={()=>onSave({...draft,id:draft.id||draft.title.trim()})}>{saving?'正在保存…':'保存时间线事件'}</Button></div>
  </section>;
}

export type ForeshadowingDraft={id:string;title:string;description:string;planted_chapter?:number;target_chapter?:number;status:string;characters:string[];events:string[]};
const emptyForeshadowing:ForeshadowingDraft={id:'',title:'',description:'',status:'OPEN',characters:[],events:[]};
export function ForeshadowingEditor({value,characters=[],events=[],saving=false,onSave}:{value?:Partial<ForeshadowingDraft>;characters?:{id:string;name:string}[];events?:{id:string;title:string}[];saving?:boolean;onSave:(value:ForeshadowingDraft)=>Promise<void>|void}){
  const [draft,setDraft]=useState<ForeshadowingDraft>({...emptyForeshadowing,...value});useEffect(()=>setDraft({...emptyForeshadowing,...value}),[value]);const set=(key:keyof ForeshadowingDraft,value:string|number|undefined|string[])=>setDraft(current=>({...current,[key]:value}));
  return <section className="novel-draft-review" aria-labelledby="foreshadowing-editor-title"><header><strong id="foreshadowing-editor-title">{draft.id?'编辑伏笔':'新建伏笔'}</strong><Badge tone={draft.title.trim()?'info':'warning'}>{draft.title.trim()?'可保存':'需要标题'}</Badge></header>
    <label>伏笔标题<input value={draft.title} onChange={event=>set('title',event.target.value)}/></label><label>描述<textarea value={draft.description} onChange={event=>set('description',event.target.value)} placeholder="记录线索、读者预期与计划回收方式。"/></label><label>埋设章节<input type="number" min="1" value={draft.planted_chapter??''} onChange={event=>set('planted_chapter',event.target.value?Number(event.target.value):undefined)}/></label><label>目标回收章节<input type="number" min="1" value={draft.target_chapter??''} onChange={event=>set('target_chapter',event.target.value?Number(event.target.value):undefined)}/></label><label>关联人物<select multiple value={draft.characters} onChange={event=>set('characters',[...event.target.selectedOptions].map(option=>option.value))}>{characters.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>关联事件<select multiple value={draft.events} onChange={event=>set('events',[...event.target.selectedOptions].map(option=>option.value))}>{events.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>状态<select value={draft.status} onChange={event=>set('status',event.target.value)}><option value="OPEN">待回收</option><option value="PLANTED">已埋设</option><option value="PAID_OFF">已回收</option><option value="ABANDONED">已放弃</option></select></label><div className="novel-actions"><Button variant="primary" disabled={saving||!draft.title.trim()} onClick={()=>onSave({...draft,id:draft.id||draft.title.trim()})}>{saving?'正在保存…':'保存伏笔'}</Button></div>
  </section>;
}
export function ForeshadowingTrackerPanel({novelId,records=[],currentChapter=0}:{novelId?:string;records:any[];currentChapter?:number}){
 const reminders=useQuery({queryKey:['foreshadowing-reminders',novelId,currentChapter],queryFn:()=>api.foreshadowingReminders(novelId!,currentChapter),enabled:!!novelId&&currentChapter>0}); const source=reminders.data?.pending?reminders.data.pending:records; const open=source.filter(item=>['OPEN','PLANTED'].includes(String(item.status||'OPEN'))); const overdue=reminders.data?.overdue||open.filter(item=>item.target_chapter&&currentChapter>=Number(item.target_chapter));
 return <section className="novel-draft-review"><header><strong>伏笔追踪与回收提醒</strong><Badge tone={overdue.length?'warning':'success'}>{overdue.length?`${overdue.length} 项待回收`:'暂无逾期'}</Badge></header>{!source.length?<p className="novel-help">还没有伏笔记录。</p>:<><div className="novel-help">共 {source.length} 项，未回收 {open.length} 项，已回收 {(reminders.data?.paid_off||[]).length||Math.max(0,source.length-open.length)} 项。</div><div>{open.map(item=><div key={item.id} className="novel-help"><strong>{item.title||'未命名伏笔'}</strong>{item.target_chapter&&<span> · 目标第 {item.target_chapter} 章</span>}{overdue.some((row:any)=>row.id===item.id)&&<Badge tone="warning">建议回收</Badge>}<p>{item.description||'未填写描述'}</p></div>)}</div></>}</section>;
}

export type RelationshipDraft={id:string;source_character_id:string;target_character_id:string;relationship_type:string;description:string;status:string;valid_from_event_id:string;valid_to_event_id:string;certainty:string};
const emptyRelationship:RelationshipDraft={id:'',source_character_id:'',target_character_id:'',relationship_type:'FRIEND',description:'',status:'ACTIVE',valid_from_event_id:'',valid_to_event_id:'',certainty:'CONFIRMED'};
export function RelationshipEditor({value,characters=[],events=[],saving=false,onSave}:{value?:Partial<RelationshipDraft>;characters?:{id:string;name:string}[];events?:{id:string;title:string}[];saving?:boolean;onSave:(value:RelationshipDraft)=>Promise<void>|void}){
  const [draft,setDraft]=useState<RelationshipDraft>({...emptyRelationship,...value});useEffect(()=>setDraft({...emptyRelationship,...value}),[value]);const set=(key:keyof RelationshipDraft,value:string)=>setDraft(current=>({...current,[key]:value}));const valid=draft.source_character_id&&draft.target_character_id&&draft.source_character_id!==draft.target_character_id;
  return <section className="novel-draft-review" aria-labelledby="relationship-editor-title"><header><strong id="relationship-editor-title">{draft.id?'编辑人物关系':'新建人物关系'}</strong><Badge tone={valid?'info':'warning'}>{valid?'可保存':'请选择两名不同人物'}</Badge></header>
    <label>人物 A<select value={draft.source_character_id} onChange={event=>set('source_character_id',event.target.value)}><option value="">请选择人物</option>{characters.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>人物 B<select value={draft.target_character_id} onChange={event=>set('target_character_id',event.target.value)}><option value="">请选择人物</option>{characters.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>关系类型<select value={draft.relationship_type} onChange={event=>set('relationship_type',event.target.value)}><option value="FAMILY">家族</option><option value="FRIEND">朋友</option><option value="ENEMY">敌人</option><option value="MENTOR">师徒</option><option value="ROMANCE">爱情</option><option value="INTEREST">利益</option><option value="OTHER">其他</option></select></label><label>关系描述<textarea value={draft.description} onChange={event=>set('description',event.target.value)}/></label><label>关系开始事件<select value={draft.valid_from_event_id} onChange={event=>set('valid_from_event_id',event.target.value)}><option value="">未指定</option>{events.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>关系结束事件<select value={draft.valid_to_event_id} onChange={event=>set('valid_to_event_id',event.target.value)}><option value="">仍然有效</option>{events.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>状态<select value={draft.status} onChange={event=>set('status',event.target.value)}><option value="ACTIVE">有效</option><option value="ENDED">已结束</option><option value="HIDDEN">隐藏</option></select></label><label>可信度<select value={draft.certainty} onChange={event=>set('certainty',event.target.value)}><option value="CONFIRMED">已确认</option><option value="LIKELY">可能</option><option value="UNKNOWN">未知</option></select></label><div className="novel-actions"><Button variant="primary" disabled={saving||!valid} onClick={()=>onSave({...draft,id:draft.id||`${draft.source_character_id}-${draft.target_character_id}`})}>{saving?'正在保存…':'保存人物关系'}</Button></div>
  </section>;
}

export type OutlineDraft={theme:string;premise:string;structure:string;beginning:string;middle:string;ending:string;main_conflict:string;climax:string;status:string};
const emptyOutline:OutlineDraft={theme:'',premise:'',structure:'THREE_ACT',beginning:'',middle:'',ending:'',main_conflict:'',climax:'',status:'DRAFT'};
export function OutlineEditor({value,saving=false,onSave}:{value?:Partial<OutlineDraft>;saving?:boolean;onSave:(value:OutlineDraft)=>Promise<void>|void}){
  const [draft,setDraft]=useState<OutlineDraft>({...emptyOutline,...value});useEffect(()=>setDraft({...emptyOutline,...value}),[value]);const set=(key:keyof OutlineDraft,value:string)=>setDraft(current=>({...current,[key]:value}));
  return <section className="novel-draft-review" aria-labelledby="outline-editor-title"><header><strong id="outline-editor-title">小说大纲</strong><Badge tone={draft.premise.trim()?'info':'warning'}>{draft.premise.trim()?'可保存':'需要故事前提'}</Badge></header>
    <label>主题<input value={draft.theme} onChange={event=>set('theme',event.target.value)} placeholder="例如：信任、身份与代价"/></label><label>故事前提<textarea value={draft.premise} onChange={event=>set('premise',event.target.value)} placeholder="用一段话说明主角、目标、阻力和核心悬念。"/></label><label>结构<select value={draft.structure} onChange={event=>set('structure',event.target.value)}><option value="THREE_ACT">三幕结构</option><option value="FOUR_ACT">四幕结构</option><option value="HERO_JOURNEY">英雄之旅</option><option value="CUSTOM">自定义</option></select></label><label>开端<textarea value={draft.beginning} onChange={event=>set('beginning',event.target.value)}/></label><label>发展<textarea value={draft.middle} onChange={event=>set('middle',event.target.value)}/></label><label>结局<textarea value={draft.ending} onChange={event=>set('ending',event.target.value)}/></label><label>主要冲突<textarea value={draft.main_conflict} onChange={event=>set('main_conflict',event.target.value)}/></label><label>高潮<textarea value={draft.climax} onChange={event=>set('climax',event.target.value)}/></label><label>状态<select value={draft.status} onChange={event=>set('status',event.target.value)}><option value="DRAFT">草稿</option><option value="ACTIVE">采用中</option><option value="LOCKED">已锁定</option></select></label><div className="novel-actions"><Button variant="primary" disabled={saving||!draft.premise.trim()} onClick={()=>onSave(draft)}>{saving?'正在保存…':'保存小说大纲'}</Button></div>
  </section>;
}

export type VolumeDraft={id:string;title:string;sequence:number;goal:string;summary:string;start_chapter?:number;end_chapter?:number;status:string};
const emptyVolume:VolumeDraft={id:'',title:'',sequence:1,goal:'',summary:'',status:'PLANNED'};
export function VolumeEditor({value,saving=false,onSave}:{value?:Partial<VolumeDraft>;saving?:boolean;onSave:(value:VolumeDraft)=>Promise<void>|void}){
  const [draft,setDraft]=useState<VolumeDraft>({...emptyVolume,...value});useEffect(()=>setDraft({...emptyVolume,...value}),[value]);const set=(key:keyof VolumeDraft,value:string|number|undefined)=>setDraft(current=>({...current,[key]:value}));const rangeValid=!draft.start_chapter||!draft.end_chapter||draft.end_chapter>=draft.start_chapter;
  return <section className="novel-draft-review" aria-labelledby="volume-editor-title"><header><strong id="volume-editor-title">{draft.id?'编辑卷规划':'新建卷规划'}</strong><Badge tone={draft.title.trim()&&rangeValid?'info':'warning'}>{!draft.title.trim()?'需要标题':rangeValid?'可保存':'章节范围无效'}</Badge></header>
    <label>卷标题<input value={draft.title} onChange={event=>set('title',event.target.value)}/></label><label>顺序<input type="number" min="1" value={draft.sequence} onChange={event=>set('sequence',Number(event.target.value))}/></label><label>本卷目标<textarea value={draft.goal} onChange={event=>set('goal',event.target.value)} placeholder="说明本卷推动的主线、人物变化和读者预期。"/></label><label>本卷摘要<textarea value={draft.summary} onChange={event=>set('summary',event.target.value)}/></label><label>起始章节<input type="number" min="1" value={draft.start_chapter??''} onChange={event=>set('start_chapter',event.target.value?Number(event.target.value):undefined)}/></label><label>结束章节<input type="number" min="1" value={draft.end_chapter??''} onChange={event=>set('end_chapter',event.target.value?Number(event.target.value):undefined)}/></label><label>状态<select value={draft.status} onChange={event=>set('status',event.target.value)}><option value="PLANNED">计划中</option><option value="WRITING">创作中</option><option value="COMPLETED">已完成</option><option value="LOCKED">已锁定</option></select></label><div className="novel-actions"><Button variant="primary" disabled={saving||!draft.title.trim()||!rangeValid} onClick={()=>onSave({...draft,id:draft.id||draft.title.trim()})}>{saving?'正在保存…':'保存卷规划'}</Button></div>
  </section>;
}

export type SceneDraft={id:string;title:string;sequence:number;volume_id:string;chapter_id:string;location_id:string;characters:string[];purpose:string;conflict:string;outcome:string;status:string};
const emptyScene:SceneDraft={id:'',title:'',sequence:1,volume_id:'',chapter_id:'',location_id:'',characters:[],purpose:'',conflict:'',outcome:'',status:'PLANNED'};
export function SceneEditor({value,volumes=[],chapters=[],locations=[],characters=[],saving=false,onSave}:{value?:Partial<SceneDraft>;volumes?:{id:string;title:string}[];chapters?:{id:string;title:string}[];locations?:{id:string;name:string}[];characters?:{id:string;name:string}[];saving?:boolean;onSave:(value:SceneDraft)=>Promise<void>|void}){
  const [draft,setDraft]=useState<SceneDraft>({...emptyScene,...value});useEffect(()=>setDraft({...emptyScene,...value}),[value]);const set=(key:keyof SceneDraft,value:string|number|string[])=>setDraft(current=>({...current,[key]:value}));
  return <section className="novel-draft-review" aria-labelledby="scene-editor-title"><header><strong id="scene-editor-title">{draft.id?'编辑场景':'新建场景'}</strong><Badge tone={draft.title.trim()&&draft.chapter_id?'info':'warning'}>{!draft.title.trim()?'需要标题':draft.chapter_id?'可保存':'需要关联章节'}</Badge></header>
    <label>场景标题<input value={draft.title} onChange={event=>set('title',event.target.value)}/></label><label>场景顺序<input type="number" min="1" value={draft.sequence} onChange={event=>set('sequence',Number(event.target.value))}/></label><label>所属卷<select value={draft.volume_id} onChange={event=>set('volume_id',event.target.value)}><option value="">未关联卷</option>{volumes.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>所属章节<select value={draft.chapter_id} onChange={event=>set('chapter_id',event.target.value)}><option value="">请选择章节</option>{chapters.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>地点<select value={draft.location_id} onChange={event=>set('location_id',event.target.value)}><option value="">未关联地点</option>{locations.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>出场人物<select multiple value={draft.characters} onChange={event=>set('characters',[...event.target.selectedOptions].map(option=>option.value))}>{characters.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>场景目标<textarea value={draft.purpose} onChange={event=>set('purpose',event.target.value)}/></label><label>场景冲突<textarea value={draft.conflict} onChange={event=>set('conflict',event.target.value)}/></label><label>场景结果<textarea value={draft.outcome} onChange={event=>set('outcome',event.target.value)}/></label><label>状态<select value={draft.status} onChange={event=>set('status',event.target.value)}><option value="PLANNED">计划中</option><option value="DRAFTED">已有草稿</option><option value="COMPLETED">已完成</option><option value="CUT">已删除</option></select></label><div className="novel-actions"><Button variant="primary" disabled={saving||!draft.title.trim()||!draft.chapter_id} onClick={()=>onSave({...draft,id:draft.id||draft.title.trim()})}>{saving?'正在保存…':'保存场景'}</Button></div>
  </section>;
}

export type StoryRouteDraft={id:string;title:string;route_type:string;parent_route_id:string;divergence_chapter?:number;divergence_summary:string;summary:string;status:string;shared_until_chapter?:number};
const emptyStoryRoute:StoryRouteDraft={id:'',title:'',route_type:'ORIGINAL',parent_route_id:'',divergence_summary:'',summary:'',status:'DRAFT'};
export function StoryRouteEditor({value,routes=[],saving=false,onSave}:{value?:Partial<StoryRouteDraft>;routes?:{id:string;title:string}[];saving?:boolean;onSave:(value:StoryRouteDraft)=>Promise<void>|void}){
  const [draft,setDraft]=useState<StoryRouteDraft>({...emptyStoryRoute,...value});useEffect(()=>setDraft({...emptyStoryRoute,...value}),[value]);const set=(key:keyof StoryRouteDraft,value:string|number|undefined)=>setDraft(current=>({...current,[key]:value}));const child=draft.route_type!=='ORIGINAL';
  return <section className="novel-draft-review" aria-labelledby="story-route-editor-title"><header><strong id="story-route-editor-title">{draft.id?'编辑剧情路线':'新建剧情路线'}</strong><Badge tone={draft.title.trim()&&(!child||draft.parent_route_id)?'info':'warning'}>{!draft.title.trim()?'需要标题':child&&!draft.parent_route_id?'需要父路线':'可保存'}</Badge></header>
    <label>路线标题<input value={draft.title} onChange={event=>set('title',event.target.value)}/></label><label>路线类型<select value={draft.route_type} onChange={event=>set('route_type',event.target.value)}><option value="ORIGINAL">原剧情</option><option value="ENDING_A">结局 A</option><option value="ENDING_B">结局 B</option><option value="HIDDEN">隐藏路线</option><option value="ALTERNATE">其他分支</option></select></label><label>父路线<select value={draft.parent_route_id} onChange={event=>set('parent_route_id',event.target.value)} disabled={!child}><option value="">无父路线</option>{routes.filter(item=>item.id!==draft.id).map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>分歧章节<input type="number" min="1" value={draft.divergence_chapter??''} onChange={event=>set('divergence_chapter',event.target.value?Number(event.target.value):undefined)}/></label><label>共享基线截止章节<input type="number" min="1" value={draft.shared_until_chapter??''} onChange={event=>set('shared_until_chapter',event.target.value?Number(event.target.value):undefined)}/></label><label>分歧说明<textarea value={draft.divergence_summary} onChange={event=>set('divergence_summary',event.target.value)}/></label><label>路线摘要<textarea value={draft.summary} onChange={event=>set('summary',event.target.value)}/></label><label>状态<select value={draft.status} onChange={event=>set('status',event.target.value)}><option value="DRAFT">草稿</option><option value="ACTIVE">采用中</option><option value="COMPLETED">已完成</option><option value="ARCHIVED">已归档</option></select></label><div className="novel-actions"><Button variant="primary" disabled={saving||!draft.title.trim()||(child&&!draft.parent_route_id)} onClick={()=>onSave({...draft,id:draft.id||draft.title.trim(),parent_route_id:child?draft.parent_route_id:''})}>{saving?'正在保存…':'保存剧情路线'}</Button></div>
  </section>;
}
