// @vitest-environment jsdom
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { buildVideoTimeline, buildTimelineTracks, buildTimelineExport, buildEdlExport, getTransitionStatus, parseKeyframeMarkers, parseShotDuration, VideoTimeline } from './VideoTimeline';
import { cleanup, fireEvent, render, screen } from '@testing-library/react';
describe('VideoTimeline', () => { it('parses durations and builds contiguous ranges', () => { expect(parseShotDuration('4s')).toBe(4); expect(buildVideoTimeline([{ shot_id:'a', name:'一', duration:'4s', camera:'', action:'' }, { shot_id:'b', name:'二', duration:'2.5 秒', camera:'', action:'' }]).map(item=>[item.start,item.end])).toEqual([[0,4],[4,6.5]]); }); });
beforeEach(() => cleanup());
it('reorders shots with accessible controls', () => { const onReorder=vi.fn(); render(<VideoTimeline shots={[{shot_id:'a',name:'一',duration:'2s',camera:'',action:''},{shot_id:'b',name:'二',duration:'3s',camera:'',action:''}]} onReorder={onReorder}/>); fireEvent.click(screen.getByLabelText('镜头 一 下移')); expect(onReorder).toHaveBeenCalledWith([expect.objectContaining({shot_id:'b'}),expect.objectContaining({shot_id:'a'})]); });
it('edits a clip duration', () => { const onDurationChange=vi.fn(); render(<VideoTimeline shots={[{shot_id:'a',name:'一',duration:'2s',camera:'',action:''}]} onDurationChange={onDurationChange}/>); fireEvent.change(screen.getByLabelText('镜头 一 时长'), { target: { value: '3.5' } }); expect(onDurationChange).toHaveBeenCalledWith(0, '3.5s'); });
it('edits transition duration separately', () => { const onTransitionDurationChange=vi.fn(); render(<VideoTimeline shots={[{shot_id:'a',name:'一',duration:'2s',camera:'',action:''}]} onTransitionDurationChange={onTransitionDurationChange}/>); fireEvent.change(screen.getByLabelText('镜头 一 转场时长'), { target: { value: '0.5' } }); expect(onTransitionDurationChange).toHaveBeenCalledWith(0, '0.5s'); });
it('builds subtitle and audio tracks from real shot fields', () => { const tracks=buildTimelineTracks([{shot_id:'a',name:'一',duration:'2s',camera:'',action:'',dialogue:'你好',ambience:'雨声',music:'钢琴'}]); expect(tracks[0]).toMatchObject({subtitle:'你好',audio:'雨声 / 钢琴',start:0,end:2}); });
it('exports timeline metadata and EDL without media placeholders', () => { const shots=[{shot_id:'a',name:'一',duration:'2s',camera:'',action:'',transition:'DISSOLVE',transition_duration:'0.5s'}]; expect(buildTimelineExport(shots)[0]).toMatchObject({start:0,end:2.5,shot_duration:2,transition_duration:0.5}); expect(buildEdlExport(shots)).toContain('* TRANSITION: DISSOLVE 0.5s'); expect(buildEdlExport(shots)).not.toContain('asset_uri'); });
it('edits subtitle text', () => { const onSubtitleChange=vi.fn(); render(<VideoTimeline shots={[{shot_id:'a',name:'一',duration:'2s',camera:'',action:''}]} onSubtitleChange={onSubtitleChange}/>); fireEvent.change(screen.getByLabelText('镜头 一 字幕'), { target: { value: '新的对白' } }); expect(onSubtitleChange).toHaveBeenCalledWith(0, '新的对白'); });
it('edits validated keyframe markers', () => { expect(parseKeyframeMarkers('1.2, 0.5, 3, bad, 0.5', 2)).toEqual(['0.5', '1.2']); const onKeyframesChange=vi.fn(); render(<VideoTimeline shots={[{shot_id:'a',name:'一',duration:'2s',camera:'',action:''}]} onKeyframesChange={onKeyframesChange}/>); fireEvent.change(screen.getByLabelText('镜头 一 关键帧'), { target: { value: '0.5, 1.2' } }); expect(onKeyframesChange).toHaveBeenCalledWith(0, ['0.5', '1.2']); });
it('renders keyframe markers on the video track', () => { render(<VideoTimeline shots={[{shot_id:'a',name:'一',duration:'2s',camera:'',action:'',keyframes:['0.5']}]} />); expect(screen.getByLabelText('一 关键帧 0.5 秒')).toBeTruthy(); });
it('reports honest transition status', () => { expect(getTransitionStatus({name:'一',duration:'2s',camera:'',action:''})).toBe('直接剪切'); expect(getTransitionStatus({name:'一',duration:'2s',camera:'',action:'',transition:'FADE'})).toBe('参数不完整'); expect(getTransitionStatus({name:'一',duration:'2s',camera:'',action:'',transition:'FADE',transition_duration:'0.5s'})).toBe('已配置参数'); });
it('offers split and merge controls', () => { const onSplit=vi.fn(); const onMerge=vi.fn(); render(<VideoTimeline shots={[{shot_id:'a',name:'一',duration:'2s',camera:'',action:''},{shot_id:'b',name:'二',duration:'2s',camera:'',action:''}]} onSplit={onSplit} onMerge={onMerge}/>); fireEvent.click(screen.getByLabelText('拆分镜头 一')); fireEvent.click(screen.getByLabelText('合并镜头 一')); expect(onSplit).toHaveBeenCalledWith(0, 1); expect(onMerge).toHaveBeenCalledWith(0); });
it('offers duplicate and guarded delete controls', () => { const onDuplicate=vi.fn(); const onDelete=vi.fn(); const { rerender }=render(<VideoTimeline shots={[{shot_id:'a',name:'一',duration:'2s',camera:'',action:''},{shot_id:'b',name:'二',duration:'2s',camera:'',action:''}]} onDuplicate={onDuplicate} onDelete={onDelete}/>); fireEvent.click(screen.getByLabelText('复制镜头 一')); fireEvent.click(screen.getByLabelText('删除镜头 一')); expect(onDuplicate).toHaveBeenCalledWith(0); expect(onDelete).toHaveBeenCalledWith(0); rerender(<VideoTimeline shots={[{shot_id:'a',name:'一',duration:'2s',camera:'',action:''}]} onDelete={onDelete}/>); expect((screen.getByLabelText('删除镜头 一') as HTMLButtonElement).disabled).toBe(true); });
