from enum import StrEnum


class EvidenceSourceType(StrEnum):
    CHAPTER_VERSION = "CHAPTER_VERSION"
    USER_ACTION = "USER_ACTION"
    GENERATION_JOB = "GENERATION_JOB"
    LEGACY_IMPORT = "LEGACY_IMPORT"


class EvidenceStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INVALIDATED = "INVALIDATED"


class ProposalType(StrEnum):
    CHARACTER_MEMORY = "CHARACTER_MEMORY"
    RELATIONSHIP = "RELATIONSHIP"
    EVENT = "EVENT"
    SECRET_CHANGE = "SECRET_CHANGE"
    WORLD_RULE = "WORLD_RULE"
    CANON_SUGGESTION = "CANON_SUGGESTION"


class ProposalStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class RelationRelevance(StrEnum):
    PRIMARY = "PRIMARY"
    SUPPORTING = "SUPPORTING"
    CONTRADICTING = "CONTRADICTING"


class PrivacyLevel(StrEnum):
    LOCAL_ONLY = "LOCAL_ONLY"
    CLOUD_ALLOWED = "CLOUD_ALLOWED"
    REDACT_BEFORE_CLOUD = "REDACT_BEFORE_CLOUD"

class MemoryType(StrEnum):
    EXPERIENCE="EXPERIENCE"
    STATE_CHANGE="STATE_CHANGE"
    KNOWLEDGE_CHANGE="KNOWLEDGE_CHANGE"
    RELATIONSHIP_CHANGE="RELATIONSHIP_CHANGE"

class MemoryStatus(StrEnum):
    ACTIVE="ACTIVE"
    SUPERSEDED="SUPERSEDED"
    RETRACTED="RETRACTED"

class SnapshotScope(StrEnum):
    CHAPTER="CHAPTER"
    VOLUME="VOLUME"
    NOVEL="NOVEL"
