import {QueryClient} from '@tanstack/react-query';import {afterEach,describe,expect,it,vi} from 'vitest';import {cacheCreatedNovel,shouldLoadLocalNovels} from './App';import {api,Novel} from './api';import {acceptedParagraphs,isVersionConflict,splitParagraphs} from './ux';
afterEach(()=>vi.unstubAllGlobals());
function mock(body:any={}){const fetch=vi.fn().mockResolvedValue({ok:true,status:200,json:async()=>body,text:async()=>JSON.stringify(body)});vi.stubGlobal('fetch',fetch);return fetch}
describe('writer experience contracts',()=>{
 it('sends TipTap selection text through rewrite request',async()=>{const f=mock({job_id:'j',events_url:'/events'});await api.generate('rewrite',{chapter_id:'n:1',novel_id:'n',selected_text:'chosen sentence',source:'chosen sentence',selection:{from:2,to:17}});expect(JSON.parse(f.mock.calls[0][1].body).selected_text).toBe('chosen sentence')});
 it('accepts and rejects drafts only through explicit endpoints',async()=>{const f=mock({});await api.accept('j','accepted paragraph');await api.reject('j');expect(f.mock.calls.map(x=>x[0])).toEqual(['/api/generation/j/accept','/api/generation/j/reject'])});
 it('cancels generation through the existing explicit endpoint',async()=>{const f=mock({});await api.cancel('j');expect(f).toHaveBeenCalledWith('/api/generation/j/cancel',expect.objectContaining({method:'POST'}))});
 it('handles paragraph decisions',()=>expect(acceptedParagraphs(splitParagraphs('one\n\ntwo\n\nthree'),[true,false,true])).toBe('one\n\nthree'));
 it('recognizes version conflicts',()=>expect(isVersionConflict({status:409})).toBe(true));
 it('covers duplicate restore import and export endpoints',async()=>{const f=mock({});await api.duplicateChapter('n:1');await api.restore('n:1',2,3);await api.exportNovel('n','markdown');await api.importNovel('markdown','# Chapter',false);expect(f).toHaveBeenCalledTimes(4)});
 it('keeps Harness audit filters and explicit clear confirmation in the API contract',async()=>{const f=mock({cleared:true});const csv=api.harnessAccessAuditCsv({novel_id:'n1',agent_id:'writer',outcome:'success'});expect(csv).toContain('novel_id=n1');expect(csv).toContain('agent_id=writer');expect(csv).toContain('outcome=success');await api.clearHarnessAccessAudit();expect(f.mock.calls[0][0]).toBe('/api/harness/access-audit?confirm=true');expect(f.mock.calls[0][1].method).toBe('DELETE')});
 it('maps director shot constraints into an existing motion frame request',async()=>{const f=mock({});await api.saveDirectorShotConstraints('n','s','t',{shot_id:'shot-01',name:'镜头 01',duration:'4s',camera:'推进',action:'抬头'},[{role:'白膜',uri:'asset://1'}]);const body=JSON.parse(f.mock.calls[0][1].body);expect(body.constraints.shot_id).toBe('shot-01');expect(body.constraints.references[0].role).toBe('白膜')});
 it('maps director dialogue to the existing speech synthesis request',async()=>{const f=mock({audio_uri:'audio://1'});await api.synthesizeDirectorShotDialogue({shot_id:'shot-01',dialogue:'快走！'},{provider_id:'openai',model_id:'tts-1',voice:'alloy'});const body=JSON.parse(f.mock.calls[0][1].body);expect(body.text).toBe('快走！');expect(body.chapter_id).toBe('shot-01')});
 it('batch synthesizes eligible director shots and skips incomplete ones',async()=>{const f=mock({audio_uri:'audio://1'});const results=await api.synthesizeDirectorShots([{shot_id:'a',dialogue:'开始',voice:'hero'},{shot_id:'b',dialogue:'缺少声音'}],{provider_id:'openai',model_id:'tts-1'});expect(f).toHaveBeenCalledTimes(1);expect(results.map((item:any)=>item.status)).toEqual(['succeeded','skipped'])});
 it('writes a created novel into the React Query cache before navigation',()=>{const client=new QueryClient();const existing:Novel={id:'old',title:'Old',genre:'',chapter_count:0,word_count:0,status:'DRAFT'};const created:Novel={id:'new',title:'New Novel',genre:'fantasy',chapter_count:0,word_count:0,status:'DRAFT'};client.setQueryData(['novels'],[existing]);cacheCreatedNovel(client,created);expect(client.getQueryData<Novel[]>(['novels'])).toEqual([existing,created]);cacheCreatedNovel(client,created);expect(client.getQueryData<Novel[]>(['novels'])).toEqual([existing,created])});
 it('does not load legacy local novels while a collaboration session is choosing scope',()=>{expect(shouldLoadLocalNovels('trusted-session')).toBe(false);expect(shouldLoadLocalNovels('',{workspaceId:'w',projectId:'p',storylineId:'s',branchId:'b'})).toBe(false);expect(shouldLoadLocalNovels('')).toBe(true)});
});
