import {afterEach,describe,expect,it,vi} from 'vitest';import {api,ApiError,setCollaborationContext} from './api';import {conflicts,drafts} from './drafts';
afterEach(()=>{vi.unstubAllGlobals();if(typeof localStorage!=='undefined')localStorage.clear();setCollaborationContext({sessionToken:''});drafts.remove('c');conflicts.remove('c')});
describe('collaboration frontend contracts',()=>{
 it('uses nested scope routes, item envelopes, and trusted headers',async()=>{const fetch=vi.fn().mockResolvedValue({ok:true,status:200,json:async()=>({items:[]})});vi.stubGlobal('fetch',fetch);const scope={workspaceId:'w',projectId:'p',storylineId:'s',branchId:'b'};setCollaborationContext({sessionToken:'opaque',scope});expect(await api.members(scope)).toEqual([]);expect(fetch.mock.calls[0][0]).toBe('/api/collaboration/workspaces/w/projects/p/storylines/s/branches/b/members');expect(fetch.mock.calls[0][1].headers).toMatchObject({'X-Session-Token':'opaque','X-Branch-Id':'b'})});
 it('persists local drafts and conflicts without server overwrite',()=>{drafts.save({chapterId:'c',content:'local',baseVersion:2,updatedAt:'now'});const local=drafts.load('c')!;conflicts.save({chapterId:'c',local,server:{content:'remote',version:3},detectedAt:'now'});expect(conflicts.load('c')?.local.content).toBe('local');expect(conflicts.load('c')?.server.content).toBe('remote')});
 it('namespaces identical chapter ids by collaboration scope',()=>{drafts.save({chapterId:'c',content:'branch-a',baseVersion:1,updatedAt:'now'},'scope-a');drafts.save({chapterId:'c',content:'branch-b',baseVersion:2,updatedAt:'now'},'scope-b');expect(drafts.load('c','scope-a')?.content).toBe('branch-a');expect(drafts.load('c','scope-b')?.content).toBe('branch-b')});
 it('keeps the File-mode legacy history endpoint',async()=>{const fetch=vi.fn().mockResolvedValue({ok:true,status:200,json:async()=>[]});vi.stubGlobal('fetch',fetch);expect(await api.legacyHistory('novel:1')).toEqual([]);expect(fetch.mock.calls[0][0]).toBe('/api/chapters/novel%3A1/history')});
 it.each([
  [403,'application/json',JSON.stringify({detail:{code:'FORBIDDEN',message:'没有权限'}}),'FORBIDDEN','没有权限'],
  [422,'application/json',JSON.stringify({detail:{code:'VALIDATION_ERROR',message:'输入无效'}}),'VALIDATION_ERROR','输入无效'],
  [500,'text/plain','服务暂时不可用','HTTP_ERROR','服务暂时不可用'],
 ])('parses an error response body once and preserves status/code/message',async(status,contentType,body,code,message)=>{const response=new Response(body,{status,headers:{'content-type':contentType}});const text=vi.spyOn(response,'text');vi.stubGlobal('fetch',vi.fn().mockResolvedValue(response));await expect(api.adminWorkspaces()).rejects.toMatchObject({problem:{status,code,message}} satisfies Partial<ApiError>);expect(text).toHaveBeenCalledTimes(1);expect(response.bodyUsed).toBe(true)});
});
