const fs=require('node:fs');
const path=require('node:path');
const {chromium,request,expect}=require('../frontend/node_modules/@playwright/test');
const root=path.resolve(__dirname,'..');
const evidence=path.join(root,'docs/delivery/full-recovery');
const token=JSON.parse(fs.readFileSync(path.join(root,'.runtime/full-recovery/session.json'),'utf8')).token;
const novelId=process.argv[2];
if(!novelId)throw Error('Usage: node scripts/full_recovery_product_surface.cjs NOVEL_ID --full --trusted-agent');
const full=process.argv.includes('--full'),trustedAgent=process.argv.includes('--trusted-agent'),prefix=trustedAgent?'REAL_AUTHORIZED_PRODUCT_BROWSER':full?'REAL_PRODUCT_BROWSER':'REAL_PRE_CHAPTER_BROWSER';
let browser,http,page;
async function openFeature(page,name){
 const navigation=page.getByRole('navigation',{name:'功能面板导航'});
 if(!await navigation.isVisible())await page.getByRole('button',{name:'打开功能导航',exact:true}).click();
 const target=navigation.getByRole('button',{name,exact:true});
 if(!await target.count()){
  const group=['Agent 团队','评论与审核','团队成员','权限设置'].includes(name)?'协作':['一致性检查','导出中心'].includes(name)?'制作与分析':'创作';
  await navigation.locator('.feature-group__header').filter({hasText:group}).click();
 }
 await target.click();
}
(async()=>{
 http=await request.newContext({baseURL:'http://127.0.0.1:8051',extraHTTPHeaders:{'X-Session-Token':token}});
 const novelResponse=await http.get(`/api/novels/${encodeURIComponent(novelId)}`);
 if(!novelResponse.ok())throw Error(`Novel read ${novelResponse.status()}`);
 const novel=await novelResponse.json();
 const inventoryResponse=await http.get('/api/novels'),inventory=await inventoryResponse.json();
 const titleIndex=inventory.filter(row=>row.title===novel.title).findIndex(row=>row.id===novelId);
 if(titleIndex<0)throw Error('Novel missing from original project inventory');
 const chapterResponse=await http.get(`/api/novels/${encodeURIComponent(novelId)}/chapters`),charactersResponse=await http.get(`/api/novels/${encodeURIComponent(novelId)}/characters`),runsResponse=await http.get(`/api/novels/${encodeURIComponent(novelId)}/planning-runs`);
 const chapters=await chapterResponse.json(),characters=await charactersResponse.json(),runs=await runsResponse.json();
 browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:900},locale:'zh-CN',timezoneId:'Asia/Shanghai'});
 await context.addInitScript(()=>localStorage.clear());
 page=await context.newPage();page.setDefaultTimeout(20000);
 const failures=[],network=[];page.on('pageerror',error=>failures.push(error.message));
 page.on('response',response=>{const url=new URL(response.url());if(url.pathname.startsWith('/api/'))network.push({method:response.request().method(),path:url.pathname,status:response.status()});});
 await page.goto('http://127.0.0.1:5209');
 const switcher=page.getByRole('button',{name:'切换本机作品',exact:true});
 await Promise.race([switcher.waitFor({state:'visible'}),page.getByRole('button',{name:novel.title,exact:true}).nth(titleIndex).waitFor({state:'visible'})]);
 if(await switcher.isVisible())await switcher.click();
 await page.getByRole('button',{name:novel.title,exact:true}).nth(titleIndex).click();
 await expect(page.locator('.context-bar')).toContainText(novel.title);
 await openFeature(page,'故事资料库');await page.getByRole('tab',{name:/世界观/}).click();
 await expect(page.getByLabel('核心设定')).toHaveValue(novel.world_summary||novel.long_term_summary||'');
 await page.locator('.main-workspace').screenshot({path:path.join(evidence,'real-pre-chapter-world.png')});
 await page.getByRole('tab',{name:/人物/}).click();
 const rows=Array.isArray(characters)?characters:(characters.items||[]);
 for(const character of rows)await expect(page.locator('.main-workspace')).toContainText(character.name);
 await page.locator('.main-workspace').screenshot({path:path.join(evidence,'real-pre-chapter-characters.png')});
 await openFeature(page,'创作方案与风格');await page.getByText('AI 结构化方案与明确规则提取',{exact:true}).click();
 await page.getByLabel('规划方式').selectOption('MODEL');await page.getByLabel('候选类型').selectOption('OUTLINE');
 await expect(page.getByLabel('故事创意与规划要求')).toBeVisible();
 const modelsResponse=await http.get('/api/text-models'),models=await modelsResponse.json(),availableModel=models.items.find(row=>row.available);
 if(!availableModel)throw Error('No actual available text-model route');
 await page.getByLabel('规划文本模型').selectOption(JSON.stringify([availableModel.provider_id,availableModel.model_id]));
 await page.getByLabel('故事创意与规划要求').fill('一个失忆者在废弃城市寻找过去身份，最终发现自己曾经毁灭城市。');
 await expect(page.getByRole('button',{name:'生成待审建议',exact:true})).toBeEnabled();
 const modelOptions=await page.getByLabel('规划文本模型').locator('option').allTextContents();
 const entryChecks={world:true,characters:true,project_planning:true,outline_proposal_ready:true};
 let historyVersions=[],exportJobs=[],selectedChapter,downloadEvidence,authorizedAgent;
 if(full){
  const outlineResponse=await http.get(`/api/novels/${encodeURIComponent(novelId)}/outline`),outline=await outlineResponse.json();
  await openFeature(page,'故事资料库');await page.getByRole('tab',{name:/大纲/}).click();
  await expect(page.getByLabel('主题',{exact:true})).toHaveValue(outline.theme||'');
  entryChecks.adopted_outline=true;
  const manuscriptChapters=Array.isArray(chapters)?chapters:(chapters.items||[]);
  selectedChapter=[...manuscriptChapters].sort((a,b)=>b.version-a.version)[0];
  if(!selectedChapter)throw Error('Acceptance manuscript has no actual chapter');
  await page.getByRole('button',{name:new RegExp(`^${selectedChapter.number}\\. `)}).filter({hasText:selectedChapter.title}).click();
  const currentResponse=await http.get(`/api/chapters/${encodeURIComponent(selectedChapter.id)}`),current=await currentResponse.json();
  const plain=[];function collect(node){if(node?.text)plain.push(node.text);for(const child of node?.content||[])collect(child);}collect(current.document);
  const expectedText=(plain.join('')||current.content.replace(/^#{1,6}\s+/gm,'')).replace(/\s/g,'');
  await expect.poll(async()=>(await page.getByRole('textbox',{name:'章节正文'}).innerText()).replace(/\s/g,'')).toBe(expectedText);
  await expect(page.getByRole('button',{name:'保存',exact:true})).toBeEnabled();entryChecks.chapter_open=true;entryChecks.manual_save=true;
  await page.getByLabel('文本模型').selectOption(`${availableModel.provider_id}:${availableModel.model_id}`);
  await page.getByRole('tab',{name:'改写',exact:true}).click();entryChecks.ai_rewrite=true;
  await openFeature(page,'一致性检查');await expect(page.getByRole('button',{name:/检查当前章节/})).toBeEnabled();entryChecks.consistency=true;
  await openFeature(page,'版本历史');
  await expect(page.locator('.revision-panel')).toBeVisible();
  const historyResponse=await http.get(`/api/chapters/${encodeURIComponent(selectedChapter.id)}/history`),history=await historyResponse.json();
  historyVersions=history.map(row=>row.version);
  await expect(page.locator('.revision-timeline button')).toHaveCount(history.length);
  const older=history.find(row=>row.version!==current.version);if(!older)throw Error('No historical revision for restore preview');
  await page.locator('.revision-timeline button').filter({hasText:new RegExp(`版本 ${older.version}\\b`)}).click();
  await expect(page.locator('.revision-comparison')).toBeVisible();entryChecks.history_compare=true;
  await page.locator('.revision-detail>.ui-button').click();await expect(page.getByRole('group',{name:'确认恢复历史版本'})).toBeVisible();
  await expect(page.getByRole('button',{name:'恢复此版本',exact:true})).toBeEnabled();entryChecks.restore_confirmation=true;
  await page.getByRole('button',{name:'取消',exact:true}).click();
  await page.locator('.main-workspace').screenshot({path:path.join(evidence,'real-product-history.png')});
  await openFeature(page,'导出中心');await expect(page.getByRole('heading',{name:'导出中心',exact:true})).toBeVisible();entryChecks.export=true;
  await expect(page.getByRole('button',{name:'TXT 小说',exact:true})).toBeEnabled();
  const downloadButton=page.getByRole('button',{name:/^下载 /});await expect(downloadButton).toBeEnabled();
  const downloaded=page.waitForEvent('download');await downloadButton.click();const file=await downloaded;
  const savedName=`real-product-browser-${path.basename(file.suggestedFilename())}`;
  await file.saveAs(path.join(evidence,savedName));entryChecks.existing_export_download=true;
  const bytes=fs.readFileSync(path.join(evidence,savedName));downloadEvidence={filename:savedName,bytes:bytes.length,sha256:require('node:crypto').createHash('sha256').update(bytes).digest('hex')};
  await page.locator('.main-workspace').screenshot({path:path.join(evidence,'real-product-export.png')});
  await openFeature(page,'Agent 团队');
  const team=page.locator('.ui-panel').filter({has:page.getByRole('heading',{name:'Creative Agent 任务',exact:true})}),role=team.getByLabel('Agent 角色');
  await expect(role).toBeVisible();
  await team.getByLabel('执行方式').selectOption('model');
  for(const agent of ['reviewer','verifier']){await role.selectOption(agent);await expect(team.getByRole('button',{name:'启动任务',exact:true})).toBeEnabled();}
  entryChecks.agent_roles=['reviewer','verifier'];
  if(trustedAgent){
   // Exercise the product's explicit password control. No page route or automatic browser request header is installed.
   await role.selectOption('reviewer');await team.getByLabel('任务说明').fill('核对失忆者的身份揭示是否与已批准的世界规则、人物状态及当前章节一致。输出完整合法结构化审核结果，不写入正文。');
   const anonymousResponse=page.waitForResponse(response=>new URL(response.url()).pathname==='/api/agent-jobs'&&response.request().method()==='POST');
   await team.getByRole('button',{name:'启动任务',exact:true}).click();const denied=await anonymousResponse;
   if(denied.status()!==401)throw Error(`Anonymous Agent start expected 401, got ${denied.status()}`);
   await expect(team.getByRole('alert')).toBeVisible();
   await page.getByLabel('本机访问凭证').fill(token);
   const bindingResponse=page.waitForResponse(response=>new URL(response.url()).pathname==='/api/local-session');
   await page.getByRole('button',{name:'验证并绑定本机会话',exact:true}).click();const binding=await bindingResponse;
   if(binding.status()!==200)throw Error(`Explicit local Host verification failed ${binding.status()}`);
   await expect(page.getByRole('button',{name:'解绑本机可信会话'})).toBeVisible();
   await expect(page.getByLabel('本机访问凭证')).toHaveCount(0);
   if(await page.evaluate(()=>Boolean(localStorage.getItem('studio.session'))))throw Error('Local Host binding changed original team session storage');
   // Bind remounts the task body to clear old identity/permission state; author reselects actual role/model.
   await role.selectOption('reviewer');await team.getByLabel('执行方式').selectOption('model');
   await team.getByLabel('任务说明').fill('核对失忆者的身份揭示是否与已批准的世界规则、人物状态及当前章节一致。输出完整合法结构化审核结果，不写入正文。');
   const createResponse=page.waitForResponse(response=>new URL(response.url()).pathname==='/api/agent-jobs'&&response.request().method()==='POST');
   await team.getByRole('button',{name:'启动任务',exact:true}).click();const createdResponse=await createResponse;
   if(createdResponse.status()!==202)throw Error(`Authorized UI Agent create failed ${createdResponse.status()}`);
   const created=await createdResponse.json();
   let result;
   await expect.poll(async()=>{const response=await http.get(`/api/agent-jobs/${encodeURIComponent(created.id)}`);if(!response.ok())return `HTTP_${response.status()}`;result=await response.json();return result.status},{timeout:240000,intervals:[1000,2000,4000]}).toMatch(/^(COMPLETED|FAILED|CANCELLED)$/);
   if(result.status!=='COMPLETED'||result.execution_mode!=='model'||result.model_called!==true||result.result?.empty!==false||!result.result?.structured_output?.summary)throw Error(`Real UI Reviewer failed: ${result.status}/${result.error_code||'NO_ERROR_CODE'}`);
   await expect(team.locator('.ui-badge')).toHaveText('COMPLETED',{timeout:10000});
   await page.locator('.main-workspace').screenshot({path:path.join(evidence,'real-authorized-product-agent.png')});
   const afterBinding=network.slice(network.findIndex(row=>row.path==='/api/local-session')+1);
   authorizedAgent={id:result.id,status:result.status,agent_id:result.agent_id,execution_mode:result.execution_mode,model_called:result.model_called,provider:result.provider,model:result.model,context_hash:result.context_hash,empty:result.result.empty,summary:result.result.structured_output.summary,anonymous_start_status:denied.status(),binding_status:binding.status(),binding_mode:(await binding.json()).session_mode,credential_persistence:false,automatic_browser_header_injection:false,network_after_binding_failures:afterBinding.filter(row=>row.status>=400)};
   entryChecks.explicit_local_host_binding=true;entryChecks.real_reviewer_ui_start=true;
   await page.getByRole('button',{name:'解绑本机可信会话'}).click();await expect(page.getByLabel('本机访问凭证')).toBeVisible();
   entryChecks.explicit_local_host_unlink=true;
  }
 }
 const geometry=await page.evaluate(()=>({width:innerWidth,pageWidth:document.documentElement.scrollWidth}));
 if(geometry.pageWidth>geometry.width)throw Error('Real UI horizontal overflow');
 const receipt={novel_id:novelId,title:novel.title,frontend:'http://127.0.0.1:5209',api:'http://127.0.0.1:8051',mock_interception:false,chapter_count:Array.isArray(chapters)?chapters.length:(chapters.items||[]).length,world_summary_verified:true,character_names_verified:rows.map(row=>row.name),outline_entry_reachable:true,outline_submit_enabled:true,selected_model:{provider_id:availableModel.provider_id,model_id:availableModel.model_id},model_options:modelOptions,planning_runs:(runs.items||[]).map(row=>({id:row.id,kind:row.request.kind,status:row.status,execution_mode:row.execution_mode,candidates:row.candidates.map(candidate=>({id:candidate.id,status:candidate.status}))})),page_errors:failures,network,geometry};
 receipt.entry_checks=entryChecks;receipt.history_versions=historyVersions;receipt.selected_chapter=selectedChapter?{id:selectedChapter.id,version:selectedChapter.version}:null;receipt.download=downloadEvidence;receipt.authorized_agent=authorizedAgent;
 fs.writeFileSync(path.join(evidence,`${prefix}.json`),JSON.stringify(receipt,null,2));
 await browser.close();await http.dispose();
 console.log(JSON.stringify({novel_id:novelId,chapter_count:receipt.chapter_count,world_summary_verified:true,character_count:rows.length,outline_entry_reachable:true,page_errors:failures.length,network_failures:network.filter(row=>row.status>=400)}));
})().catch(async error=>{if(page){await page.screenshot({path:path.join(evidence,`${prefix}-debug.png`)}).catch(()=>{});fs.writeFileSync(path.join(evidence,`${prefix}-debug.txt`),(await page.locator('body').innerText()).replaceAll(token,'[redacted]'));}console.error(error.message.replaceAll(token,'[redacted]').replace(/X-Session-Token: [^\r\n]*/g,'X-Session-Token: [redacted]').split('\n').slice(0,5).join('\n'));process.exitCode=1;}).finally(async()=>{await browser?.close();await http?.dispose();});
