import {useEffect,useMemo,useState} from 'react';
import {Activity,RefreshCw} from 'lucide-react';
import {api} from '../api';
import {Badge,Button,EmptyState,Panel,Spinner,StatusMessage} from './primitives';
import './CapabilityStatusCenter.css';
type Module='IMAGE'|'VIDEO'|'AUDIO'|'ASSETS'|'CONTROL'|'PLUGIN'|'WORKFLOW';
const labels:Record<Module,string>={IMAGE:'图片',VIDEO:'视频',AUDIO:'声音',ASSETS:'资产',CONTROL:'主控',PLUGIN:'插件',WORKFLOW:'Workflow'};
export function CapabilityStatusCenter({module,novelId}:{module:Module;novelId?:string}){
 const [loading,setLoading]=useState(true),[failed,setFailed]=useState(false),[health,setHealth]=useState<any>({}),[videos,setVideos]=useState<any[]>([]),[runtime,setRuntime]=useState<any>({}),[workflows,setWorkflows]=useState<any[]>([]);
 const refresh=async()=>{setLoading(true);setFailed(false);try{const [h,v,r,w]=await Promise.all([api.multimodalHealth(),api.videoProviders(),api.pluginRuntimeStatus(),novelId?api.workflows(novelId):Promise.resolve({items:[]})]);setHealth(h||{});setVideos(v?.items||[]);setRuntime(r||{});setWorkflows(w?.items||[])}catch{setFailed(true)}finally{setLoading(false)}};
 useEffect(()=>{void refresh()},[novelId]);
 const rows=useMemo(()=>{const configured=(value:unknown)=>value===true?'已配置':'未配置';if(module==='IMAGE')return [['Provider 注册',health.image_providers?.length?`可使用（${health.image_providers.length}）`:'未配置'],['Vision 凭据',configured(health.vision_credentials)],['图片生成','接口已接入，Provider 可用性取决于配置']];if(module==='VIDEO')return [['Provider 配置',videos.length?`已连接（${videos.length}）`:'未配置'],['Pipeline','已具备'],['Shot 生成','未实现']];if(module==='AUDIO')return [['Speech 凭据',configured(health.speech_credentials)],['语音生成','接口已接入，需 Provider 凭据'],['导入资产','可使用']];if(module==='ASSETS')return [['资产库','可使用'],['下载与预览','可使用'],['关联生成资产','由图片/声音/视频模块写入']];if(module==='CONTROL')return [['文本模型',health.text_credentials?'已配置':'等待配置'],['图片 Provider',health.image_providers?.length?`已发现（${health.image_providers.length}）`:'等待配置'],['插件运行时',runtime.execution_supported?'已连接':'未启用']];if(module==='PLUGIN')return [['插件发现','可使用'],['运行时',runtime.execution_supported?'已连接':'被 Feature Flag 关闭'],['沙箱',runtime.sandbox||'未记录']];return [['Workflow 定义',novelId?(workflows.length?`可使用（${workflows.length}）`:'暂无工作流'):'未打开小说'],['运行状态','由真实 Runtime 提供'],['Agent 节点','延迟触发，非自动运行']];},[module,health,videos,runtime,workflows,novelId]);
 return <Panel title="能力状态" actions={<Button variant="ghost" onClick={()=>void refresh()}><RefreshCw aria-hidden="true"/>刷新</Button>}><section className="cap-status" aria-label={`${labels[module]}能力状态`}><header><div><strong>{labels[module]}模块</strong><p>区分已连接、已配置、可使用与未完成能力。</p></div><Badge tone="info"><Activity aria-hidden="true"/>真实状态</Badge></header>{loading?<div role="status" className="cap-status__loading"><Spinner size="sm"/>正在读取能力状态…</div>:failed?<StatusMessage tone="error">状态读取失败，请重试。</StatusMessage>:rows.length?<dl>{rows.map(([label,status])=><div key={label}><dt>{label}</dt><dd>{status}</dd></div>)}</dl>:<EmptyState title="暂无状态" detail="当前模块没有可报告的真实能力。"/>}</section></Panel>;
}
