// @vitest-environment jsdom
import {act} from 'react';
import {createRoot,Root} from 'react-dom/client';
import {afterEach,describe,expect,it,vi} from 'vitest';
import {ApiError,api} from '../api';
import {ModelCenter} from './ModelCenter';

(globalThis as typeof globalThis & {IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;

describe('ModelCenter',()=>{
 let host:HTMLDivElement,root:Root,mounted=false;
 afterEach(()=>{if(mounted)act(()=>root.unmount());host?.remove();vi.restoreAllMocks();mounted=false});
 it('shows verified models, runtime state, and the registered video pipeline',async()=>{
  vi.spyOn(api,'modelCenterModels').mockResolvedValue({items:[{id:'qwen',display_name:'Qwen3.6 27B',capabilities:['TEXT'],runtime_type:'LLAMA_CPP',status:'READY',verified:true,historically_validated:true,hardware_profile_details:[{id:'gpu',gpu_name:'RTX 5080',profile_kind:'DEFAULT',benchmark:{}}]}]});
  vi.spyOn(api,'modelCenterRuntimes').mockResolvedValue({items:[{id:'llama',runtime_type:'LLAMA_CPP',base_url:'http://127.0.0.1:8081',status:'CONFIGURED',instance:null,discovery:{path_exists:true,executable_exists:true}}]});
  vi.spyOn(api,'modelCenterPipelines').mockResolvedValue({items:[{id:'LOCAL_VIDEO_PIPELINE_V1',nodes:[{id:'generate',capability:'VIDEO',model_id:'wan22'}],edges:[]}]});
  vi.spyOn(api,'modelCenterHealth').mockResolvedValue({status:'READY',mutation_authorization:{can_mutate:true,mutation_auth_mode:'TRUSTED_SESSION'}});
  host=document.createElement('div');document.body.append(host);root=createRoot(host);mounted=true;await act(async()=>{root.render(<ModelCenter/>);await Promise.resolve();await Promise.resolve()});
  expect(host.textContent).toContain('Qwen3.6 27B');expect(host.textContent).toContain('Current Verified');expect(host.textContent).toContain('LOCAL_VIDEO_PIPELINE_V1');expect(host.textContent).toContain('127.0.0.1');
 });
 it('renders non-ready states and prevents duplicate start while starting',async()=>{
  vi.spyOn(api,'modelCenterModels').mockResolvedValue({items:[{id:'rife',display_name:'RIFE 4.26',capabilities:['INTERPOLATION'],runtime_type:'COMFYUI',status:'INCOMPATIBLE',verified:false,historically_validated:true,hardware_profile_details:[]},{id:'ltx',display_name:'LTX 2.5',capabilities:['VIDEO'],runtime_type:'COMFYUI',status:'LICENSE_REQUIRED',verified:false,historically_validated:false,hardware_profile_details:[]}]});
  vi.spyOn(api,'modelCenterRuntimes').mockResolvedValue({items:[{id:'llama',runtime_type:'LLAMA_CPP',base_url:'http://127.0.0.1:8081',status:'CONFIGURED',instance:{state:'STARTING',process_id:123},discovery:{path_exists:true,executable_exists:true}}]});
  vi.spyOn(api,'modelCenterPipelines').mockResolvedValue({items:[]});
  vi.spyOn(api,'modelCenterHealth').mockResolvedValue({status:'READY',mutation_authorization:{can_mutate:true,mutation_auth_mode:'TRUSTED_SESSION'}});
  host=document.createElement('div');document.body.append(host);root=createRoot(host);mounted=true;await act(async()=>{root.render(<ModelCenter/>);await Promise.resolve();await Promise.resolve()});
  expect(host.textContent).toContain('INCOMPATIBLE');expect(host.textContent).toContain('LICENSE_REQUIRED');expect(host.textContent).toContain('Historical Validation');expect(host.textContent).toContain('未完成推理验证');
  const buttons=Array.from(host.querySelectorAll('button'));
  expect(buttons.find(button=>button.textContent?.includes('Start'))?.disabled).toBe(true);
  expect(buttons.find(button=>button.textContent?.includes('Stop'))?.disabled).toBe(false);
  expect(buttons.find(button=>button.textContent?.includes('Validate'))?.disabled).toBe(true);
 });
 it('ignores responses that finish after unmount',async()=>{
  let resolveModels!:(value:Awaited<ReturnType<typeof api.modelCenterModels>>)=>void;
  let resolveRuntimes!:(value:Awaited<ReturnType<typeof api.modelCenterRuntimes>>)=>void;
  let resolvePipelines!:(value:Awaited<ReturnType<typeof api.modelCenterPipelines>>)=>void;
  let resolveHealth!:(value:Awaited<ReturnType<typeof api.modelCenterHealth>>)=>void;
  vi.spyOn(api,'modelCenterModels').mockReturnValue(new Promise(resolve=>{resolveModels=resolve}));
  vi.spyOn(api,'modelCenterRuntimes').mockReturnValue(new Promise(resolve=>{resolveRuntimes=resolve}));
  vi.spyOn(api,'modelCenterPipelines').mockReturnValue(new Promise(resolve=>{resolvePipelines=resolve}));
  vi.spyOn(api,'modelCenterHealth').mockReturnValue(new Promise(resolve=>{resolveHealth=resolve}));
  host=document.createElement('div');document.body.append(host);root=createRoot(host);mounted=true;
  await act(async()=>{root.render(<ModelCenter/>);await Promise.resolve()});
  act(()=>root.unmount());mounted=false;
  await act(async()=>{resolveModels({items:[]});resolveRuntimes({items:[]});resolvePipelines({items:[]});resolveHealth({status:'READY',mutation_authorization:{can_mutate:false,mutation_auth_mode:'DEVELOPMENT_SESSION_REQUIRED'}});await Promise.resolve()});
  expect(host.textContent).toBe('');
 });
 it('keeps default local runtime controls read-only without sending mutations',async()=>{
  vi.spyOn(api,'modelCenterModels').mockResolvedValue({items:[]});
  vi.spyOn(api,'modelCenterRuntimes').mockResolvedValue({items:[{id:'llama',runtime_type:'LLAMA_CPP',base_url:'http://127.0.0.1:8081',status:'CONFIGURED',instance:{state:'RUNNING',process_id:123},discovery:{path_exists:true,executable_exists:true}}]});
  vi.spyOn(api,'modelCenterPipelines').mockResolvedValue({items:[]});
  vi.spyOn(api,'modelCenterHealth').mockResolvedValue({status:'READY',mutation_authorization:{can_mutate:false,mutation_auth_mode:'DEVELOPMENT_SESSION_REQUIRED'}});
  const validate=vi.spyOn(api,'modelCenterValidateRuntime'),start=vi.spyOn(api,'modelCenterStartRuntime'),stop=vi.spyOn(api,'modelCenterStopRuntime');
  host=document.createElement('div');document.body.append(host);root=createRoot(host);mounted=true;await act(async()=>{root.render(<ModelCenter/>);await Promise.resolve();await Promise.resolve()});
  expect(host.textContent).toContain('运行时控制需要受信任的桌面会话');
  const controls=Array.from(host.querySelectorAll('button')).filter(button=>/Validate|Start|Stop/.test(button.textContent||''));
  expect(controls).toHaveLength(3);expect(controls.every(button=>button.disabled)).toBe(true);
  controls.forEach(button=>button.click());
  expect(validate).not.toHaveBeenCalled();expect(start).not.toHaveBeenCalled();expect(stop).not.toHaveBeenCalled();
 });
 it('falls back to read-only controls when the trusted session expires',async()=>{
  vi.spyOn(api,'modelCenterModels').mockResolvedValue({items:[]});
  vi.spyOn(api,'modelCenterRuntimes').mockResolvedValue({items:[{id:'llama',runtime_type:'LLAMA_CPP',base_url:'http://127.0.0.1:8081',status:'CONFIGURED',instance:null,discovery:{path_exists:true,executable_exists:true}}]});
  vi.spyOn(api,'modelCenterPipelines').mockResolvedValue({items:[]});
  vi.spyOn(api,'modelCenterHealth').mockResolvedValue({status:'READY',mutation_authorization:{can_mutate:true,mutation_auth_mode:'PACKAGED_BOOTSTRAP'}});
  vi.spyOn(api,'modelCenterStartRuntime').mockRejectedValue(new ApiError({status:401,code:'INVALID_SESSION',message:'INVALID_SESSION'}));
  host=document.createElement('div');document.body.append(host);root=createRoot(host);mounted=true;await act(async()=>{root.render(<ModelCenter/>);await Promise.resolve();await Promise.resolve()});
  const start=Array.from(host.querySelectorAll('button')).find(button=>button.textContent?.includes('Start'))!;
  expect(start.disabled).toBe(false);
  await act(async()=>{start.click();await Promise.resolve();await Promise.resolve()});
  expect(start.disabled).toBe(true);expect(host.textContent).toContain('受信任的桌面会话已失效');
 });
 it('shows external runtime metadata without start or stop controls',async()=>{
  vi.spyOn(api,'modelCenterModels').mockResolvedValue({items:[]});
  vi.spyOn(api,'modelCenterRuntimes').mockResolvedValue({items:[{id:'comfy',runtime_type:'COMFYUI',management:'EXTERNAL',base_url:'http://127.0.0.1:8188',status:'CONFIGURED',instance:{state:'EXTERNAL',process_id:null,http_reachable:true},discovery:{path_exists:true,executable_exists:false}}]});
  vi.spyOn(api,'modelCenterPipelines').mockResolvedValue({items:[]});
  vi.spyOn(api,'modelCenterHealth').mockResolvedValue({status:'READY',mutation_authorization:{can_mutate:true,mutation_auth_mode:'PACKAGED_BOOTSTRAP'}});
  host=document.createElement('div');document.body.append(host);root=createRoot(host);mounted=true;await act(async()=>{root.render(<ModelCenter/>);await Promise.resolve();await Promise.resolve()});
  expect(host.textContent).toContain('COMFYUI · EXTERNAL');
  expect(Array.from(host.querySelectorAll('button')).find(button=>button.textContent?.includes('Start'))?.disabled).toBe(true);
  expect(Array.from(host.querySelectorAll('button')).find(button=>button.textContent?.includes('Stop'))?.disabled).toBe(true);
 });
 it('opens trusted typed configuration and advanced diagnostics',async()=>{
  vi.spyOn(api,'modelCenterModels').mockResolvedValue({items:[]});
  vi.spyOn(api,'modelCenterRuntimes').mockResolvedValue({items:[{id:'llama',runtime_type:'LLAMA_CPP',management:'MANAGED',base_url:'http://127.0.0.1:8081',status:'CONFIGURED',instance:null,discovery:{path_exists:true,executable_exists:true}}]});
  vi.spyOn(api,'modelCenterPipelines').mockResolvedValue({items:[]});
  vi.spyOn(api,'modelCenterHealth').mockResolvedValue({status:'READY',mutation_authorization:{can_mutate:true,mutation_auth_mode:'PACKAGED_BOOTSTRAP'}});
  vi.spyOn(api,'modelCenterRuntimeConfiguration').mockResolvedValue({id:'llama',runtime_type:'LLAMA_CPP',management:'MANAGED',executable:'D:/runtime/llama.exe',working_directory:'D:/runtime',base_url:'http://127.0.0.1:8081',bind_address:'127.0.0.1',port:8081,health_endpoint:'/v1/models',model_path:'D:/models/qwen.gguf',context_size:8192,gpu_layers:40,threads:12,batch_size:512,extra_arguments:[]});
  vi.spyOn(api,'modelCenterRuntimeDiagnostics').mockResolvedValue({runtime_id:'llama',management:'MANAGED',state:'RUNNING',process_alive:true,http_reachable:true,version:'b7000',latency_ms:4,safe_error_code:null,checks:[]});
  vi.spyOn(api,'modelCenterRuntimeCapabilities').mockResolvedValue({runtime_id:'llama',runtime_version:'b7000',detected_at:'now',runtime_state:'RUNNING',capabilities:['TEXT'],available_models:['qwen.gguf'],adapters:['OPENAI_COMPATIBLE_TEXT'],node_classes:[],warnings:[]});
  vi.spyOn(api,'modelCenterRuntimeLogs').mockResolvedValue({runtime_id:'llama',stdout:['ready'],stderr:[]});
  host=document.createElement('div');document.body.append(host);root=createRoot(host);mounted=true;await act(async()=>{root.render(<ModelCenter/>);await Promise.resolve();await Promise.resolve()});
  const buttons=Array.from(host.querySelectorAll('button'));
  await act(async()=>{buttons.find(button=>button.textContent?.includes('Edit Configuration'))!.click();await Promise.resolve()});
  expect(host.querySelector('[role=dialog]')).toBeTruthy();expect((host.querySelector('input[value="D:/models/qwen.gguf"]') as HTMLInputElement).value).toContain('qwen.gguf');
  await act(async()=>{host.querySelector('[role=dialog] button')!.dispatchEvent(new MouseEvent('click',{bubbles:true}));await Promise.resolve()});
  await act(async()=>{Array.from(host.querySelectorAll('button')).find(button=>button.textContent?.includes('View Diagnostics'))!.click();await Promise.resolve();await Promise.resolve()});
  expect(host.textContent).toContain('Advanced Diagnostics');expect(host.textContent).toContain('b7000');expect(host.textContent).toContain('ready');
 });
 it('saves an explicit allowlisted configuration payload without spreading server fields',async()=>{
  vi.spyOn(api,'modelCenterModels').mockResolvedValue({items:[]});
  vi.spyOn(api,'modelCenterRuntimes').mockResolvedValue({items:[{id:'llama',runtime_type:'LLAMA_CPP',management:'MANAGED',base_url:'http://127.0.0.1:8081',status:'CONFIGURED',instance:null,discovery:{path_exists:true,executable_exists:true}}]});
  vi.spyOn(api,'modelCenterPipelines').mockResolvedValue({items:[]});
  vi.spyOn(api,'modelCenterHealth').mockResolvedValue({status:'READY',mutation_authorization:{can_mutate:true,mutation_auth_mode:'PACKAGED_BOOTSTRAP'}});
  vi.spyOn(api,'modelCenterRuntimeConfiguration').mockResolvedValue({id:'llama',runtime_type:'LLAMA_CPP',management:'MANAGED',executable:'D:/runtime/llama.exe',working_directory:'D:/runtime',base_url:'http://127.0.0.1:8081',bind_address:'127.0.0.1',port:8081,health_endpoint:'/v1/models',model_path:'D:/models/qwen.gguf',context_size:8192,gpu_layers:40,threads:12,batch_size:512,extra_arguments:[],launch_arguments:['--host','0.0.0.0'],capabilities:['TEXT'],status:'CONFIGURED',provider_adapter:'OPENAI_COMPATIBLE_TEXT'} as never);
  const update=vi.spyOn(api,'modelCenterUpdateRuntimeConfiguration').mockResolvedValue({id:'llama',runtime_type:'LLAMA_CPP',management:'MANAGED',executable:'D:/runtime/llama.exe',working_directory:'D:/runtime',base_url:'http://127.0.0.1:8081',bind_address:'127.0.0.1',port:8081,health_endpoint:'/v1/models',model_path:'D:/models/qwen.gguf',context_size:8192,gpu_layers:40,threads:12,batch_size:512,extra_arguments:[]});
  host=document.createElement('div');document.body.append(host);root=createRoot(host);mounted=true;await act(async()=>{root.render(<ModelCenter/>);await Promise.resolve();await Promise.resolve()});
  await act(async()=>{Array.from(host.querySelectorAll('button')).find(button=>button.textContent?.includes('Edit Configuration'))!.click();await Promise.resolve()});
  await act(async()=>{(host.querySelector('[role=dialog] button[type=submit]') as HTMLButtonElement).click();await Promise.resolve();await Promise.resolve()});
  expect(update).toHaveBeenCalledTimes(1);
  const body=update.mock.calls[0][1] as Record<string,unknown>;
  expect(body).not.toHaveProperty('launch_arguments');
  expect(body).not.toHaveProperty('capabilities');
  expect(body).not.toHaveProperty('status');
  expect(body).not.toHaveProperty('provider_adapter');
  expect(body).not.toHaveProperty('id');
  expect(body.runtime_type).toBe('LLAMA_CPP');
  expect(body.bind_address).toBe('127.0.0.1');
  expect(body.model_path).toBe('D:/models/qwen.gguf');
  expect(body.extra_arguments).toEqual([]);
 });
 it('saves ComfyUI configuration with installation_path only',async()=>{
  vi.spyOn(api,'modelCenterModels').mockResolvedValue({items:[]});
  vi.spyOn(api,'modelCenterRuntimes').mockResolvedValue({items:[{id:'comfy',runtime_type:'COMFYUI',management:'EXTERNAL',base_url:'http://127.0.0.1:8188',status:'CONFIGURED',instance:null,discovery:{path_exists:true,executable_exists:false}}]});
  vi.spyOn(api,'modelCenterPipelines').mockResolvedValue({items:[]});
  vi.spyOn(api,'modelCenterHealth').mockResolvedValue({status:'READY',mutation_authorization:{can_mutate:true,mutation_auth_mode:'PACKAGED_BOOTSTRAP'}});
  vi.spyOn(api,'modelCenterRuntimeConfiguration').mockResolvedValue({id:'comfy',runtime_type:'COMFYUI',management:'EXTERNAL',executable:'',installation_path:'D:/ComfyUI',base_url:'http://127.0.0.1:8188',bind_address:'127.0.0.1',port:8188,health_endpoint:'/system_stats'});
  const update=vi.spyOn(api,'modelCenterUpdateRuntimeConfiguration').mockResolvedValue({id:'comfy',runtime_type:'COMFYUI',management:'EXTERNAL',executable:'',installation_path:'D:/ComfyUI',base_url:'http://127.0.0.1:8188',bind_address:'127.0.0.1',port:8188,health_endpoint:'/system_stats'});
  host=document.createElement('div');document.body.append(host);root=createRoot(host);mounted=true;await act(async()=>{root.render(<ModelCenter/>);await Promise.resolve();await Promise.resolve()});
  await act(async()=>{Array.from(host.querySelectorAll('button')).find(button=>button.textContent?.includes('Edit Configuration'))!.click();await Promise.resolve()});
  expect((host.querySelector('input[value="D:/ComfyUI"]') as HTMLInputElement).value).toBe('D:/ComfyUI');
  await act(async()=>{(host.querySelector('[role=dialog] button[type=submit]') as HTMLButtonElement).click();await Promise.resolve();await Promise.resolve()});
  const body=update.mock.calls[0][1] as Record<string,unknown>;
  expect(body.runtime_type).toBe('COMFYUI');
  expect(body.installation_path).toBe('D:/ComfyUI');
  expect(body).not.toHaveProperty('working_directory');
  expect(body).not.toHaveProperty('launch_arguments');
 });
 it('renders never-started diagnostics when log arrays are missing',async()=>{
  vi.spyOn(api,'modelCenterModels').mockResolvedValue({items:[]});
  vi.spyOn(api,'modelCenterRuntimes').mockResolvedValue({items:[{id:'llama',runtime_type:'LLAMA_CPP',management:'MANAGED',base_url:'http://127.0.0.1:8081',status:'CONFIGURED',instance:null,discovery:{path_exists:true,executable_exists:true}}]});
  vi.spyOn(api,'modelCenterPipelines').mockResolvedValue({items:[]});
  vi.spyOn(api,'modelCenterHealth').mockResolvedValue({status:'READY',mutation_authorization:{can_mutate:true,mutation_auth_mode:'PACKAGED_BOOTSTRAP'}});
  vi.spyOn(api,'modelCenterRuntimeDiagnostics').mockResolvedValue({runtime_id:'llama',management:'MANAGED',state:'STOPPED',process_alive:false,http_reachable:false,version:null,latency_ms:null,safe_error_code:null,checks:[]});
  vi.spyOn(api,'modelCenterRuntimeCapabilities').mockResolvedValue({runtime_id:'llama',runtime_version:null,detected_at:'now',runtime_state:'STOPPED',capabilities:[],available_models:[],adapters:[],node_classes:[],warnings:[]});
  vi.spyOn(api,'modelCenterRuntimeLogs').mockResolvedValue({runtime_id:'llama'} as never);
  host=document.createElement('div');document.body.append(host);root=createRoot(host);mounted=true;await act(async()=>{root.render(<ModelCenter/>);await Promise.resolve();await Promise.resolve()});
  await act(async()=>{Array.from(host.querySelectorAll('button')).find(button=>button.textContent?.includes('View Diagnostics'))!.click();await Promise.resolve();await Promise.resolve()});
  expect(host.textContent).toContain('Advanced Diagnostics');
  expect(host.textContent).toContain('No managed runtime logs.');
 });
});
