import {useEffect,useRef,useState} from 'react';
import {Activity,FileText,Play,RefreshCw,Settings2,ShieldAlert,Square,X} from 'lucide-react';
import {ApiError,api,type ModelCenterModel,type ModelCenterPipeline,type ModelCenterRuntime,type ModelCenterRuntimeConfiguration,type RuntimeCapabilitySnapshot,type RuntimeDiagnostics} from '../api';
import {Badge,Button,EmptyState,Panel,StatusMessage} from './primitives';
import './ModelCenter.css';

const authCodes=['SESSION_REQUIRED','INVALID_SESSION'];

export function ModelCenter(){
 const [models,setModels]=useState<ModelCenterModel[]>([]),[runtimes,setRuntimes]=useState<ModelCenterRuntime[]>([]),[pipelines,setPipelines]=useState<ModelCenterPipeline[]>([]),[canMutate,setCanMutate]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState('');
 const [selected,setSelected]=useState(''),[configuration,setConfiguration]=useState<ModelCenterRuntimeConfiguration>(),[diagnostics,setDiagnostics]=useState<RuntimeDiagnostics>(),[snapshot,setSnapshot]=useState<RuntimeCapabilitySnapshot>(),[logs,setLogs]=useState<{stdout:string[];stderr:string[]}>(),[editing,setEditing]=useState(false);
 const mounted=useRef(true),requestGeneration=useRef(0);
 const expire=()=>{setCanMutate(false);setEditing(false);setError('受信任的桌面会话已失效，运行时控制已禁用。')};
 const refresh=async()=>{const generation=++requestGeneration.current;if(mounted.current){setError('');setLoading(true)}try{const [m,r,p,h]=await Promise.all([api.modelCenterModels(),api.modelCenterRuntimes(),api.modelCenterPipelines(),api.modelCenterHealth()]);if(mounted.current&&generation===requestGeneration.current){setModels(m.items);setRuntimes(r.items);setPipelines(p.items);setCanMutate(h.mutation_authorization.can_mutate);if(!selected&&r.items[0])setSelected(r.items[0].id)}}catch{if(mounted.current&&generation===requestGeneration.current)setError('模型中心状态读取失败，请检查本地服务。')}finally{if(mounted.current&&generation===requestGeneration.current)setLoading(false)}};
 useEffect(()=>{mounted.current=true;void refresh();return()=>{mounted.current=false;requestGeneration.current++}},[]);
 const action=async(id:string,kind:'validate'|'start'|'stop')=>{if(!canMutate)return;setBusy(`${id}:${kind}`);setError('');try{if(kind==='validate')await api.modelCenterValidateRuntime(id);else if(kind==='start')await api.modelCenterStartRuntime(id);else await api.modelCenterStopRuntime(id);if(mounted.current)await refresh()}catch(caught){if(mounted.current){if(caught instanceof ApiError&&authCodes.includes(caught.problem.code))expire();else setError(caught instanceof ApiError?caught.problem.code:'运行时操作未完成。')}}finally{if(mounted.current)setBusy('')}};
 const openEdit=async(id:string)=>{if(!canMutate)return;setBusy(`${id}:edit`);try{setConfiguration(await api.modelCenterRuntimeConfiguration(id));setEditing(true)}catch(caught){if(caught instanceof ApiError&&authCodes.includes(caught.problem.code))expire();else setError('运行时配置读取失败。')}finally{setBusy('')}};
 const save=async(event:React.FormEvent)=>{event.preventDefault();if(!configuration||!canMutate)return;setBusy(`${configuration.id}:save`);try{const {id:_id,...editable}=configuration;const body=configuration.runtime_type==='LLAMA_CPP'?editable:{runtime_type:'COMFYUI',management:'EXTERNAL',installation_path:configuration.working_directory,base_url:configuration.base_url,bind_address:configuration.bind_address,port:configuration.port,health_endpoint:configuration.health_endpoint,executable:''};await api.modelCenterUpdateRuntimeConfiguration(configuration.id,body as unknown as Record<string,unknown>);setEditing(false);await refresh()}catch(caught){if(caught instanceof ApiError&&authCodes.includes(caught.problem.code))expire();else setError(caught instanceof ApiError?caught.problem.code:'运行时配置保存失败。')}finally{setBusy('')}};
 const inspect=async(id:string)=>{if(!canMutate)return;setBusy(`${id}:inspect`);try{const [d,c,l]=await Promise.all([api.modelCenterRuntimeDiagnostics(id),api.modelCenterRuntimeCapabilities(id),api.modelCenterRuntimeLogs(id)]);setDiagnostics(d);setSnapshot(c);setLogs(l);setSelected(id)}catch(caught){if(caught instanceof ApiError&&authCodes.includes(caught.problem.code))expire();else setError('运行时诊断读取失败。')}finally{setBusy('')}};
 const runtimeTone=(state?:string):'success'|'warning'|'error'|'neutral'=>state==='RUNNING'||state==='EXTERNAL'?'success':state==='STARTING'||state==='DEGRADED'?'warning':state==='FAILED'?'error':'neutral';
 const field=(key:keyof ModelCenterRuntimeConfiguration,label:string,type='text')=><label>{label}<input type={type} value={String(configuration?.[key]??'')} onChange={event=>setConfiguration(current=>current?{...current,[key]:type==='number'?Number(event.target.value):event.target.value}:current)}/></label>;
 return <div className="model-center">
  {error&&<StatusMessage tone="error">{error}</StatusMessage>}
  <Panel title="Model Center" actions={<Button variant="ghost" onClick={()=>void refresh()} disabled={loading}><RefreshCw aria-hidden="true"/>刷新</Button>}>
   {loading?<div role="status">正在读取模型注册表…</div>:!models.length?<EmptyState title="暂无模型" detail="注册本地模型后会显示在这里。"/>:<div className="model-center__models">{models.map(model=><article key={model.id}><header><div><strong>{model.display_name}</strong><small>{model.runtime_type}</small></div><Badge tone={model.status==='READY'?'success':model.status==='INCOMPATIBLE'?'error':'warning'}>{model.status}</Badge></header><div className="model-center__capabilities">{model.capabilities.map(item=><Badge key={item}>{item}</Badge>)}</div><dl><div><dt>验证</dt><dd>{model.verified?'Current Verified':model.historically_validated?'Historical Validation / Verified Baseline':'未完成推理验证'}</dd></div><div><dt>硬件</dt><dd>{model.hardware_profile_details[0]?.gpu_name||'未记录'}</dd></div></dl></article>)}</div>}
  </Panel>
  <Panel title="Local Runtimes">{!loading&&!canMutate&&<StatusMessage tone="warning"><ShieldAlert aria-hidden="true"/>运行时控制需要受信任的桌面会话。Trusted desktop session required.</StatusMessage>}{!loading&&!runtimes.length?<EmptyState title="暂无运行时" detail="配置本地运行时后会显示在这里。"/>:<div className="model-center__runtimes">{runtimes.map(runtime=>{const state=runtime.instance?.state||'STOPPED',active=['STARTING','RUNNING'].includes(state),managed=runtime.management!=='EXTERNAL'&&runtime.runtime_type!=='COMFYUI';return <article key={runtime.id} data-selected={selected===runtime.id}><header><div><strong>{runtime.id}</strong><small>{runtime.runtime_type} · {runtime.management||(managed?'MANAGED':'EXTERNAL')}</small></div><Badge tone={runtimeTone(state)}>{state}</Badge></header><dl><div><dt>Endpoint</dt><dd>{runtime.base_url}</dd></div><div><dt>Context</dt><dd>{runtime.context_size||'—'}</dd></div><div><dt>Health</dt><dd>{runtime.instance?.http_reachable?'Reachable':'Not reachable'}</dd></div></dl><div className="model-center__actions"><Button onClick={()=>void action(runtime.id,'validate')} disabled={!canMutate||!!busy||state==='STARTING'}>Validate</Button><Button onClick={()=>void action(runtime.id,'start')} disabled={!canMutate||!!busy||!managed||active}><Play aria-hidden="true"/>Start</Button><Button variant="ghost" onClick={()=>void action(runtime.id,'stop')} disabled={!canMutate||!!busy||!managed||!active}><Square aria-hidden="true"/>Stop</Button><Button variant="ghost" onClick={()=>void openEdit(runtime.id)} disabled={!canMutate||!!busy}><Settings2 aria-hidden="true"/>Edit Configuration</Button><Button variant="ghost" onClick={()=>void inspect(runtime.id)} disabled={!canMutate||!!busy}><Activity aria-hidden="true"/>View Diagnostics</Button></div></article>})}</div>}</Panel>
  {(diagnostics||snapshot||logs)&&<Panel title="Advanced Diagnostics" actions={<Button variant="ghost" onClick={()=>{setDiagnostics(undefined);setSnapshot(undefined);setLogs(undefined)}}><X aria-hidden="true"/></Button>}><div className="model-center__diagnostics">{diagnostics&&<dl><div><dt>State</dt><dd>{diagnostics.state}</dd></div><div><dt>Version</dt><dd>{diagnostics.version||'Unknown'}</dd></div><div><dt>Latency</dt><dd>{diagnostics.latency_ms??'—'} ms</dd></div><div><dt>Error</dt><dd>{diagnostics.safe_error_code||'None'}</dd></div></dl>}{snapshot&&<section><strong>Capabilities</strong><p>{snapshot.capabilities.join(', ')||'None detected'}</p><strong>Node classes</strong><p>{snapshot.node_classes.join(', ')||'None detected'}</p></section>}{logs&&<section><strong><FileText aria-hidden="true"/> Redacted logs</strong><pre>{[...logs.stdout,...logs.stderr].join('\n')||'No managed runtime logs.'}</pre></section>}</div></Panel>}
  {editing&&configuration&&<div className="model-center__dialog" role="dialog" aria-modal="true" aria-label="Edit runtime configuration"><form onSubmit={save}><header><h2>Edit Configuration</h2><Button type="button" variant="ghost" onClick={()=>setEditing(false)}><X aria-hidden="true"/></Button></header>{field('base_url','Base URL')}{field('bind_address','Host')}{field('port','Port','number')}{field('health_endpoint','Health endpoint')}{configuration.runtime_type==='LLAMA_CPP'&&<>{field('executable','Executable')}{field('working_directory','Working directory')}{field('model_path','Model path')}{field('context_size','Context','number')}{field('gpu_layers','GPU layers','number')}{field('threads','Threads','number')}{field('batch_size','Batch size','number')}<label>Extra safe flags<input value={configuration.extra_arguments.join(' ')} onChange={event=>setConfiguration({...configuration,extra_arguments:event.target.value.split(/\s+/).filter(Boolean)})}/></label></>}{configuration.runtime_type==='COMFYUI'&&field('working_directory','Installation path')}<footer><Button type="button" variant="ghost" onClick={()=>setEditing(false)}>Cancel</Button><Button type="submit" disabled={!!busy}>Save</Button></footer></form></div>}
  <Panel title="Pipelines">{pipelines.map(pipeline=><section className="model-center__pipeline" key={pipeline.id}><strong>{pipeline.id}</strong><ol>{pipeline.nodes.map(node=><li key={node.id}><span>{node.capability}</span><code>{node.model_id}</code></li>)}</ol></section>)}</Panel>
 </div>
}
