from __future__ import annotations
import uuid
from datetime import datetime,timezone
from sqlalchemy import DateTime,ForeignKey,Integer,Numeric,Text,UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB,UUID
from sqlalchemy.orm import Mapped,mapped_column
from app.repositories.postgres.models import Base
def utcnow():return datetime.now(timezone.utc)
class EvidenceModel(Base):
 __tablename__="evidence_records";__table_args__=(UniqueConstraint("novel_id","source_type","source_id","content_hash"),)
 id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True);novel_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("novels.id",ondelete="CASCADE"));schema_version:Mapped[int]=mapped_column(Integer,default=1);source_type:Mapped[str]=mapped_column(Text);source_id:Mapped[str]=mapped_column(Text);chapter_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("chapters.id",ondelete="SET NULL"));chapter_version:Mapped[int|None]=mapped_column(Integer);generation_job_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("generation_jobs.id",ondelete="SET NULL"));excerpt:Mapped[str|None]=mapped_column(Text);locator:Mapped[dict]=mapped_column(JSONB);content_hash:Mapped[str]=mapped_column(Text);privacy:Mapped[str]=mapped_column(Text);status:Mapped[str]=mapped_column(Text,default="ACTIVE");invalidation_reason:Mapped[str|None]=mapped_column(Text);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class LoreProposalModel(Base):
 __tablename__="lore_proposals"
 id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True);novel_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("novels.id",ondelete="CASCADE"));proposal_type:Mapped[str]=mapped_column(Text);schema_version:Mapped[int]=mapped_column(Integer,default=1);payload:Mapped[dict]=mapped_column(JSONB);approved_payload:Mapped[dict|None]=mapped_column(JSONB);status:Mapped[str]=mapped_column(Text,default="PENDING");source_chapter_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("chapters.id",ondelete="SET NULL"));source_version:Mapped[int|None]=mapped_column(Integer);agent_name:Mapped[str|None]=mapped_column(Text);generation_job_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("generation_jobs.id",ondelete="SET NULL"));confidence:Mapped[float|None]=mapped_column(Numeric);reviewed_by:Mapped[str|None]=mapped_column(Text);reviewed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));rejection_reason:Mapped[str|None]=mapped_column(Text);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class LoreProposalEvidenceModel(Base):
 __tablename__="lore_proposal_evidence"
 proposal_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("lore_proposals.id",ondelete="CASCADE"),primary_key=True);evidence_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("evidence_records.id",ondelete="RESTRICT"),primary_key=True);schema_version:Mapped[int]=mapped_column(Integer,default=1);relevance:Mapped[str]=mapped_column(Text);note:Mapped[str|None]=mapped_column(Text);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class CharacterMemoryModel(Base):
 __tablename__="character_memories";__table_args__=(UniqueConstraint("novel_id","business_id"),)
 id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True);novel_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("novels.id",ondelete="CASCADE"));character_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("characters.id",ondelete="CASCADE"));business_id:Mapped[str]=mapped_column(Text);memory_type:Mapped[str]=mapped_column(Text);schema_version:Mapped[int]=mapped_column(Integer,default=1);content:Mapped[dict]=mapped_column(JSONB);status:Mapped[str]=mapped_column(Text,default="ACTIVE");valid_from_chapter:Mapped[int|None]=mapped_column(Integer);valid_to_chapter:Mapped[int|None]=mapped_column(Integer);proposal_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("lore_proposals.id",ondelete="RESTRICT"));supersedes_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("character_memories.id",ondelete="RESTRICT"));retraction_reason:Mapped[str|None]=mapped_column(Text);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class MemorySnapshotModel(Base):
 __tablename__="memory_snapshots";__table_args__=(UniqueConstraint("novel_id","scope","scope_key","version"),)
 id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True);novel_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("novels.id",ondelete="CASCADE"));scope:Mapped[str]=mapped_column(Text);scope_key:Mapped[str]=mapped_column(Text);schema_version:Mapped[int]=mapped_column(Integer,default=1);range_start:Mapped[int|None]=mapped_column(Integer);range_end:Mapped[int|None]=mapped_column(Integer);memory:Mapped[dict]=mapped_column(JSONB);version:Mapped[int]=mapped_column(Integer);source_watermark:Mapped[dict]=mapped_column(JSONB);content_hash:Mapped[str]=mapped_column(Text);supersedes_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("memory_snapshots.id",ondelete="RESTRICT"));created_by:Mapped[str]=mapped_column(Text);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
