"""Server-owned capability descriptions, including honest planned work.

A registered direction is not a runnable capability. Runtime availability is
computed from implementation state and current server flags, never a client hint.
This module contains no project content and starts no scanners, workers or models.
"""
from __future__ import annotations

from .flags import enabled_flags

# These states are intentionally conservative and updated only with real wiring.
INTEGRATED_PACKAGES = frozenset({'F00', 'U01', 'U02', 'U03', 'U04', 'U07', 'U08', 'U09', 'U10', 'U12', 'A04', 'A05', 'A06', 'A07', 'A09', 'A13', 'A02', 'A03', 'U06', 'A01', 'A10', 'A11', 'U05', 'U13'})
CAPABILITIES = (
    {'id': 'F00', 'title': 'Foundation, reuse and dependency registry', 'mode': 'NOVEL', 'flag': None, 'dependencies': [], 'wave': 0, 'model_requirement': 'NONE', 'network_requirement': 'NONE', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'U02', 'title': 'Loss-resistant editing and visible save state', 'mode': 'NOVEL', 'flag': 'writing_recovery_v2', 'dependencies': [], 'wave': 1, 'model_requirement': 'NONE', 'network_requirement': 'NONE', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'U01', 'title': 'Resume the previous workspace', 'mode': 'NOVEL', 'flag': 'workspace_tools_v2', 'dependencies': ['U02'], 'wave': 1, 'model_requirement': 'NONE', 'network_requirement': 'NONE', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'U03', 'title': 'Search, commands and recents', 'mode': 'NOVEL', 'flag': 'workspace_tools_v2', 'dependencies': ['U01'], 'wave': 1, 'model_requirement': 'NONE', 'network_requirement': 'NONE', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'U07', 'title': 'Unified task center and honest progress', 'mode': 'NOVEL', 'flag': 'workspace_tools_v2', 'dependencies': [], 'wave': 1, 'model_requirement': 'NONE', 'network_requirement': 'NONE', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'U08', 'title': 'Context and privacy inspector', 'mode': 'NOVEL', 'flag': 'author_context_inspector_v2', 'dependencies': [], 'wave': 1, 'model_requirement': 'OPTIONAL', 'network_requirement': 'OPTIONAL_AUTHORIZED_ONLY', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'U09', 'title': 'Local AI diagnostic and setup guidance', 'mode': 'NOVEL', 'flag': 'local_ai_workflow_inspector_v2', 'dependencies': [], 'wave': 1, 'model_requirement': 'OPTIONAL', 'network_requirement': 'OPTIONAL_AUTHORIZED_ONLY', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'U12', 'title': 'Actionable errors and private diagnostic export', 'mode': 'NOVEL', 'flag': 'workspace_tools_v2', 'dependencies': [], 'wave': 1, 'model_requirement': 'NONE', 'network_requirement': 'NONE', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'U04', 'title': 'Focus, reference split and inspiration', 'mode': 'NOVEL', 'flag': 'writing_focus_v2', 'dependencies': ['U02'], 'wave': 1, 'model_requirement': 'NONE', 'network_requirement': 'NONE', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'U10', 'title': 'Scenario onboarding and progressive disclosure', 'mode': 'NOVEL', 'flag': 'workspace_tools_v2', 'dependencies': [], 'wave': 1, 'model_requirement': 'NONE', 'network_requirement': 'NONE', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'U13', 'title': 'Chinese input, accessibility and scale', 'mode': 'NOVEL', 'flag': 'writing_recovery_v2', 'dependencies': ['U02', 'U03'], 'wave': 1, 'model_requirement': 'NONE', 'network_requirement': 'NONE', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'A04', 'title': 'Temporal semantic story graph', 'mode': 'NOVEL', 'flag': 'temporal_story_graph_v2', 'dependencies': [], 'wave': 2, 'model_requirement': 'NONE', 'network_requirement': 'NONE', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'A05', 'title': 'Character knowledge and mind state', 'mode': 'NOVEL', 'flag': 'character_mind_v2', 'dependencies': ['A04'], 'wave': 2, 'model_requirement': 'OPTIONAL', 'network_requirement': 'OPTIONAL_AUTHORIZED_ONLY', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'A06', 'title': 'Explainable model broker', 'mode': 'NOVEL', 'flag': 'model_broker_v2', 'dependencies': [], 'wave': 2, 'model_requirement': 'OPTIONAL', 'network_requirement': 'OPTIONAL_AUTHORIZED_ONLY', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'A07', 'title': 'Model benchmark and capability evidence', 'mode': 'NOVEL', 'flag': 'model_benchmark_v2', 'dependencies': ['A06'], 'wave': 2, 'model_requirement': 'OPTIONAL', 'network_requirement': 'OPTIONAL_AUTHORIZED_ONLY', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'A09', 'title': 'Asset lineage and derived relationships', 'mode': 'NOVEL', 'flag': 'asset_lineage_v2', 'dependencies': [], 'wave': 2, 'model_requirement': 'NONE', 'network_requirement': 'NONE', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'A13', 'title': 'Production manifest and controlled replay', 'mode': 'NOVEL', 'flag': 'production_manifest_v2', 'dependencies': ['A06', 'A09'], 'wave': 2, 'model_requirement': 'OPTIONAL', 'network_requirement': 'OPTIONAL_AUTHORIZED_ONLY', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'U06', 'title': 'Change impact and selective refresh', 'mode': 'NOVEL', 'flag': 'change_impact_v2', 'dependencies': ['A04', 'A09'], 'wave': 2, 'model_requirement': 'OPTIONAL', 'network_requirement': 'OPTIONAL_AUTHORIZED_ONLY', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'A02', 'title': 'Style metrics and drift', 'mode': 'NOVEL', 'flag': 'style_dna_v2', 'dependencies': [], 'wave': 3, 'model_requirement': 'OPTIONAL', 'network_requirement': 'OPTIONAL_AUTHORIZED_ONLY', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'A03', 'title': 'Evidence-based narrative judge', 'mode': 'NOVEL', 'flag': 'narrative_quality_judge_v2', 'dependencies': ['A04', 'A05'], 'wave': 3, 'model_requirement': 'OPTIONAL', 'network_requirement': 'OPTIONAL_AUTHORIZED_ONLY', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'A01', 'title': 'Bounded story simulation', 'mode': 'NOVEL', 'flag': 'story_simulator_v2', 'dependencies': ['A04', 'A05'], 'wave': 3, 'model_requirement': 'OPTIONAL', 'network_requirement': 'OPTIONAL_AUTHORIZED_ONLY', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'A10', 'title': 'Layered research library', 'mode': 'NOVEL', 'flag': 'research_library_v2', 'dependencies': ['A04'], 'wave': 3, 'model_requirement': 'OPTIONAL', 'network_requirement': 'OPTIONAL_AUTHORIZED_ONLY', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'A11', 'title': 'Revision intelligence and partial changes', 'mode': 'NOVEL', 'flag': 'revision_intelligence_v2', 'dependencies': ['A04'], 'wave': 3, 'model_requirement': 'OPTIONAL', 'network_requirement': 'OPTIONAL_AUTHORIZED_ONLY', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'U05', 'title': 'Selection assistant and partial accept', 'mode': 'NOVEL', 'flag': 'selection_assistant_v2', 'dependencies': ['A11'], 'wave': 3, 'model_requirement': 'OPTIONAL', 'network_requirement': 'OPTIONAL_AUTHORIZED_ONLY', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'U11', 'title': 'Reading, proofreading and publishing checks', 'mode': 'NOVEL', 'flag': 'u11_v2', 'dependencies': ['A03', 'A11'], 'wave': 3, 'model_requirement': 'NONE', 'network_requirement': 'NONE', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'U15', 'title': 'Writing goals and controlled notices', 'mode': 'NOVEL', 'flag': 'u15_v2', 'dependencies': ['U07'], 'wave': 3, 'model_requirement': 'NONE', 'network_requirement': 'NONE', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'A08', 'title': 'Camera grammar and scene direction', 'mode': 'NOVEL', 'flag': 'a08_v2', 'dependencies': [], 'wave': 4, 'model_requirement': 'OPTIONAL', 'network_requirement': 'OPTIONAL_AUTHORIZED_ONLY', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'A12', 'title': 'OTIO and NLE exchange', 'mode': 'NOVEL', 'flag': 'a12_v2', 'dependencies': ['A09'], 'wave': 4, 'model_requirement': 'NONE', 'network_requirement': 'NONE', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'B03', 'title': 'Voice direction and speaker attribution', 'mode': 'NOVEL', 'flag': 'b03_v2', 'dependencies': [], 'wave': 4, 'model_requirement': 'OPTIONAL', 'network_requirement': 'OPTIONAL_AUTHORIZED_ONLY', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'B04', 'title': 'Subtitle editing and timeline', 'mode': 'NOVEL', 'flag': 'b04_v2', 'dependencies': ['B03'], 'wave': 4, 'model_requirement': 'NONE', 'network_requirement': 'NONE', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'U14', 'title': 'Portable project, relink and safe cleanup', 'mode': 'NOVEL', 'flag': 'u14_v2', 'dependencies': ['A09'], 'wave': 4, 'model_requirement': 'NONE', 'network_requirement': 'NONE', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'U16', 'title': 'Safe batch preflight', 'mode': 'NOVEL', 'flag': 'u16_v2', 'dependencies': ['U07', 'A06'], 'wave': 4, 'model_requirement': 'OPTIONAL', 'network_requirement': 'OPTIONAL_AUTHORIZED_ONLY', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'B01', 'title': 'Declarative template library', 'mode': 'NOVEL', 'flag': 'b01_v2', 'dependencies': [], 'wave': 5, 'model_requirement': 'NONE', 'network_requirement': 'NONE', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'B02', 'title': 'Custom agents and workflow SDK', 'mode': 'NOVEL', 'flag': 'b02_v2', 'dependencies': ['A06', 'B01'], 'wave': 5, 'model_requirement': 'OPTIONAL', 'network_requirement': 'OPTIONAL_AUTHORIZED_ONLY', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'B05', 'title': 'Multilingual revisions and terminology', 'mode': 'NOVEL', 'flag': 'b05_v2', 'dependencies': ['A11'], 'wave': 5, 'model_requirement': 'OPTIONAL', 'network_requirement': 'OPTIONAL_AUTHORIZED_ONLY', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'B06', 'title': 'Comic and Webtoon layouts', 'mode': 'NOVEL', 'flag': 'b06_v2', 'dependencies': ['A08', 'A09'], 'wave': 5, 'model_requirement': 'OPTIONAL', 'network_requirement': 'OPTIONAL_AUTHORIZED_ONLY', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'B07', 'title': 'Interactive narrative export', 'mode': 'NOVEL', 'flag': 'b07_v2', 'dependencies': ['A01', 'A04'], 'wave': 5, 'model_requirement': 'NONE', 'network_requirement': 'NONE', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'B08', 'title': 'Writer room and team review', 'mode': 'NOVEL', 'flag': 'b08_v2', 'dependencies': [], 'wave': 6, 'model_requirement': 'NONE', 'network_requirement': 'NONE', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'B09', 'title': 'Project fork and merge', 'mode': 'NOVEL', 'flag': 'b09_v2', 'dependencies': ['A04', 'A09', 'A11'], 'wave': 6, 'model_requirement': 'NONE', 'network_requirement': 'NONE', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
    {'id': 'B10', 'title': 'Offline synchronization foundation', 'mode': 'NOVEL', 'flag': 'b10_v2', 'dependencies': ['B08', 'B09'], 'wave': 6, 'model_requirement': 'NONE', 'network_requirement': 'OPTIONAL_AUTHORIZED_ONLY', 'permission': 'domain.read / domain.write / domain.review as applicable', 'failure_behavior': 'Fail closed; retain draft and explicit stale/error state.', 'reversal_behavior': 'Versioned explicit recovery where supported; already-sent data cannot be recalled.'},
)


def capability_status():
    enabled = enabled_flags()
    return {"schema_version": 1, "experimental": True, "items": [
        {**item, "implementation": ("INTEGRATED" if item["id"] == "F00" else "PARTIAL_INTEGRATED") if item["id"] in INTEGRATED_PACKAGES else "PENDING",
         "available": item["id"] in INTEGRATED_PACKAGES and (item["flag"] is None or item["flag"] in enabled),
         "verification": "NOT_RUN" if item["id"] not in INTEGRATED_PACKAGES else "CONTRACT_VERIFIED",
         "disabled_reason": "IMPLEMENTATION_PENDING" if item["id"] not in INTEGRATED_PACKAGES else (None if item["flag"] is None or item["flag"] in enabled else "SERVER_FEATURE_DISABLED")}
        for item in CAPABILITIES]}
