from __future__ import annotations
from typing import Protocol, runtime_checkable
from ..authorization import AuthorizationScope

@runtime_checkable
class AuthorizationRepositoryProtocol(Protocol):
    def save_role_assignment(self, item: dict) -> dict: ...
    def save_permission_assignment(self, item: dict) -> dict: ...
    def save_role_assignment_with_audit(self, item: dict, audit: dict) -> dict: ...
    def save_permission_assignment_with_audit(self, item: dict, audit: dict) -> dict: ...
    def list_role_assignments(self, principal_id: str | None = None) -> list[dict]: ...
    def list_permission_assignments(self, principal_id: str | None = None) -> list[dict]: ...
    def revoke_role_assignment_with_audit(self, assignment_id: str, audit: dict, protect_last_admin: bool = False) -> dict: ...
    def revoke_permission_assignment_with_audit(self, assignment_id: str, audit: dict) -> dict: ...
    def append_audit_event(self, item: dict) -> dict: ...
    def list_audit_events(self, scope: AuthorizationScope | None = None) -> list[dict]: ...
