from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class IdentityRepositoryProtocol(Protocol):
    def save_user(self, item: dict) -> dict: ...
    def get_user(self, user_id: str) -> dict: ...
    def list_users(self, status: str | None = None) -> list[dict]: ...
    def save_membership(self, item: dict) -> dict: ...
    def get_membership(self, user_id: str, workspace_id: str) -> dict: ...
    def list_memberships(self, user_id: str | None = None, workspace_id: str | None = None, status: str | None = None) -> list[dict]: ...
    def update_membership_status(self, user_id: str, workspace_id: str, status: str, updated_at: str, protect_last_admin: bool = True) -> dict: ...
    def save_membership_with_audit(self, item: dict, audit: dict) -> dict: ...
    def remove_membership_with_audit(self, user_id: str, workspace_id: str, audit: dict, protect_last_admin: bool = True) -> dict: ...
    def update_membership_status_with_audit(self, user_id: str, workspace_id: str, status: str, updated_at: str, audit: dict, protect_last_admin: bool = True) -> dict: ...
