from __future__ import annotations
from typing import Any,Protocol,runtime_checkable

@runtime_checkable
class NovelRepositoryProtocol(Protocol):
    def list(self)->list[dict]: ...
    def create(self,payload:dict)->dict: ...
    def get(self,novel_id:str)->dict: ...
    def update(self,novel_id:str,payload:dict)->dict: ...
    def delete(self,novel_id:str)->None: ...
    def get_data_set(self,novel_id:str,name:str)->list[dict]: ...
    def upsert_character(self,novel_id:str,character_id:str,payload:dict)->dict: ...
    def upsert_location(self,novel_id:str,location_id:str,payload:dict)->dict: ...
    def upsert_timeline_event(self,novel_id:str,event_id:str,payload:dict)->dict: ...
    def upsert_foreshadowing(self,novel_id:str,foreshadowing_id:str,payload:dict)->dict: ...
    def upsert_relationship(self,novel_id:str,relationship_id:str,payload:dict)->dict: ...
    def get_outline(self,novel_id:str)->dict: ...
    def update_outline(self,novel_id:str,payload:dict)->dict: ...
    def upsert_volume(self,novel_id:str,volume_id:str,payload:dict)->dict: ...
    def upsert_scene(self,novel_id:str,scene_id:str,payload:dict)->dict: ...
    def upsert_story_route(self,novel_id:str,route_id:str,payload:dict)->dict: ...
    def list_adaptation_proposals(self,novel_id:str)->list[dict]: ...
    def save_adaptation_proposal(self,novel_id:str,proposal:dict)->dict: ...
    def list_screenplays(self,novel_id:str)->list[dict]: ...
    def save_screenplay(self,novel_id:str,screenplay:dict)->dict: ...
    def get_public_secrets(self,novel_id:str)->list[dict]: ...
    def get_context_sources(self,novel_id:str)->dict: ...

@runtime_checkable
class ChapterRepositoryProtocol(Protocol):
    def list(self,novel_id:str)->list[dict]: ...
    def list_archived(self,novel_id:str)->list[dict]: ...
    def archive(self,chapter_id:str,expected_version:int|None=None)->dict: ...
    def restore_archive(self,chapter_id:str,expected_version:int|None=None)->dict: ...
    def create(self,novel_id:str,payload:dict)->dict: ...
    def get(self,chapter_id:str)->dict: ...
    def save(self,chapter_id:str,document:dict,expected_version:int,source:str="USER",operator:str="local-user",create_revision:bool=True)->dict: ...
    def delete(self,chapter_id:str)->None: ...
    def duplicate(self,chapter_id:str)->dict: ...
    def rename(self,chapter_id:str,title:str,expected_version:int)->dict: ...
    def move(self,chapter_id:str,direction:str)->list[str]: ...
    def history(self,chapter_id:str)->list[dict]: ...
    def restore(self,chapter_id:str,version:int,expected_version:int)->dict: ...
    def save_summary(self,novel_id:str,chapter_number:int,summary:str)->dict: ...

@runtime_checkable
class CanonRepositoryProtocol(Protocol):
    def list(self,novel_id:str)->list[dict]: ...
    def list_pending(self,novel_id:str)->list[dict]: ...
    def get_pending(self,pending_id:str)->dict: ...
    def save_pending(self,item:dict)->dict: ...
    def approve(self,pending_id:str,proposals:list[dict]|None=None)->dict: ...
    def reject(self,pending_id:str)->dict: ...

@runtime_checkable
class GenerationRepositoryProtocol(Protocol):
    def save(self,item:dict)->None: ...
    def get(self,job_id:str)->dict: ...
    def load_all(self)->list[dict]: ...
