from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class LoreRepositoryProtocol(Protocol):
    def create_evidence(self, item: dict) -> dict: ...
    def get_evidence(self, evidence_id: str) -> dict: ...
    def list_evidence(self, novel_id: str) -> list[dict]: ...
    def invalidate_evidence(self, evidence_id: str, reason: str) -> dict: ...
    def create_proposal(self, item: dict) -> dict: ...
    def get_proposal(self, proposal_id: str) -> dict: ...
    def list_proposals(self, novel_id: str, status: str | None = None) -> list[dict]: ...
    def link_evidence(self, relation: dict) -> dict: ...
    def list_proposal_evidence(self, proposal_id: str) -> list[dict]: ...
    def approve_proposal(self, proposal_id: str, approved_payload: dict, reviewer: str) -> dict: ...
    def reject_proposal(self, proposal_id: str, reviewer: str, reason: str | None = None) -> dict: ...
    def create_memory(self,item:dict)->dict: ...
    def get_memory(self,memory_id:str)->dict: ...
    def list_character_memories(self,character_id:str,status:str|None=None)->list[dict]: ...
    def list_memories(self,novel_id:str,status:str|None=None)->list[dict]: ...
    def supersede_memory(self,memory_id:str,replacement:dict)->dict: ...
    def retract_memory(self,memory_id:str,reason:str)->dict: ...
    def approve_proposal_with_memory(self,proposal_id:str,approved_payload:dict,reviewer:str,memory:dict)->tuple[dict,dict]: ...
    def create_snapshot(self,item:dict)->dict: ...
    def get_latest_snapshot(self,novel_id:str,scope:str,scope_key:str)->dict|None: ...
    def list_snapshots(self,novel_id:str,scope:str|None=None)->list[dict]: ...
